### ISSUE TITLE
Nanopaste again

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#1012]
Sorry, peeps, but I don't really know how the issue system works or how to get updates on it and it got closed before I ever noticed.  Here's the relevant code.

http://i.imgur.com/wBU5pCT.png

Nanopaste is supposed to be able to repair robot limbs and I've highlighted the relevant lines.  The issue is the organ/external/s has an if-open check, and robot limbs can't be opened.  Only organic limbs can (by a scalpel, on an op table).  Nanopaste was intended as the R&Dable upgrade to cable coils and welder.  like the code is right there.  it's already written.  just need to delete the one miswritten line and fix the spacing.  if(s.open == 1).

**Comment by CakeQ** [comment]
Fixed for next patch!
