### ISSUE TITLE
Admin verb and player panel not working during a round.

### ISSUE THREAD

**Issue by Metichi** [Apollo-Community/ApolloStation#1039]
Some verbs dont work for me, like "Player panel new" (wich pops up the window but it has no names on it) and "Allow player to respawn", wich just gives the error "It appears you didnt select a ghost" without prompting you to select one.

**Comment by Luthhran** [comment]
Both of those seem to work fine for me

**Comment by rjtwins** [comment]
Something must have failed to init.

**Comment by rjtwins** [comment]
This is most likely caused by a failure to sync you with the sql on login.
