### ISSUE TITLE
Plumbing Request

### ISSUE THREAD

**Issue by hexagoncode** [Apollo-Community/ApolloStation#104]
Roboticist needs a sink near the office, and maybe latex gloves. Surgery at the surgery table is a gory mess.

**Comment by GutsySS13** [comment]
they don't have any way to sedate their patient (victim) either.

**Comment by Kwask** [comment]
A good whack to the head is all the sedation you need ;)

Added a sink and anesthetic cabinet to robotics on the sectors branch, so no one do the duplicate work on master :8ball:
