### ISSUE TITLE
Senior Engineers have access to Cargo

### ISSUE THREAD

**Issue by Luthhran** [Apollo-Community/ApolloStation#1041]
I looked at the code and nothing in the Senior Engineer seem to be cargo related, yet they can open the doors.

**Comment by CakeQ** [comment]
which doors?

**Comment by mewseht** [comment]
This is because the main front door and the other two doors also named "Cargo Office" can be opened with the head access that Senior Engineer's have.

**Comment by Luthhran** [comment]
@CakeQ  Front doors. If Mew is right, then if you update the server it should be fixed, cause I removed the head access from Seniors yesterday

**Comment by rjtwins** [comment]
I'll confirm this when I get back home and upate this issue.

**Comment by rjtwins** [comment]
Was not fixed yet
