### ISSUE TITLE
Bucket filled with welding fuel on someone is OP

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#105]
Pouring it on someone will poison them badly. It's not even possible to use antitoxins to cure it?

**Comment by lmas** [comment]
This happends because of how the reagent system works. The bucket's contents will simply be transfered to the body, like a normal syringe. And since a bucket can hold a lot of chemicals... yeah, bad times for the poor dude.

**Comment by Kwask** [comment]
I added a thing so it should have about a 1/4 chance to do 1 poison damage every life cycle, as opposed to it doing 1 poison damage every life cycle like it was before. The issue of there being a huge volume of the reagent inside of the person is prevalent with all reagents. If you need to get huge volumes of chemicals out of someone, perform a dialysis inside of the sleepers
