### ISSUE TITLE
Allowing players to be promoted as ghosts using the promotion/demotion admin verb

### ISSUE THREAD

**Issue by Arrowhead154** [Apollo-Community/ApolloStation#1053]
Admins are unable to promote characters when they're ghosts, making them be in the game to actually promote them instead of being able to ghost and then promote. It'll be a big convenience for both admins and players if this was fixed so players could spawn in directly as their role instead of spawning, promoting, and cryo-ing.

**Comment by CakeQ** [comment]
I think it would be better to be able to access the char database as an admin and do it from there so that you can apply demotions and promotions when they aren't online. Useful for the role apps and for shitter demotions
