### ISSUE TITLE
Can't build on arrival shuttle/arrival shuttle yields no alarms

### ISSUE THREAD

**Issue by wykthor-btracker** [Apollo-Community/ApolloStation#1059]
Can't build on arrival shuttle, and we need to build on it because it's a meteor shower target, so people spawn and die.

Also the arrival shuttle area has no atmos alarm, so the engineers are oblivious to the fact if only checking the station alerts computer

**Comment by rjtwins** [comment]
It was decided some time ago that we would make the arrival shuttle indestructible.

**Comment by rjtwins** [comment]
Its indestructible now so this issue is void.
