### ISSUE TITLE
Bugged Z level wires

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#106]
Rasengetsu reported this.

**Comment by Kwask** [comment]
Aparently happens when the powernet's total power drops to 0, the z-cable gets cut off for some reason

**Comment by halworsen** [comment]
Any chance this is getting a fix soon? Telecomms is suffering badly from this issue.

**Comment by nullbear** [comment]
kwask said when he gets around to it
.so not likely soon.

**Comment by Kwask** [comment]
snark snark snark

I wasn't the one who made z-cables, so I've got just as much of a clue of what I'm doing as anyone else

**Comment by nullbear** [comment]
xD i was gunna get around to it eventually, like catwalks, but im busyyyy

**Comment by lmas** [comment]
Ops, I thought you were the creator kwask, so I assigned it to you. Also I'm in tokyo for the next weeks so I'm not available either.
