### ISSUE TITLE
Derilict Bugs

### ISSUE THREAD

**Issue by Luthhran** [Apollo-Community/ApolloStation#1087]
1- If you place an air alarm thingy on the walls, the next round, it won't be able to take an air sample in the room

2- If you fill up a room with air, the next round, it'll be empty

**Comment by CakeQ** [comment]
2 is caused because each tile in mapping has their own air configuration which is loaded on startup. I'm assuming Atebite didn't change that.

**Comment by halworsen** [comment]
^

Floors are airless, so this is a mapping issue.

**Comment by Faustico** [comment]
On round start no wires on the derelict will transfer power, they have to be cut and replaced

**Comment by Haldreithen** [comment]
There's no derilict anymore, Issue closed
