### ISSUE TITLE
Records and character details are being deleted

### ISSUE THREAD

**Issue by Arrowhead154** [Apollo-Community/ApolloStation#1088]
Players are losing their character records, flavor texts, and other various details about their characters upon new round start-up. Not studied it further if replacing them and then starting a new round still saves them or not.

**Comment by astralenigma** [comment]
#1084 duplicate

**Comment by Luthhran** [comment]
This was filled with a couple command recommendations and promotion notes.. Q.Q https://gyazo.com/328208b05b65466cc0c7d97d3e5fbf26

**Comment by CakeQ** [comment]
Nothing can really be done about missing records. If the problem happens again please re-open this
