### ISSUE TITLE
Tokamak Engine problems

### ISSUE THREAD

**Issue by Luthhran** [Apollo-Community/ApolloStation#1095]
I've tried to test the engine, but it isn't quite possible, cause there doesn't seem the be the console the wiki guide is mentioning to set up the parts anywhere. Also, the part fabricator doesn't accept alloys, unless it's something else than catametallic alloy we need to use. Also, if there's a spider or any mob of the sort, the arc emmiters won't shoot them

**Comment by rjtwins** [comment]
The console is located in the engine monitoring room. It is definitely there.
The alloy it needs to be a 50/50 alloy (so 50% mineral and 50% glass/metal). 
Also make sure the alloy fab actually has power.
For the mobs, I will adjust it so they get shocked.
