### ISSUE TITLE
SECTORS: Ambient Sounds 

### ISSUE THREAD

**Issue by hexagoncode** [Apollo-Community/ApolloStation#110]
Ambient sounds won't stay toggled off. 
Crossing into a new zone starts them again, but clicking the toggle gives the message for the ambient sounds coming back on. Toggling it again to off turns it off. But moving re-enables the sounds again.

**Comment by Kwask** [comment]
Ambient sounds fixed, but now music from the jukebox doesn't go away unless you toggle ambience
