### ISSUE TITLE
Infinite robot debris spawning from dead spiderbot.

### ISSUE THREAD

**Issue by bIuebit** [Apollo-Community/ApolloStation#1105]
When I played a round earlier, I came back to robotics to find it completely covered in oil and robot debris. Whenever it was on screen, it lagged really bad. I've never done a bug report before, so I'm not really sure what to put here, but I'll be as thorough as I can be to help duplicate it.
The cyborg F.U.N.C.T.I.O.N. had self destructed earlier in the round. I scooped up the MMI left behind, ran to robotics, and put it in a spiderbot. I don't know if I messed up or if the player went afk, but as far as I know F.U.N.C.T.I.O.N didn't move again. Some time goes by and I return to robotics to see an absolute mess. Oil everywhere and debris everywhere. My frames start dropping right away. The spider is there, still attacking F.U.N.C.T.I.O.N. Every few seconds, parts flew out of the spiderbot F.U.N.C.T.I.O.N. After the spider was killed, the spiderbot kept spewing parts every two seconds, and it continued to tank my frames. I tried shoving it in a locker, but it kept spewing parts through the locker. Next step, obviously, was to shoot it out the mass driver.  I ran through the hallways dragging the locker behind me, leaving a trail of oil and parts. When I got to the chapel, I chucked it in the mass driver and launched it, solving the problem. And an album of the mess: http://imgur.com/a/QjXUk
EDIT: I have no idea how to format this.

**Comment by rjtwins** [comment]
Given your screenshot I'm making this a feature.
