### ISSUE TITLE
tracker map

### ISSUE THREAD

**Issue by eeetem** [Apollo-Community/ApolloStation#1123]
tracker map is bugged

**Comment by eeetem** [comment]
it has old map

**Comment by rjtwins** [comment]
We'll generate a new one for it thanks for the heads up.

**Comment by eeetem** [comment]
Also map in survival kit is outdated too

**Comment by halworsen** [comment]
Map on the website is updated now

**Comment by CakeQ** [comment]
Dealt with here: https://github.com/Apollo-Community/ApolloStation/pull/1131
