### ISSUE TITLE
SECTORS: Engineering Shuttle Pod

### ISSUE THREAD

**Issue by hexagoncode** [Apollo-Community/ApolloStation#114]
- [x] Engineering shuttle pod has a wall behind the fore door at Apollo and the engineering station.
- [ ] Entering shuttle with welding mask removes the UI completely.
- [x] Shuttle pods NEED something to keep track of location more accurately than bluespace triangulation that takes a minute to work. Even 1960s and 70s spacecraft had inertial guidance that could track relative positions.
- [x] Shuttle does not appear to refuel when parked over the refueling floor at the engineering station. May be true for the main station as well. Parked over it and changing direction, it will not increase the fuel. This could be because a mod teleported it into place.
- [x] Every time you leave the shuttle, all items appear to be gone and you have to log out and back into the session to see them.

**Comment by hexagoncode** [comment]
Shuttle pods NEED something to keep track of location more accurately than bluespace triangulation that takes a minute to work. Even 1960s and 70s spacecraft had inertial guidance that could track relative positions.

**Comment by hexagoncode** [comment]
Shuttle does not appear to refuel when parked over the refueling floor at the engineering station. May be true for the main station as well. Parked over it and changing direction, it will not increase the fuel. This could be because a mod teleported it into place.

**Comment by hexagoncode** [comment]
Every time you leave the shuttle, all items appear to be gone and you have to log out and back into the session to see them.

**Comment by hexagoncode** [comment]
Entering shuttle with welding mask removes the UI completely.

**Comment by lmas** [comment]
Entering shuttle with welding mask/googles toggled on/off does nothing to the UI, works as expected. Probably accidently toggled off the UI by pressing the F12 key.
