### ISSUE TITLE
Heart transplants are currently impossible

### ISSUE THREAD

**Issue by Faustico** [Apollo-Community/ApolloStation#1166]
Attempting to remove someones heart currently kills them from 200+ immediate toxin damage. The drug that is supposed to counter this (Potassium Chlorophoride) does not stop it. 
To fix this you could either figure out whats wrong with Potassium Chlorophoride and fix that, or change the damage to suffocation so you can use dexalin plus to counter it (maybe).

**Comment by halworsen** [comment]
Looks like heart surgery isn't even implemented yet.

**Comment by rjtwins** [comment]
Looking into this

**Comment by rjtwins** [comment]
Fixed, once you administer Potassium Chlorophoride you have 10 secconds to transplant the heart.
