### ISSUE TITLE
SECTORS: Pods teleport everything loose in a 9x9 square

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#117]
If a pod is on the station with some items around it, for example, and one then recalls the pod back to science, the pod along with items around it will get teleported.

**Comment by Kwask** [comment]
Intentional feature, you're advised not to recall the shuttle if it is inside of a structure

**Comment by lmas** [comment]
That wasn't in the manual!

**Comment by hexagoncode** [comment]
I like this. It's like a mini singulo. And after some experimentation about jumping through it myself, it looks like you will teleport with the ship if you're in that area. Which is fine. You can't get lost in bluespace. Yet.
