### ISSUE TITLE
Moon doesn't have anywhere to use the drill on

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#1174]
So you can use the drill on the moon, right? Well, you can't exactly use it, even though you can set it up. There's no ores for it to dig up, so it just stops immediately. Dunno what the deal with that is, but you can't use the drill on the moon because there's nothing to drill for.

**Comment by Awantje** [comment]
I did my best to reproduce this but 3 people all reported and got this working.

**Comment by Draco16** [comment]
Tested this on two different shifts, the underground minerals are not being applied to the moon, only the asteroids.  Everything works fine on the asteroids.

**Comment by rjtwins** [comment]
99% sure this is fixed now
