### ISSUE TITLE
SECTORS: sometimes pods will not work because someone else is assigned as pilot

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#118]
Pilot leaves the pod and someone climbs in and try to fly it, it won't let the new pilot control it because pod thinks the old pilot is still there.
Nullbear got this one too.

**Comment by lmas** [comment]
Getting runtime errors:

```
proc name: process (/obj/item/device/spacepod_equipment/engine/process)
  source file: equipment.dm,351
runtime error: Cannot read null.pilot
```

**Comment by Kwask** [comment]
Any idea how to reproduce the problem with the nonexistant pilot?

**Comment by lmas** [comment]
Jump in, jump out. Pod was the mining pod. Haven't tested it too much yet, need to query nullbear more about it. But the runtime error above shoved up for me when I was trying out the pods on a local server.

**Comment by Kwask** [comment]
The runtine should be fixed now, lemme know if any more appear

**Comment by Kwask** [comment]
Awaiting instructions on how to reproduce

**Comment by lmas** [comment]
Tried it again, no dice and no runtime errors. Did you remove the `Switch to passenger's/pilot's seat` verb?
