### ISSUE TITLE
Promotions/Card Modification HoS

### ISSUE THREAD

**Issue by InvidiaSH** [Apollo-Community/ApolloStation#1184]
Promotions and card modification for HoS is bugged (at least witnessed in the case of using the title Commander), would need further debugging to determine cause, but I would guess it has something to do with the permanent editing of roles conflicting with my role as HoS (Commander in this case)

CKey: XRev

**Comment by rjtwins** [comment]
Looking into this now.

**Comment by rjtwins** [comment]
Should be fixed, need feedback

**Comment by rjtwins** [comment]
Fix confirmed
