### ISSUE TITLE
The circuit imprinter does not accept phoron sheets

### ISSUE THREAD

**Issue by Delnth** [Apollo-Community/ApolloStation#1202]
i.e impossible to print the **RUST Fuel Compressor Board** without admin assistance. It's probably the same for a few other boards.

**Comment by nullbear** [comment]
Nice

**Comment by Awantje** [comment]
There are 2 ways I can fix this. 1. change the boards that need it to not need phoron. (this makes sense to me) Or make the machine accept phoron. (Way harder and makes less sense to me.) I will do the first implementation unless anyone objects then ill yell the second option is not possible for me to do and we gotta do the first one anyways.

**Comment by InvidiaSH** [comment]
Fixed in commit 0e6cf915b7dfb7621faabe9a1dd281b5845d7ad9
