### ISSUE TITLE
Simple mobs are immune to engine shocking

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStation#1205]
Simple mobs such as spiders or mice, are completely immune to the engine lighting shocking them, They do take burn damage however this burn damage does not take down their total health,... Who made the engine apply direct burn damage instead of health damage?

**Comment by BlueSushii** [comment]
![image](https://cloud.githubusercontent.com/assets/16139506/20985268/c922a646-bc91-11e6-8674-e4016863349a.png)

**Comment by InvidiaSH** [comment]
Fixed in commit dff1ebcd34194f773541fcb03467bea4598a8082
