### ISSUE TITLE
Court Cardreader not working properly for IAA

### ISSUE THREAD

**Issue by Dilqui** [Apollo-Community/ApolloStation#1208]
As the title says. Basically, when playing as the IAA, and there is a tribunal going on, when I try to swipe my ID, it tells me access denied, although as IAA I should have the authority to be a justice.

**Comment by ghost** [comment]
Just made a pull request, should be fixed once it gets accepted.

**Comment by InvidiaSH** [comment]
Fixed in commit ed41750ae0a01983c813342724cafc16af7be355
