### ISSUE TITLE
Entry level access for Internal Affairs, and headset.

### ISSUE THREAD

**Issue by Dilqui** [Apollo-Community/ApolloStation#1213]
As the title says. We agreed upon on a previous community that IA should have entry level access to all departments. Here is the copy-paste code needed to be pasted into the access system:

(access_iaa, access_court, access_sec_doors, access_maint_tunnels, access_medical, access_morgue, access_research, access_tox, access_security, access_mailsorting, access_cargo, access_cargo_bot, access_qm, access_mint, access_mining, access_mining_station, access_eva, access_engine, access_engine_equip, access_external_airlocks, access_construction, access_bar, access_janitor,
			            access_crematorium, access_kitchen, access_hydroponics, access_theatre, access_chapel_office, access_library, access_clown, access_mime, )

Similarly, here is the code for the headset changes decided upon a previous meeting:

H.equip_to_slot_or_qdel(new /obj/item/device/radio/headset/heads/iaa(H), slot_l_ear)

/obj/item/device/radio/headset/heads/iaa
    name = "Internal Afairs headset"
    desc = "The headset of centcoms watchdog."
    icon_state = "com_headset"
    item_state = "headset"
    ks2type = /obj/item/device/encryptionkey/heads/captain

If I knew how to use this, then I would upload the changes. Since I can't, I'll just post this here and let you guys change it.

**Comment by InvidiaSH** [comment]
Fixed in commit 5d1fad2778e76477ac9008d981eb5a1f67f97818
