### ISSUE TITLE
QM doesnt get Cargo Account Info at round start

### ISSUE THREAD

**Issue by Butterrobber202** [Apollo-Community/ApolloStation#1214]
Can't use the EFTPOS without it

**Comment by InvidiaSH** [comment]
Fix attempt in commit d705249277f2f2e481de1a42aa1aa40b43458a1d

Need feedback on whether it's fixed or not.

**Comment by InvidiaSH** [comment]
Fixed in commit d705249277f2f2e481de1a42aa1aa40b43458a1d
