### ISSUE TITLE
Pipe dispenser

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#1221]
Please add: /obj/machinery/atmospherics/unary/outlet_injector
air injector
to:
ApolloStation/code/game/machinery/pipe/pipe_dispenser.dm
thanks.

Request from Faustico, relayed by Ptar.  The pipe dispenser sorts the pipes through some black numbering magic and I don't want to read or figure it out so someone else please

thanks.

**Comment by InvidiaSH** [comment]
Fixed in commit 397b8a72eea00d81b57a72a50e9f97239015b85b
