### ISSUE TITLE
Science lost maint access in the med-sci sec-engi remap.

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#1222]
Sci can't even reach their escape pod or the dorms (or my precious yellow airtanks and other maint things).  Rose has reported that med still has theirs, and sec/engi both have maint access, so I have to assume this is an oversight.
Screenshots: relevant doors.
http://i.imgur.com/dX2VZZM.png (This one is high up near med, but we could make it all the way to secdorms prior and also the hidden bar is up there now wow)

http://i.imgur.com/Ccluh1B.png
http://i.imgur.com/EgzFvU4.png
http://i.imgur.com/GFJaaMh.png These three which connects to the one above for aforementioned reasons.

http://i.imgur.com/61LYGPu.png These two because being able to get out would be really nice.

http://i.imgur.com/BwR4ILW.png muh dorms.  please.

http://i.imgur.com/X3ZgOqD.png Both of these.  The one in the tunnel and the one connecting the department to the tunnel.

http://i.imgur.com/8uZuijt.png This is directly under those doors.

http://i.imgur.com/ClAUhe0.png Continues our tunnel.
http://i.imgur.com/v1pF8Mc.png

And finally these two, left and right of my ghost.  http://i.imgur.com/Ob1HYOB.png
please fix.  They are probably set to require multiple accesses (sci and maint) instead of one access.
thanks

**Comment by InvidiaSH** [comment]
Fixed in commit e81dd96befcf4d7c0d875aa1418dc5483235d346

I didn't grant all of the access ideas seeing as I vastly disagree giving all science members access to some of those doors. Especially the ones that are actually cargo access. Also, some of the doors already were All Access.

**Comment by dontdothis** [comment]
The screenshots were just an approximation of what the access used to be prior to the remap.  I've no objections to some areas being restricted, but I think I've noticed some issues I'll mention in a future issue once I've had time to test it.

**Comment by InvidiaSH** [comment]
I doubt you require more access to maint than I already gave Science in that commit honestly.
