### ISSUE TITLE
Wrenching a Coolant Injector and Unwrenching it Changes it to an air Injector That You Can't Pick Up

### ISSUE THREAD

**Issue by Faustico** [Apollo-Community/ApolloStation#1226]
Fairly straightforward bug, to replicate just get a coolant injector from the pipe dispenser in atmos, wrench it to the ground, then unwrench it. The air injector cant be picked up, doesnt have a pick up option when right clicked, and cant be drag/dropped into the pipe dispenser to get rid of it.

**Comment by InvidiaSH** [comment]
It worked when I tried to reproduce it.

**Comment by InvidiaSH** [comment]
No further response. I'll close the issue.
