### ISSUE TITLE
Loosing jobs when using the "Reset changes" button in the character menu

### ISSUE THREAD

**Issue by Pygmali** [Apollo-Community/ApolloStation#1227]
Heyo,

It happen twice, if I use the "Reset Changes" on the character menu, I loose all my job in the security department (HoS, Warden, Detective, Officer). Only left the Civilians job and my HoP job.

**Comment by Haldreithen** [comment]
It's kind of a feature, like it was intended to be, though if people want it changed I can look into it. It's basicly for a full character reset. Btw, if you want your roles back (if you don't have them yet) Ahelp while either Me, Koenigsegg, OminousBrainworm or XRev are online.

**Comment by InvidiaSH** [comment]
Yeah I talked to you about this over Discord. It's intended to work like this. Never press Reset Changes if you don't want to lose your occupation settings.
