### ISSUE TITLE
The new HoS head RIG.

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#1241]
It was pulled from a pre-existing admin-only RIG that should not see the light of day.

HoS's combat RIG: Mounted laser cannon.  Thermals. AI-tracking disruptor.  Grenade launcher (Comes in three flavors: Flashbang, smoke, EMP.).  Chem dispenser.  A power sink.  Ungodly hideous armor values.
Edit: This suit seems to have a mounted egun instead of a laser cannon but it's still concerning.

Rescue suit for CMO is fine.

I think the Captain's rig is a renamed ERT leader rig, which, y'know what.  Okay.  Whatever.  It's not showing up in the code so it was probably renamed from the map.  Still fairly strong but it's the weakest of the ERT suits if my guess is correct.  Might have conflicts w/ERTs because of appearance.

Generally speaking, anything that has a mounted gun should be avoided because they cause problems in the same vein as stungloves, which were removed-- being able to surprise-blast someone out of nowhere with nothing in your hands.

Thermals were removed from security for good reason.

Grenade launcher, power sink, etc.  I don't think I need to comment on those.  The armor value is also ridiculous.

Please kill it immediately.

**Comment by Haldreithen** [comment]
The HoS suit doesn't have a grenade launcher, power sink or chem dispenser. It only has jetpacks, thermal view and and a gun. I'm going to check myself to change the armor values too. Also, as far as I know, thermals only make your screen red, though if it does something else, tell me.
