### ISSUE TITLE
Readd the slater

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#1249]
This was discussed and needs to be done but I keep forgetting it.

**Comment by Haldreithen** [comment]
You mean like re-adding the Slater?

**Comment by Awantje** [comment]
yes

**Comment by InvidiaSH** [comment]
Does anyone know if there's something wrong with it? I kinda want to re-implement it if it works fine.

**Comment by Haldreithen** [comment]
There's nothing wrong with it, it was removed cause someone didn't like it.

**Comment by InvidiaSH** [comment]
Supposedly done! 💃
