### ISSUE TITLE
Disposals Virology Bug

### ISSUE THREAD

**Issue by Lorelai17** [Apollo-Community/ApolloStation#1262]
Virology disposals chute leads directly into the Mailing Loop, NOT the disposals loop. So every time a bunch of quarantine bags and boxes get thrown away, they end up in the mail loop going around in circles forever. Instead of to disposals to get incinerated/thrown away.

**Comment by Pygmali** [comment]
Use the tagger, set it to Incinerator, problem solved. (That what I do as HoP each time I see something from the virology disposal)

**Comment by InvidiaSH** [comment]
I suppose this has something to do with quarantine bags being considered as tagged items by the junction sorter. Can be fixed manually by the solution provided by @Pygmali . Also, this way it can be used to send them somewhere by tagging it yourself at Virology. Issue closed.
