### ISSUE TITLE
Community Meeting 2017 Simple Things

### ISSUE THREAD

**Issue by Faustico** [Apollo-Community/ApolloStation#1263]
I few things I remember Awan telling us to "put on the issue tracker", hoping this is the correct place for it.

- Add toxin as a thing you get from butchering spiders
- Rename Tricordrazine to Tetrazine
- Add some of the medbay equipment to the normal loadout items. (Medical Scrubs, Health HUDs, and stethoscopes were mentioned by name)

That was all the "easy" things that I saw passed in the community [meeting document](https://docs.google.com/document/d/1cyLW-k2O8-RQu_lK0kFXpACQHTxpml-7A_k65aJYXpE/edit#) , however I left before the last three items were discussed so there might be more.

**Comment by InvidiaSH** [comment]
Add some of the medbay equipment to the normal loadout items. (Medical Scrubs, Health HUDs, and stethoscopes were mentioned by name)

>> As was commented on the document, non-medical shouldn't have free loadout access to those items in the first place. Except maybe one could make an argument for stethoscopes.

**Comment by Faustico** [comment]
I am almost positive that the majority agreed that adding these items couldn't hurt, as security already has access to their HUDs through the loadouts (nobody sees that as a problem) and the scrubs are just cosmetic. The comment that I am seeing on the document was made by Silvia before the discussion took place.

**Comment by InvidiaSH** [comment]
Security has access to their huds via hud sunglasses. I don't believe they're standard loadout equipment actually.

**Comment by Haldreithen** [comment]
They are in the loadout. You can't join with them unless you are security though.

**Comment by InvidiaSH** [comment]
Fixed in commit 72d7527617f6091a04d5d9d4b10f32cefd75d7a6
