### ISSUE TITLE
Mapping issues.  Warden, some maint.

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#1265]
- [x] http://i.imgur.com/yh0MSY3.png Warden shutter button appears to not be linked to the actual shutters.  Doesn't seem to do anything when pressed.

- [x] http://i.imgur.com/TxekFBN.png I don't think anyone has actual access to their own fire closets except maybe engineers, which is a little nonsensical.  This is the sci maint one.  I don't remember what the results were for the one by the chef office, but I think it needs looking at too.

- [x] http://i.imgur.com/L11KQec.png These two vertically-stacked maint doors are Sci-only, and other people going through maint have to walk all the way out and around.

- [x] http://i.imgur.com/iA0ujSQ.png Toxins needs more than one row between the top and the table.  Maneuvering canisters is a nightmare and I often have to climb onto a table to get them into place.

- [x] http://i.imgur.com/FYLoxLr.png This maint door doesn't work for science access.

**Comment by InvidiaSH** [comment]
First issue: Marked for addressing.
Second issue: Intended functionality.
Third issue: Intended functionality seeing as other people going through maint would have access to Science otherwise.
Fourth issue: This is mapping. If anyone can do it with the space provided, marked for addressing.
Fifth issue: Pretty sure I added it in in commit #1222 , marked for addressing if otherwise.

**Comment by dontdothis** [comment]
Second issue: I question the wisdom of locking the firesuits so that only the people who will already be showing up in fireproof EVA suits can reach them.  But ok.

Third issue: The vertical maint doors are science-locked.  The ones above and below my ghost.  The whole point of a four-way is to let people through maint without forcing them to go around.  You can prevent people from entering sci by making sure the two doors horizontal are sci-locked (which they are, I am pretty sure.)

All they get if you let them pass through that chamber is a tiny 2x3 area, and not the science department.  Really doubt this is intended.

Fourth: kkkkk

Fifth: Confirmed for not working as of posting yesterday.  I did check before posting.

**Comment by Haldreithen** [comment]
I'll deal with toxins right now, I'm getting really annoyed when I work in there. I'll check the science maint door too. (fifth issue and fourth issue dealt with)

**Comment by InvidiaSH** [comment]
@dontdothis Second issue: This is totally intended, it's because engineers won't always be wearing firesuits (roleplay purposes).

**Comment by Andrew-Fall** [comment]
Warden Office Fixed.

**Comment by InvidiaSH** [comment]
Marks all as fixed. Issue closed.
