### ISSUE TITLE
Energy Crossbow

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#1273]
The ebow is atrociously shitty.  Max cell charge 600, costs 250/charge.

40 agony on hit, 10 damage.

You need 100 agony to stun.

The ebow is currently so shitty that it can't stun anyone at all.  It fires two shots, then runs out of charge for a grand total of 80 agony-- if both shots hit.  

At the absolute least, I'd say give it ten shots at 40 agony, like a self-recharging stun revolver.  That's incredibly lackluster for an antag weapon though.

Could make it like a ranged stun baton-- stuns for two ticks on hit, applies agony until they pass out.

Could crank up the toxloss to something terrifying, like 50 or 60.  Easiest damtype to cure, doesn't break bones.

It needs more shots and a boost to power, though.

**Comment by InvidiaSH** [comment]
Fixed in commit 80292d05490a6521f417174a40ab91c84d22f614
