### ISSUE TITLE
Communication system for pods

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#128]
The pods should have some sort of harder communication system to contact the station. It could be something you have to work for to do like morse. It could just cost a lot of power (and the station has to use a console to send something back) or all messages arrive at the communications console on the bridge/captains office and have a delay of 180 seconds. (also the only place they can be send from and one message per 30 sec)

**Comment by Kwask** [comment]
Why can't you use a station-bounced radio?

**Comment by Awantje** [comment]
those are z-level bound right. as in when you get to far you cant?

**Comment by Kwask** [comment]
Fairly certain they're universal, so they'll work everywhere

**Comment by Awantje** [comment]
I tested it they are not working on some z-levels but well you could just say they are out of range. I will close this because its old and I dont see it changing.
