### ISSUE TITLE
Issues with Robotics

### ISSUE THREAD

**Issue by Draco16** [Apollo-Community/ApolloStation#131]
The little robots robotics can build mostly all have problems.  
- [x] The cleaning bot does not listen when told to NOT patrol the station and often gets obsessed with trying to get into certain areas and ends up ignoring everything else.
- [x] The floor bot just straight up doesn't work.  Load it full of tiles and put it in a room missing all it's tiles and it just sits there beeping and booping.  
- [x] The ED-209 doesn't seem to know how to patrol.  It can follow orders and go where told to but it's auto patrol does not do anything and it simply sits in the hallway doing nothing.  
- [x] The Exosuit Fabricators won't have access to the main R&D server and can't be updated. EDIT: Testing revealed that getting the Fabricator and the R&D console to be at the exact same lighting level allowed them to sync.
- [x] The mounted cable layer does not seem to work, it can be loaded full of wire, turned on, and it can eject set amounts of loose wire, but it won't actually lay any wires.  
- [x] The farmbot doesn't work anymore. It's disabled in the source.

**Comment by lmas** [comment]
Only security can set patrol mode for the ED, seen it patrolling around during the week.

And the fabricator has a buggy area check; a room area is split up into different light areas or something. Same issue as with the jukebox area check. @Kwask has more info on this.

**Comment by lmas** [comment]
Same thing with the cleanbot, unlock it's controlls with an ID with high enough access and then you can toggle it's patrol mode off. It will still try to go to any mess in the current area and clean it up but at least it won't run away to the other end of the station.

**Comment by lmas** [comment]
~~Floorbot was only designed to fix floor tiles open to space. It doesn't make nice tiles for you. I'll see if I can hack it a little to force it to make nice tiles too.~~ Nevermind, can't get it working at all now. It's damned buggy.

Edit: I'm going to cherry-pick [some commits from bay12](https://github.com/Baystation12/Baystation12/pull/8991/commits) which should fix most of the bot issues.

**Comment by lmas** [comment]
Made #182 which should solve the bot issues for now.

**Comment by lmas** [comment]
6dbde1fd3ef211cee653ed94df7d0cab26a30697 Should fix the cable layer.
