### ISSUE TITLE
fix of Slater Engien room door

### ISSUE THREAD

**Issue by CdrRiley** [Apollo-Community/ApolloStation#1318]
as forman or as QM you cant aces the engien room on the slater please fix  it pealse

**Comment by CdrRiley** [comment]
,

**Comment by InvidiaSH** [comment]
I think thats because it makes sense for an engine to be engineering access, and foreman doesnt have that access, which is also logical. Not a bug, but okay.

**Comment by Andrew-Fall** [comment]
Should we change it or?

**Comment by Haldreithen** [comment]
I personally don't think so

**Comment by InvidiaSH** [comment]
Well. That makes two of us. Issue closed.
