### ISSUE TITLE
Suit Cooling Units

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#1320]
Please add two of these to EVA, right by the magboots and jetpacks:
/obj/item/device/suit_cooling_unit
.

When I asked Kwask why there were no suit cooling units, he said IPCs were grossly overpowered already and needed racial weaknesses.  After asking him some more questions, it seemed he didn't really actually know IPC code too well.
Weaknesses:
- IPC body parts are all mechanical and auto-detach when damage maxes out.  Two lasers to head insta-kills IPCs.
- IPC extremities are extremely easy to remove via laser or harmwelder.
- EMP will either kill or significantly disable an IPC.
- Mechanical limbs flip out at any sign of damage.  Failure checks are equal to prob(damage), and the check is e x t r e m e l y frequent, which anyone who has ever used a prosthetic knows.  Even tiny amounts of damage will have you constantly dropping things.
- Overheat in low-pressure environments, and have to attach a suit cooling unit to their suit slot if they don't want to fry.  Roasting even a little means they'll be constantly dropping everything, since it's whole-body damage.

pls add suit coolers.  Alternatively, make it so robots can survive in space without roasting.  It's an easy one-var change.  They're probably second-easiest to kill atm, with nucleations being the first, as long as you can get burn-based weaponry.

**Comment by InvidiaSH** [comment]
Fixed in commit c16662e6c4e70a53772a2d3696946b005b0ba5ce
