### ISSUE TITLE
Grenade fix

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#1328]
ApolloStation/code/game/objects/items/weapons/grenades/grenade.dm

Line 93.

The quotes break the switch.  Just remove all the quotes from the numbers and it'll work.

I'm not sold on this being a good idea though.

Also: please change default dettime to 30 so we don't have to fix it all our flashbangs every round.

**Comment by Andrew-Fall** [comment]
Pull Request #1329 Grenade Fix/Changes
