### ISSUE TITLE
Engineer Pod Bay APC

### ISSUE THREAD

**Issue by Rattlederp** [Apollo-Community/ApolloStation#133]
The APC in the engineer shuttle bay doesn't charge nor discharge, stays at 90% the whole round. Tried messing with some of the wires around it with Kwask, still didn't charge. Disassembled it completely and couldn't place a new one anywhere in the engineering pod bay. All the equipment seems to be functional even without an APC in the room.

**Comment by Awantje** [comment]
pod also recalls to the wrong place

**Comment by Kwask** [comment]
Fixed, the area it was in was declared as a no power zone
