### ISSUE TITLE
Fix/Remove Accounts Uplink Terminal

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#1331]
http://i.imgur.com/dZdJxzj.png

Reported months and months ago but it was never issued.  With antags running on account cash, anyone with access to the terminal can instantly sniff out who the antags are: anyone with 10k+ cash.

Suggest removing or throwing in meme code so that antags always have a static real-looking cash value.

**Comment by InvidiaSH** [comment]
Don't know an easy way to cheekily resolve this one, sadly. Definitely an issue though.

**Comment by InvidiaSH** [comment]
For any of the people working on this later:

code\modules\economy\Accounts_DB.dm  --  The account uplink machinery.
code\modules\economy\Accounts -- Where accounts are made.
code\modules\antagonist\antagonists\traitor.dm -- Line 18 till 23 -- Where the traitor accounts are made.
code\modules\antagonist\contract.dm -- Line 106 -- Contract money reward application.

**Comment by dontdothis** [comment]
I think nixing the machine is a good temporary solution in the meantime-- it's not really used for anything besides antagsniffing or antags cheesing the machine for an ungodly amount of cash so they can buy a million items.

Also, economy code is an ungodly mess and I don't have speedy solutions to suggest either.  RIP.

**Comment by InvidiaSH** [comment]
Fixed in bc49fcfd9d784a9d37c08457ada32e8bceee5f92
