### ISSUE TITLE
No sprite for tipped glass table.

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#136]
No sprite for tipped glass table.

**Comment by nullbear** [comment]
but my invisible walls! no yeah, this is an issue.

**Comment by Kwask** [comment]
hm, I thought that glass tables shattered when they were flipped

**Comment by JMMJ01** [comment]
Yep, they shatter on flipping. I've been chased by sec for stealing them
when I flipped them as a racist assistant

**Comment by nullbear** [comment]
they dont leave shards, and you can "put table back", though?

**Comment by JMMJ01** [comment]
That's a recent change, then. I'd sprite, but I'm occupied with a different
project.

**Comment by Kwask** [comment]
Glass tables now shatter as of 75a8ff1a30c1e5553c9a5785651417f052a5cb5e

**Comment by nullbear** [comment]
Well now all tables shatter... GOD DAMNIT!

**Comment by Kwask** [comment]
totally intentional feature
