### ISSUE TITLE
Autopsy's don't show carp attacks when performed

### ISSUE THREAD

**Issue by Dilqui** [Apollo-Community/ApolloStation#1371]
Simple. I performed an autopsy on a dead person, and it gave me only the time of death. Later, I viewed the vars on that character, and it turned out that they had been attacked by carp, which did not show up on the autopsy scanner. Considering that death by carps are becoming more common, this might be a useful thing to have.

**Comment by InvidiaSH** [comment]
Fixed in commit 2711af52f3859348fbe8f887c0acf01f9a4a4fee
