### ISSUE TITLE
Typing error into AI welcome sentence 

### ISSUE THREAD

**Issue by FoinGRC** [Apollo-Community/ApolloStation#1385]
when spawn as AI :
A small error in the welcome sentence : in the shortcut list for the different channels ": p - AI Private" But it is ": b"

![aisentence](https://cloud.githubusercontent.com/assets/20094902/22446139/50036c84-e74b-11e6-9d1d-36c2f63c9e0c.png)

**Comment by Andrew-Fall** [comment]
Don't think so, :b is binary which only robots can understand. AI Private, or :p is typically in galactic common and could be overheard and understood by non-robots if they were tuned to the frequency.

**Comment by InvidiaSH** [comment]
Also doesnt follow the template. Issue closed.
