### ISSUE TITLE
Xenoflora light change only occurs if the plant is not glowing.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#139]
code is something like:

if glows
   stop glowing
otherwise
  start glowing // say "It glows now!"
      have a chance to change glow color. "the color suddenly changed" (from what? It only just started glowing now.)

I think this can be optimized by giving it a chance to change color if its already glowing. Otherwise "changing color" doesnt have any meaning. something like:

if glows
  have a chance to change glow color
  otherwise stop glowing
else
 start glowing

**Comment by lmas** [comment]
Going to need better info, like exact file or something.

**Comment by nullbear** [comment]
i think its seed_datums.dm or something similar.

**Comment by lmas** [comment]
https://github.com/stuicey/ApolloStation/blob/master/code/modules/hydroponics/seed_datums.dm#L366 ? It seems it already do what you suggested.

**Comment by nullbear** [comment]
If its glowing, it stops glowing, otherwise it starts glowing. Lets say it mutates three times:

The plant glows.

The plant dims

The plant glows
The plant starts to glow green

So you can only cause the plants color to change, if the plant isnt already glowing. That makes for a really damned rare chance to modify the color a plant is glowing, which kind of sucks. I think that it should have a decent chance to change color if it's already glowing, and a lesser chance to change whether it's glowing or not.

As well, if the negative lighting is a thing for apollo, probably add the possibility for the glow to be either negative or positive in the lighting mutation...

Theoretically, with a 100 potency, negative lighting vine, you could erm... make a vine that's impossible to remove unless you're carrying a ton of flashlights.

**Comment by lmas** [comment]
Dude, you gotta show me some actual code, takes ages to parse your text :p But I know what you mean. I'll see if I can do a little magic on it.

And no, we haven't got any negative lightning. Last commit from bay12 was a couple of months ago.

**Comment by lmas** [comment]
Close enough? It screws up the mutation ratios for the rest of the table though and if the plant isn't glowing already it will be a wasted mutation.
