### ISSUE TITLE
A Few air alams not working

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#14]
There seems to be a bug with a few air alarm panels across the station I found them when the station was quite busy so thought it was lag related, but this morning I checked with no one on the station and they were still bugged. 

The panels look like they work but when you try to change a number of settings they don't respond.
Setting that don't work include: vents Scrubbing toxins on/off, emergency siphon, normal siphon, changing air alarm modes (Filter, replace, siphon etc) and possibly other settings.

Yesterday I noticed the problem and went around the station today looking at a lot of air pannels to see which ones wern't working. A lot do and some areas just have one pannel that doesn't work, but here's a short list of my findings, check google doc for pictures of them that may help track them down:

2 in the arrivals lounge area.
both panels in arrivals corridor
3 in central hallway (north, northwest and south)
2 in hallway between medbay/bar/hydroponics.
1 in atmos office itself (which was funny).
There may be more but I don't have access to search the whole station as an atmos tech.

I also noted that 2 areas do not have air panels in at all:
Bar (the main public area)
Laundry room (near arrivals)

Here's the link to the google Doc:
https://docs.google.com/document/d/12E158aBXjiNpt3ep00uHRNQnvvuoW4huEVskglN47gk/edit?usp=sharing

My guess at the potential cause is that the panels are placed outside of a zone or maybe in 2 zones overlapping or something.

**Comment by GutsySS13** [comment]
Possible issue with their frequency settings?
I've looked at two that arn't working and their frequency seems to be 1441 whereas the one in the same cordoor that do work are on 1439.

Working one: https://drive.google.com/file/d/0Bw3ZV7xxvq78SzY5dXlPbmpwdTg/view?usp=sharing
Non working one: https://drive.google.com/file/d/0Bw3ZV7xxvq78dlAyRGM1c3dtb1U/view?usp=sharing

**Comment by stuicey** [comment]
should be fixed
