### ISSUE TITLE
Non-Euclidian Space?

### ISSUE THREAD

**Issue by hexagoncode** [Apollo-Community/ApolloStation#140]
Is it a designed feature to make space difficult to traverse?
I exited escape's airlock, traveled east until my momentum stopped, which seems to indicate that you've been switched off that level and onto another.
I threw an object east so I moved west and traveled two more sectors without encountering the station again.

So... once you're out of sight of the station, are you basically screwed forever?

**Comment by Kwask** [comment]
when you traverse to a new sector, it sets you to a random coordinate along the edge that you arrive at. It might be that you got placed at one of the extreme ends of the edge, and just flew past the station

**Comment by hexagoncode** [comment]
So how do you navigate space if after an arbitrary distance X or Y (distance to the border), you are shifted in a random X or Y (respectively) direction? That discontinuity is probably why I got lost as hell in the engineering shuttle the day of the update.

If it's not a "bug" per se, I'd still call it highly undesirable behavior.

**Comment by Kwask** [comment]
If you could look at the overmap, you'd still be traveling in a straight line across sectors, but your local movement would be something more like a zigzag. I left it in there because I figured it would emulate objects shifting in position due to orbits

Wouldn't be too hard to remove though

**Comment by hexagoncode** [comment]
I get the idea of orbits and the like, but when I leave the station we have identical orbital velocities. Locally, we're stationary or nearly so to each other. The further I go away, the more that changes but on the scale of 50,000 KPH (approximate orbital velocity of Europa, and it would be significantly faster the closer you get to Jupiter), my jet pack isn't going to make much difference. Or fire extinguisher. Or thrown piece of metal sheeting. I figure that's why the pods are using bluespace portals (or bluespace drives before the portal implementation).

Honestly, as a player, I find it very frustrating to get lost in space and not be able to get back. I shouldn't be outside in the first place, sometimes, but it's pretty easy to detach from the station. Poor Ol Sparky... pre-update, it got lost at the aft starboard array, drifted until it hit the research station. Fell off looking for an entrance, and wound up at the telecom satellite. Teleporting to the bridge scared the crap out of a security officer there... good times.

**Comment by Kwask** [comment]
Fixed in f9613b751ac97edc761fa861e6a7b269587afcb9
