### ISSUE TITLE
Eletrical grille

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#143]
Place two electrical grilles infront of each other, touch one and bounce between them. Or something like that. Nullbear broke the whole server again doing it.

**Comment by lmas** [comment]
See http://pastebin.com/tBwSQX2V for an example of nullbears RP:
    Isaiah Smith was shocked by the the grille!
    Isaiah Smith was tossed by the an electric shock from the grille!
    Isaiah Smith was shocked by the the grille!
    Isaiah Smith was tossed by the an electric shock from the grille!
    Isaiah Smith was shocked by the the grille!
    Isaiah Smith was tossed by the an electric shock from the grille!

**Comment by Kwask** [comment]
it's like electrical ping pong!

**Comment by Kwask** [comment]
Fixed in ae9e187bbc7fe7bf09de1f2544db1eaa6c636f4e
