### ISSUE TITLE
Messaging Console can't spoof names

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#146]
The messaging console can be used to send PDA messages using names, but the only valid name and job for it are the default ones, Administrator and Admin. Using any other name doesn't prevent sending the message but it doesn't show a name or a job, and the message itself end up in place of the name,

**Comment by lmas** [comment]
I tried to send a PDA message to myself with custom name/job and it worked perfectly.

```
*beep, beep*
Message from Someone (Tester), "This is a test, please ignore." (Reply)
```

The message won't show up in the target's PDA though, only in the chat window.
