### ISSUE TITLE
Spacepod R&D terminal does not update with main R&D database correctly

### ISSUE THREAD

**Issue by GeckoDragon** [Apollo-Community/ApolloStation#148]
Attempting to automatically update the terminal returns no research improvements even if the robotics terminal does. Tech data can still be moved across the station by hand on technology disks.

**Comment by lmas** [comment]
I think there's a limited range for the database connection back to R&D. Fairly sure I've seen some code about that in the R&D consoles. Which is kinda stupid and pointless I think.

Edit: Yep, [found it](https://github.com/stuicey/ApolloStation/blob/master/code/game/vehicles/spacepods/pod_fabricator.dm#L291). Stupid thing has limited range, just like [mech fab](https://github.com/stuicey/ApolloStation/blob/master/code/game/mecha/mech_fabricator.dm#L505). Maybe time for refactoring.

**Comment by Kwask** [comment]
Changed it from checking area to it checking orange(10), all is quiet on the robotics front
