### ISSUE TITLE
Spacepod armor broken

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#151]
Producing the command spacepod armor yields a spriteless part named "mecha part". Instead of acting like an armor installation, it gives the message "You insert the mecha part into the space pod." Doesn't seem to do anything.

**Comment by lmas** [comment]
Kwask probably forgot to add in that part and so it spits out a default part object.

**Comment by Kwask** [comment]
Did you produce the part on a mech fabricator or spacepod fabricator?

**Comment by lmas** [comment]
If I remember correctly I tried it in the spacepod fabber and got the junk.

Edit: Tried it again `the spacepod fabricator beeps, "The following has been completed: Pod Armor (command) is built".` It spent the materials but it didn't produce anything now.

**Comment by halworsen** [comment]
It was produced in the spacepod fabber in the Podbay.
