### ISSUE TITLE
Randomly get antennae on char. creation screen

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#155]
Reported by Draco.
Sometimes a char will get horns in the char. creation screen. Only way to get rid of it is to randomize the char. appereance.

**Comment by Kwask** [comment]
perhaps the person should stop being so villainous :smiling_imp:

**Comment by lmas** [comment]
The horns are infact wryn antennae. New human players gets them. One way to get rid of them is to randomize the character.

**Comment by GutsySS13** [comment]
maybe bunny ears too, someone said the on thursday.. funny ears week ?

**Comment by lmas** [comment]
The link to change hairstyle disappears too. Happends for new character loadouts.

Edit:
~~[Line in question](https://github.com/stuicey/ApolloStation/blob/master/code/modules/mob/new_player/sprite_accessories.dm#L51). It wrongfully causes new loadouts to use the custom human_face.dmi (where the first sprite is the wryn antennae) instead of the normal one.~~ Nope, something still forces the use of the antennae.

**Comment by lmas** [comment]
The problem was that `load_character()` didn't set a default hairstyle (which normaly is "Bald") and would just load the first hairstyle sprite from the icon file.
