### ISSUE TITLE
Chemistry package (mail) sorting pipe Still not working

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#16]
The pipes you swapped both need to not be inverted pipes. the direction of flow is the other way, the sorting pipe still sadly isn't on the main sorting loop which is in the east maintenance tunnel traveling south, but I still can't get it working... ongoing testing.

See this google doc for a more detailed description and pictures, I'm working on a comit but it's just a bit of map editing so feel free to do it yourself.

https://docs.google.com/document/d/1AaSmDNUpAPRGiNhC99MnLphDE09xgJFI8gdAlH30FU8/edit?usp=sharing

Changes are:
Pipe replaced with non-mirrored at 139,114,1 (it was facing down instead of up).

Sorting disposal pipe at: 157,114,1 moved to 163,120,1 and  changed icon state to "pipe-j1s" and dir to 2. Apologies i said move it here but this was outbound waste only and it is inverted so needs to be normal pipe even before being moved. I'm not sure if changing the icon state to j1s will work as it still doesn't sort, I'm still looking for reason why but this should be the right place for it.

linked disposal unit at 154,120,1 to south to outbound only pipe at 154,114,1. 

Linked Chemistry disposal in/outbound chute to disposal main route at 163,120,1

**Comment by GutsySS13** [comment]
I found the reason. I hadn't deleted the pipe under the sorting pipe. It now workd and you can send and receive from the disposal chute in Chemistry.

**Comment by Kwask** [comment]
Works once again in 87c4358909b6159ba19eae61ccc5c8a766518b89

Sorry about goofing it up earlier :panda_face:
