### ISSUE TITLE
Syndicate Uplink Soap

### ISSUE THREAD

**Issue by SilentNight195** [Apollo-Community/ApolloStation#160]
Ordering soap will cost you 2 TC and will not give you the soap, but it will give you the spybug kit.

**Comment by Ccomp5950** [comment]
https://github.com/stuicey/ApolloStation/blob/master/code/game/gamemodes/game_mode.dm#L47
And 
https://github.com/stuicey/ApolloStation/blob/master/code/game/gamemodes/game_mode.dm#L63

have the same "reference" of SP (the two letter code).

Change the spykit to SK and it will resolve it.

**Comment by Kwask** [comment]
heh, whoops

**Comment by Kwask** [comment]
there, fixed in 1202aa084c0eee82125774ea6223fdbb88622529
