### ISSUE TITLE
Jukebox music keeps playing when leaving the area

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#161]
~~A little bird told me someone sneaked in this new feature?~~

Bugs:
- [x] Fix music resetting when moving around in the room area.
- [x] Stop playing music when leaving the area

Suggestions:
- [x] Distance based sound levels of the music, instead of area based.

**Comment by Kwask** [comment]
heh, was wondering how long it would take before someone reported this little (mostly) harmless bug

**Comment by lmas** [comment]
I see what you did there!

**Comment by lmas** [comment]
Fixed in 72cdf924b38a9c9a4afbfd652a5f7bb859dab69c
