### ISSUE TITLE
Remind admins to toggle objectives as completed before round end.

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#164]
Example:

```
when escape shuttle arrives:
    check for custom objectives set by an admin
    send admin msg to remind them of setting the objectives as completed
```

**Comment by ghost** [comment]
Going to try to implement this.

**Comment by lmas** [comment]
Take a look at [objective.dm](https://github.com/stuicey/ApolloStation/blob/master/code/game/gamemodes/objective.dm) for some hints.

I think "Free objective" always needs to be toggled manually, so you can start checking for that. Then you need to find a way to get custom objectives made by admins.
