### ISSUE TITLE
Remove unused junk from repo

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#169]
My fingers are really itchy, wanting to remove most of the junk from the repo that we never use.
- SQL/tgstation_schema.sql
- bot/
- html/
- lib/
- scripts/
- tools/
- ~~.travis.yml~~
- libmysql.dll

Any objections if I remove this crap?

I don't know if there's any stuff in there that we use ourselves, but most of it looks old and with no updates for long periods of time. One quick thing I noticed was some mapmerge tool that's setup in git to run automagically, no idea if that's something we need (commits with map changes looks horrible anyway).

**Comment by Kwask** [comment]
We use SQL extensively on the server for saving bans and pretty much any other data that needa to be carried beyond the round

**Comment by lmas** [comment]
Alright, so do we only need `SQL/feedback_schema.sql` then?

**Comment by Kwask** [comment]
Yeah, the systems that the tables in the TG scheme file are for are deprecated

**Comment by lmas** [comment]
I suspected that. No point in keeping that junk. I love shaving off old, ugly stuff.

**Comment by Kwask** [comment]
Also, the .travis.yml file would be needed if Stuicey ever sets up Travis builds (glares at Stuicey)

**Comment by lmas** [comment]
OFFTOPIC: I think if we had a github org. someone else could set up travis for the repo as long as one have the required access. Right now it's a repo under Stu's account so only he can do such things to the repo.

**Comment by GutsySS13** [comment]
erm libmysql is used by php other programs as a sort of external plugin link to mysql. in other words. get ready to put it back in... you may be using localhost to talk to mysql but this may be what the game is using to communicate to it creating a dummy socket or something.... of course if you are running on a linux or mac or something be my guest. most compilers will point to this file if they want to use it's external libraries. unix and mac will be looking for a .so file and most mysql distributions come with these files so you may have one somewhere else anyway.

**Comment by lmas** [comment]
Hence why I asked in the first place :D

IMO, we're running our server on a linux host, doing dev. work on windows desktops without a sql database. I see no point in keeping libmysql.dll, as I don't care much for others who might host the game on windows. Plus it haven't changed for over 5 years so it's greatly out of date and insecure too. 

We could always add a note somewhere that it might be required and point in the general direction at where one can get a more up-to-date version of that file.

Edit: even the README is out-of-date in the `SQL Setup` section.

**Comment by GutsySS13** [comment]
to me it does look like it would be something that's safe to be deleted. it sounds like it's pretty old

**Comment by lmas** [comment]
If there's noone else that want to speak up now I'll go ahead and start removing stuff tonight.

**Comment by lmas** [comment]
Eh, 15 days later and I removed the stuff in 9b866b80dd49965c14ac3a745d764e92a17366cf and c9e03944a3cd8d80b70ad907350418ca89a911d5. Gonna let it sit for a while and see if there's any problems.

**Comment by lmas** [comment]
Done with it for now, it's stable.
