### ISSUE TITLE
Break off from Baystation

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#170]
I've put a lot of time and work on trying to merge the changes from latest bay12 master branch, but without any good results. 
The code is really messy and buggy, duplicate stuff everywhere when we and bay added the same new features etc. etc. ad nauseam.
I haven't heard anyone else being interested in the latest bay12 changes either, besides myself, and it's really annoying and hard work to merge map changes and stuff like that.

My suggestion is; we might aswell break off completely from baystation's repo and clean up our own. Not just be a fork, but our own shiny repo (so we finally, for example, can do code search in this repo via github :D ) with our own free github organization.

How does that sound? Yay or nay?

**Comment by Kwask** [comment]
Aye, I'm all for this. Merging at this point, with all we've added, gets really messy really quickly.

I'd suggest thar we just cherry pick any features that look particularly appealing

**Comment by nullbear** [comment]
Cherry picking is nice.

**Comment by lmas** [comment]
Imma go ahead and remove my bay branch.
