### ISSUE TITLE
Server can't make sub dirs for logs.

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#178]
... If the sub dirs doesn't exist already.

This is a problem with the file() func. A possible fix is to replace all file() calls with text2file() instead, as it will created the sub dirs first.

Per Stuicey's notes.

**Comment by stuicey** [comment]
I would just take it as a precaution that file() proc doesn't create sub directories rather than replace all instances.

**Comment by lmas** [comment]
What creates the `data/logs` dir in the first place then? The files are created in `world.new()` but I can't find any references to how the dir is setup. It's not in the repo and my grep'ing fails.

 I wanted to make sure the server creates the dirs so we don't have that problem again with missing logs. Could simply add that to the `world.new()` before it opens the logs. Can't find any byond stuff to make empty dirs though.. 

I might aswell add some empty dirs to the repo instead.

Edit:
Or change

```
log = file("data/logs/runtime/[time2text(world.realtime,"YYYY-MM-DD-(hh-mm-ss)")]-runtime.log")
```

into

```
log = file("data/logs/[date_string]-runtime.log")
```

so we store it in the same dir. But that would break the admin verb `getruntimelog()` since it's browsing the `data/logs/runtime/`. Unsure if anything else would break.

**Comment by lmas** [comment]
IMO, you should be able to download this repo, compile the source and copy over the example configs (with sane defaults), in order to start a fully functional server with complete logs.

**Comment by stuicey** [comment]
Going to close this due to inactivity, also the fact that not having these sub directories is very useful for local bug testing - since runtimes don't get redirected to log files.
