### ISSUE TITLE
Can't make random numbers in Telecoms script

### ISSUE THREAD

**Issue by isitfun4** [Apollo-Community/ApolloStation#179]
if you try to use 
$RandomNumber = rand(2,5);

$RandomNumber will be set to null

**Comment by Rusty-Gravy** [comment]
Have you tried mt_rand(2, 5); ?

**Comment by ghost** [comment]
This is not a bug but a feature request or oversight thingy. rand() and mt_rand() are not part of NT script. (source: http://wiki.baystation12.net/NT_Script)
