### ISSUE TITLE
Long server startup time

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#183]
The server takes an exorbitant amount of time getting itself back on its feet after it restarts. A few of the startup and initilization procs should be looked at for optimization

**Comment by lmas** [comment]
Did a [simple benchmark on my desktop](https://docs.google.com/spreadsheets/d/133LbtkUuP0yDICnEy8F_C6_btCWAe2fWhhGFT4uTLgU/edit?usp=sharing). Note that it's average CPU times and that it was both a startup/login and then a restart.

So, possible places to optimize the code is:

```
Proc Name                                               S.CPU   T.CPU   R.Time  Calls
/datum/controller/lighting/proc/initializeLighting      0.54    10.205  10.205  2
/datum/controller/game_controller/proc/setup            0.002   8.545   8.573   2
/datum/controller/game_controller/proc/setup_objects    0.068   2.925   2.953   2
/datum/controller/game_controller/proc/SetupXenoarch    0.168   0.422   0.422   2
/datum/ore_distribution/proc/populate_distribution_map      0   0.103   0.103   2
/datum/ore_distribution/proc/apply_to_asteroid          0.071   0.071   0.071   2
/obj/machinery/cryopod/proc/find_control_computer       0.039   0.039   0.039   16
/obj/machinery/cryopod/initialize                           0   0.039   0.039   16
/obj/effect/landmark/corpse/proc/createCorpse           0.001   0.032   0.032   10
```

Everything looks pretty good already so no idea where to start...

Edit: just for fun I postponed initializeLighting() by chucking it inside a spawn(120). It makes it quicker to join the server but then there will be that lag spike when the proc is finally being run.

**Comment by Kwask** [comment]
We could stagger that proc so it spreads out the processing over the length of the first minute of lobby time.

**Comment by nullbear** [comment]
I tried something similar with the explosion and delamination procs to see if it made the game feel less laggy. It didnt.

**Comment by lmas** [comment]
How would you stagger that proc, kwask?

Also, the explosion stuff is too math heavy and CPU intensive for poor byond and it's single CPU usage. Good luck trying to optimize that without proper multiprocessing.

**Comment by Kwask** [comment]
You would probably have a set constant time total, like 600 deciseconds, then divide that time between each item that has to be processed. In this case, every turf that has to be initialized. 

Since sleep() in BYOND can't go lower than 1 decisecond, you would need to group together turfs in batches, the total number of which would be the same as the total number of deciseconds that it would take to process the entire thing. So if you allocated 600 deciseconds, you would have 600 batches which would be individually processed in 0.1 second periods of time.

**Comment by lmas** [comment]
Now that you disabled a lot of maps the server starts up quite fast.
