### ISSUE TITLE
Paper bugs

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#186]
I mean, i guess i should have maybe tested the code before i made a pr, but:
- [ ] Fax machine construction is bugged as a result of being a child of photocopiers
- [x] Hand labellers dont use labels. Not my fault.
- [x] Filing cabinets need variety like comfy chairs or whatever
- [x] Antilogo doesnt work. I mean, i dunno why, but i'll figure it out.
- [x] Paper bins are not constructible, and do not drop papers that have not been added. That's no fun.

**Comment by Kwask** [comment]
tsk tsk

**Comment by GutsySS13** [comment]
how do you make paper any hoo? chemist !!!!

**Comment by nullbear** [comment]
I think photocopiers have unlimited paper, and you can order paper via bureaucracy crate?
