### ISSUE TITLE
Ingame issues with the new monkey code

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#190]
- [ ] Clothes disappears when scooped up, but shows up when moving around freely again.
- [x] Human screams when hurt. Needs monkey sounds instead.
- [x] ~~Keeps gasping when dead.~~ ~~Won't die completely, stuck at -72 health of 75 or something like that.~~ This happends for all mobs that's been attacked by slimes.

**Comment by GutsySS13** [comment]
Monkeys grunt and scream when suffocating in xenobiology.

**Comment by stuicey** [comment]
perfect

**Comment by nullbear** [comment]
needs feature tag.

**Comment by DreadedReborn** [comment]
Quite obviously a feature.
~~How else will sadists like the xenobiology job if they can't hear human screams?~~

**Comment by Kwask** [comment]
We must accommodate everyone

**Comment by DreadedReborn** [comment]
:hear_no_evil::gun::see_no_evil: :speak_no_evil:
Indeed.

**Comment by lmas** [comment]
See #205 for monkey cubes.

**Comment by ghost** [comment]
@lmas cea6e90e09e82a62470fa40aaf2e14495cbe0d98 fixed the human screams.

**Comment by lmas** [comment]
It's been tested properly and stuff? If so, neat! 
Gonna have to join you guys on saturday night and continue my monkey experimentations..

**Comment by ghost** [comment]
Wait, I don't know if it fixed your other issues.

**Comment by lmas** [comment]
Ops, I forgot those.
