### ISSUE TITLE
Spybug kit withouth the actual spybug.

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#192]
- [x] Only a helmet in it. Isn't it supposed to have at least one bug in the box?
- [ ] Selfdestructing the bug makes a really big mess for such a tiny thing.
- [x] VR helmet has no sprite when it's being weared.

**Comment by Kwask** [comment]
Some reason the mob holder de spawns as soon as it is created. A similar thing happened when I tried making it so you could put bunnies in tophats

As for the helmet sprite, whoever moved all of those custom sprites around touched it last. We lost the curtain sprites for the same reason

**Comment by lmas** [comment]
I assume 60688b5fd6e4d3645b6e6efea47fdf3857a0174c fixed the no spubugs in kit?

**Comment by lmas** [comment]
That's an affirmative. Issue 2 I can live with.
