### ISSUE TITLE
The power blackout event is still showing up too often

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#194]
My attempts at nerfing it wasn't enough. Also noticed we rarely have meteors.

**Comment by Kwask** [comment]
I still haven't even seen a meteor hit the station once since the event was updated :unamused:

**Comment by lmas** [comment]
Weird. Let's see how it is when I merge in the TG meteors.

**Comment by Kwask** [comment]
suddenly every meteor becomes a clown :fearful:

**Comment by lmas** [comment]
Merged in e0192282dbe9d1fdae75dfae0f2f85aa566e6f51 and finally compiles in 50b560b0563876a25da5be9f7e665e8424416c8a.

But for some reason `locate(startx, starty, Z)` inside `/proc/spaceDebrisStartLoc()` always returns `(1,1,1)`, even thought if `startx, starty` is valid positions that's not 1,1,1. 

And `var/picked_station_level = pick(config.station_levels)` is always picking `3`, so no hits on the basement.

**Comment by GutsySS13** [comment]
last night it was spiders, spiders and more spiders. is it just a case that maybe once an event takes hold it keeps happening? We didn't have a power outage.

**Comment by lmas** [comment]
Might just be the RNG gods screwing with you.

**Comment by lmas** [comment]
Hmm, not sure if the coordinate bug is real or not.Tried this on a local server just now and it would hit the station from all kinds of angles and directions. Not sure if it's a bug with `testing()` or `locate()`. 

Either way, it works, doesn't throw any errors of any kind and have spectacular results :D

Edit: Merged it in, this better be good. Also tried nerfing the blackout event again.

**Comment by lmas** [comment]
Closing this for now.
