### ISSUE TITLE
SpacePod AFK 

### ISSUE THREAD

**Issue by stuicey** [Apollo-Community/ApolloStation#195]
If you go AFK inside a space pod and fall to the floor you drop all items making them un-recoverable. However if you drop a tracking beacon using this message and try teleport to it afterwards you will be teleported to loc (0,0,0) which is an out of game area.

**Comment by Kwask** [comment]
spacepods are the key to nullspace!

**Comment by lmas** [comment]
Also, if you aghost when inside a pod and then try to reenter body you won't get back your spacepod tab and can't exit the pod.

**Comment by GutsySS13** [comment]
jump to the passenger seat and back again. hopefully you didn't bring a passenger along :P Also this fixes your UI so you can see your fuel and cell power again.
