### ISSUE TITLE
Mindbreaker toxin from a lucky sevens cig never stops

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#196]
Happened to kingnexus, smoked one, got that new cool hallunication. Then his body processed the toxin but he kept blacking out and falling on the ground. I think his hallunication level got stuck in an infinite loop.

**Comment by ghost** [comment]
Was he still smoking one?

**Comment by lmas** [comment]
Nope, smoked only one cig until it burnt out. I verified his body had purged the toxin (in his vars) but he still kept getting hallucinations.

**Comment by Kwask** [comment]
Hallucinations stay in the body for a while after LSD is metabolized, am gonna close this up until we verify it really was never going away

**Comment by lmas** [comment]
Sounds like a bug to me :D 
I think it should be nerfed and have the hallucinations go away when the drug does, it's no fun for the players (especially since they can't do something about it when the drug is already purged).
