### ISSUE TITLE
Critter hide verb + Stairs

### ISSUE THREAD

**Issue by Rusty-Gravy** [Apollo-Community/ApolloStation#202]
![stairs critter hide](https://cloud.githubusercontent.com/assets/9167646/8144155/74ce30be-11c6-11e5-95e3-47e7b4d82550.gif)

I noticed that if you're a small critter, in this case a Dionaea Nymph but possibly others too, you are able to hide underneath the bottom set of stairs.

**Comment by Kwask** [comment]
little harry potter under the staircase

**Comment by Rusty-Gravy** [comment]
![tumblr_mjxs7zmnyk1qew2ypo6_r1_250](https://cloud.githubusercontent.com/assets/9167646/8146194/15ebdcb4-1224-11e5-958e-1466f38db5a2.gif)

I just spent the past 30 minutes doing this in GIMP because I have no idea how to make gifs any other way :'(

**Comment by Kwask** [comment]
oh my god, that is so goddamn good :laughing:

**Comment by lmas** [comment]
That gif is so damn true, made me laugh out big time! You better post it to the subreddit (if you haven't already).

I think I agree with gutsy, it's kinda a nifty feature. What happends when you try to move further "down the stair", when under it? Will you actually go down?
Maybe we should add some transparant parts to the stairs so you can see what's under it.

Dat insane logic though (hidding under the stairs, that goes downwards).

**Comment by Rusty-Gravy** [comment]
You can go up the stairs while hiding under the first tile, it looks weird haha
The top set of stairs aren't possible to hide under.

Also yeah I'll post that to the subreddit I suppose, what is it? /r/ss13?

**Comment by lmas** [comment]
Nice. I assume you will keep hiding under the stairs when you go through it. Can't decide if it's a bug or feature.

And yes, that's the subreddit. Take wisdom from Stuicey and Kwask, always post your awesome work on reddit. :p

**Comment by Kwask** [comment]
gotta get them meme points

**Comment by Rusty-Gravy** [comment]
upboat my toats

http://www.reddit.com/r/SS13/comments/3armbs/shitcurity_dionaea_nymphs/

**Comment by lmas** [comment]
Yeah boy!

**Comment by lmas** [comment]
Soo, back to the topic: Disable critters from hiding under stairs?

**Comment by Kwask** [comment]
Yeah, since there's nothing there to hide under, nothing should be able to hide under it

**Comment by lmas** [comment]
Sounds like an easy enough movement check to add for any and all critters.

**Comment by nullbear** [comment]
fixed in https://github.com/Apollo-Community/ApolloStation/pull/458
