### ISSUE TITLE
AI bugs

### ISSUE THREAD

**Issue by DreadedReborn** [Apollo-Community/ApolloStation#206]
- [ ] Check for more things related to AI and this bug.
- [ ] Fix medical equipment.
- [x] Fix the fact turrets shoot the back of the AI's upload when someone enters.

What I mean is, the AI is capable of entering Sleepers and Body Scanners, and be basically stuck there. All I've seen so far is the medical equipment, however. Might need more testing.
The turrets continue to quite literally shoot the AI in the back, however.
Also, side note. I haven't seen any issues put up about this before, so I am assuming this is the first one about this.

**Comment by Rusty-Gravy** [comment]
A picture I took of the incident:

![sleeper](https://cloud.githubusercontent.com/assets/9167646/8172336/88892a30-13b7-11e5-94e5-fd919116f867.png)

**Comment by nullbear** [comment]
oh hi there.

**Comment by Kwask** [comment]
the AI's "remote access" is actually just a big robotic arm that carries the AI between the consoles on the station :>

**Comment by DreadedReborn** [comment]
And that's the problem. The poor thing can accidentally climb into things.

**Comment by Rusty-Gravy** [comment]
Tested it on a lot of things, appears to only be the body scanner.

**Comment by Kwask** [comment]
I think it's a oversight from when we added in the click-to-enter on the sleeper and scanner pods

**Comment by DreadedReborn** [comment]
Nice pun there, Kwask. Oversight.
Like what an AI has?
I tried.

**Comment by Kwask** [comment]
:rage:

**Comment by lmas** [comment]
I think it's an oversight somewhere else, when I added in the click-to-enter I used the regular enter-sleeper/scanner/cryo/borgcryo verb.

Edit: Yep, see good ol' #50. Also, sometimes you're the worst dreaded.

Edit2: Hmm, I wonder why the AI can go inside when there's a check for [nonhuman/small things in the move_inside verb](https://github.com/stuicey/ApolloStation/blob/master/code/game/machinery/Sleeper.dm#L421).
