### ISSUE TITLE
Prison Cell 1 missing cell timer console

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#207]
Prison Cell 1 missing cell timer console.

I thought this had already been reported, but can't seem to find it so I am logging it again as it's not been fixed.

**Comment by lmas** [comment]
Could had sworn I reported that, that cell's been missing a console for a long time now.

**Comment by DreadedReborn** [comment]
God damnit Kwask. Fix it. :anger:

**Comment by Kwask** [comment]
priority: mega-low

**Comment by lmas** [comment]
Don't know why, but I can't even select and, for example, remove the other prison cell consoles in the mapeditor.

**Comment by stuicey** [comment]
They probably have some crazy pixel offset

**Comment by lmas** [comment]
Ugh, I keep forgetting about that stupid way of adding things to walls.
