### ISSUE TITLE
Construction of a hull shield leaves behind a "machine" which can be screwdrivered for endless hull shields

### ISSUE THREAD

**Issue by GeckoDragon** [Apollo-Community/ApolloStation#209]
As the title says, i presume the bubbleshield acts the same way

**Comment by Kwask** [comment]
time to make a hull shield entirely out of hull shield machines

**Comment by GeckoDragon** [comment]
Considering they're "for free" you can probably make a building out of them and live in it

**Comment by nullbear** [comment]
there was a similar bug with a bunch of other machines. Notably telecomms

**Comment by nullbear** [comment]
reference this? Idk how https://github.com/stuicey/ApolloStation/issues/74

**Comment by lmas** [comment]
Hopefully it's just someone who forgot to add a line to remove that leftover machine or something.
~~What do you mean with "construction of a hull shield"? Do you grab one from engineering and unscrew it to break it appart or something?~~

~~Edit: There's no deconstruction proc for machines, only computers, in the circuitboard code. Might want to refactor machines to use some kind of global proc too.~~

Nvm, you build a new machine with the right circuitboard. Can't deconstruct this thing so it's a bug in the creation code. Getting a runtime error [on this line](https://github.com/stuicey/ApolloStation/blob/master/code/game/machinery/constructable_frame.dm#L119):

```
runtime error: Cannot execute null.Cut().
proc name: attackby (/obj/machinery/constructable_frame/machine_frame/attackby)
```

**Comment by lmas** [comment]
Meh, that code block I linked to is so damned broken and is in great need of a overhaul...

**Comment by lmas** [comment]
Fixed it for now.
