### ISSUE TITLE
IPC Issues

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#210]
- [x] IPCs can be changelings
- [x] IPCs can be cultists
- [x] IPCs don't have posibrains
- [x] IPCs don't have a clearly defined lore
- [ ] IPCs are instagibbed when hit by an EMP, not stunned like the wiki says they should be
- [x] IPCs can get hungry

**Comment by lmas** [comment]
Some of these could be easily fixed with some checks to avoid picking IPCs.

**Comment by Kwask** [comment]
- [x] IPCs can be turned into xeno babys

**Comment by halworsen** [comment]
The hungry part is probably kind of dumb. It'd be better to replace it with another icon. Nutrition is pretty much just treated as power for the IPCs.

IPCs can become chubby, though, which is weird.

**Comment by Kwask** [comment]
- [x] IPCs wont gain nutrition from draining APCs

**Comment by halworsen** [comment]
They do, though.

**Comment by Kwask** [comment]
Was told yesterday people still weren't getting nutrition from it

**Comment by halworsen** [comment]
I think that has more to do with their expectations for draining from APCs being a little high. I tested it today, it works fine.
