### ISSUE TITLE
Meteors aren't buff enough.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#214]
Triggered 50+ meteors on the station during lowpop (someone asked if i could do a custom derelict event or something) with minimal damage. About 40% of the time, the station makes it through the event without a single meteor hitting the station.

**Comment by stuicey** [comment]
It would be nice to see meteors classed into size groups that could be announced over station comms so crew know what to look out for.

**Comment by GutsySS13** [comment]
How about if we had a meteor that crashed through the station tearing a nice big hole as it went for 20 or so tiles, it  could then be taken down to mining and melted down into something. Maybe have it not smash though none repairable items like sleepers/super matter/re-inforced walls and maybe some other things that could go in a list to stop really nasty destruction.

++FUN

**Comment by Kwask** [comment]
Quite contrary. We had a meteor that ripped all the way from xenobiology out through the opposite side at the library, and this was WITH hull shields active. It's just an issue with the secrets version of meteors, the random event itself is very deadly.

**Comment by nullbear** [comment]
I don't have access to the random event panel, I was just mucking with the event manager.

**Comment by lmas** [comment]
Ooh.. I might have forgotten to mention there's a bunch of different meteors now, not just small and regular ones. 
What Kwask experienced was a Tunguska meteor. And yes, it will rip open the station spectaculary when it just goes through "soft hull stuff" :D It's a bit rare though... It all depends on the RNG.

And there's different announcement messages too: meteor shower is sent for just a bunch of rocks doing some light poking, meteor storm is sent when the fun stuff is on it's way in.
Unfortunately the only difference between the two is the amount of waves and how many meteors there's in each wave. Any kind of meteor can be randomly selected for a wave.

_cough_ there's some radiation meteors too.._cough_
