### ISSUE TITLE
Drones cant make pipes.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#219]
Nor can they pull the pipe dispenser. They're restricted to dragging pipes all the way across the station individually.

**Comment by lmas** [comment]
Besides production, can they interact with pipes normaly? Ie, flip/rotate, wrench/weld?

I'm also thinking it's too easy to mess around building pipe traps of various kinds, considering that anyone can ghost and then go drone. But then again the drones already have lot's of access to stuff that could be misused.

**Comment by GutsySS13** [comment]
I'm kinda glad they can't tbh. it should be the job of an engineer or crew, that's what they're there for. drones are there to just fix light bulbs and simple stuff not do major repairs imo...

**Comment by lmas** [comment]
Agreed.

**Comment by lmas** [comment]
Closing this for now due to inactivity. Feel free to reopen it.
