### ISSUE TITLE
Mob pathfinding doesn't account for windows/soils/possibly other structures

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#226]
Example: the farmbot in hydroponics. The windows and soils can block the farmbot's path when it's trying to reach some soil plot. ~~It will throw a~~:

```
runtime error: list index out of bounds
proc name: Life (/mob/living/bot/farmbot/Life)
  source file: farmbot.dm,130
  usr: null
  src: Farmbot (/mob/living/bot/farmbot)
```

~~which is easy to silence~~ fixed in 3c4f24e580ec76c2fcab2a553174fc15f9adf167, but there's still the pathing problem (which will stop the bot, but it will keep try to move).

[AStar.dm](https://github.com/stuicey/ApolloStation/blob/master/code/defines/procs/AStar.dm#L6) states that it will account for windows but that's either a lie or a bug.

**Comment by lmas** [comment]
Another thing to note is the secbots failing to chase after targets that's on the other side of for example a wall, though [chasing after targets using pathfinding isn't part of their programming](https://github.com/stuicey/ApolloStation/blob/master/code/modules/mob/living/bot/secbot.dm#L172)...

**Comment by Kwask** [comment]
Mob AI needs a rewrite in general. The only things mobs do is move() in the dir of their target. There's no pathfinding, no aggro'ing, no retreating or going berserk when health is low. It's just throw yourself in a direction until you hit something

**Comment by stuicey** [comment]
Going to close this - been inactive for a year and probably improved with 999bcdbba9f9417f45e6fb6b47f390fdd33f4cf6
