### ISSUE TITLE
Meteor explosion sounds does not play

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#228]
They would always play a distant explosion effect when they struck the station. There's [code to do it](https://github.com/stuicey/ApolloStation/blob/master/code/game/gamemodes/meteor/meteors.dm#L205) (explosion will play it), but it's not working right now.

The sound falloff range is too great I think.

(~~Also, I'm not hearing any sound effects when I run the game locally... makes it really hard for me to troubleshoot this~~ Nvm, you actually have to be a living mob once in the round for you to hear effects.)

**Comment by lmas** [comment]
Someone tell me if I overdid it again.

**Comment by lmas** [comment]
Nope, still not playing sounds when you're not completely near them I think.

**Comment by Kwask** [comment]
Might want to check explosion code, pretty sure those explosions are still heard across the station

**Comment by lmas** [comment]
Eh, seems it's just me having this issue or something. Closing.
