### ISSUE TITLE
Bugged sleeptoxin for new clones

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#230]
The toxin will never be consumed by the host body after it was clonned. I think. Antitoxins won't get rid of it either.

**Comment by Kwask** [comment]
Does this mean that clones of corpses that were injected with sleep toxin will never wake up?

**Comment by lmas** [comment]
Maybe, what I remember of it clones wouldn't ever wake up after poping out of the cloner/being put in a cryotube. Only way to make them wake up was with the help of an admin (to manually remove the toxin). They weren't injected by another player though, it was that standard sleeptoxin from the cloner/cryotube.

One have to do a simple test (make two clones, let one wake up after cloner and let the other one wake up after having been put in both the cloner and cryotube).

**Comment by nullbear** [comment]
I thought clones were injected with sleeptoxin in the machines as a cloning nerf. It's got nothing to do with the corpse.

A fast way to get around it was to do a dialisis in the sleepers right after cloning.

**Comment by lmas** [comment]
Correct, ~~but the sleeptoxin would never wear off, even with antitox. Could be a bug with the machines or the sleeptoxin itself. I'm going to test it again.~~

Edit: Eh, the sleeptox seems to wear off slowly and it can be speed up with antitox (the cloner injects 15 units of sleeptox, and a small dose of ~5u chloralhydrate). Patient will wake up after the sleeptox is gone so I'm going to close this for now.

Also I think you missread my first comment kwask, I meant the bodies of new clones not the old, dead body.
