### ISSUE TITLE
Xenomorphs hug spiders (Harm intent)

### ISSUE THREAD

**Issue by stuicey** [Apollo-Community/ApolloStation#236]
So when a xenomorph attacks a spider on harm intent they just poke them and do no damage.

**Comment by Kwask** [comment]
hey man, spiders are scary

**Comment by lmas** [comment]
Same thing with space carp. Poor xeno could only pet the carp gnashing at him.

**Comment by halworsen** [comment]
Wasn't a bug after all. Spiders & carp are simple animals, which have some nonsensical code. Damage done to them (and the attack message) is hardcoded, not based on who or what attacks 'em.

**Comment by lmas** [comment]
What, so xeno's doesn't hurt them then?

**Comment by halworsen** [comment]
They do. 3 damage per hit, as per defined for `/mob/living/simple_animal` in code\modules\mob\living\simple_animal\simple_animal.dm.
