### ISSUE TITLE
Catwalks can't be deconstructed

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#242]
Not good at all for when you want to expand areas and there's indestructible catwalks. They leak into space as well, which is extra bad if you want to pressurize.

**Comment by nullbear** [comment]
yeah i was gunna do something about it soon, but ive been busy

**Comment by Kwask** [comment]
Catwalks being porous is fine so long as we can fix them being indestructible.

Technically they're always destructible with bombs ;)

**Comment by nullbear** [comment]
xD i think para has catwalks you can construct by using rods+lattice, and can be removed with wrench/wirecutters.
