### ISSUE TITLE
Spacepods can be refueled with oxygen tanks

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#243]
![yep](http://i.imgur.com/7j4j6nR.png)

**Comment by Kwask** [comment]
I think the message might just say that, in reality it probably doesn't fill the tank at all. 

The code for it, if I recall correctly, just sucks up all the phoron gas in a tank, rather than all gasses in the tank.

**Comment by stuicey** [comment]
Just add a check for phoron in the tank-

if("phoron" in G)   // Gasses are stored as a list
