### ISSUE TITLE
null cartridge

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#244]
![null](http://i.imgur.com/F3rGoeI.png)

I don't know how it happens or when, but occasionally the cartridge in your PDA becomes "null".

Still works fine, though.

**Comment by Kwask** [comment]
What happens if you try to eject it?

**Comment by halworsen** [comment]
If I remember correctly, nothing special. Cartridge pops out, but its name is still null.

**Comment by lmas** [comment]
Haven't even heard of it in a long time, closing for now.
