### ISSUE TITLE
Entertainer's bugging it up.

### ISSUE THREAD

**Issue by DreadedReborn** [Apollo-Community/ApolloStation#245]
The entertainer's clothing has slipped up and is now displaying a red 'TSUIT' icon instead of the actual jumpsuit.

**Comment by lmas** [comment]
It's probably the damned sprites files again. Not sure but I think I changed the suit icons some unknown time ago in some update, and missed to update the file references in the code.

**Comment by DreadedReborn** [comment]
I had a poke about, and the only thing that seemed odd was this sprite sheet variable.
Set to a vox sprite sheet.

**Comment by lmas** [comment]
The [sprite_sheet variable](https://github.com/stuicey/ApolloStation/blob/master/code/modules/clothing/clothing.dm#L406) is globally set for all suits. Not sure if it's relevant.

Edit: Chloe's kimono, cyborg suit and evening gown are other clothes not working.

**Comment by Kwask** [comment]
Fixed in e9c3d3d76768f99308069ca453d26cf904a08489
