### ISSUE TITLE
Re-enable monkeysplosion when eating a monkey cube?

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#246]
Easy enough to revert d914a5e40eeb79fc634b224f575bf8e40931eb3b (also see #205), but it's going to be a pain to get that code working again with the new monkey code.

Yay or nay?

@Kwask and @nullbear is obviously voting yay :p

**Comment by Kwask** [comment]
yayayay

**Comment by nullbear** [comment]
yay

**Comment by ghost** [comment]
Nay. Although I do think it should hurt them a lot, I don't think it should crit-hit them.

**Comment by DreadedReborn** [comment]
I agree with HiddenKn on this one.

**Comment by lmas** [comment]
Doesn't seem to be enough popular interest on this one, closing for now.

**Comment by halworsen** [comment]
yes though
