### ISSUE TITLE
Add "get random job" button

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#247]
You can set all your job preferences to never and make sure you have that "get random job when all slots are full" setting toggled on, but that's a not very user friendly.

As requested by SwGustav.

**Comment by Kwask** [comment]
Would also be useful to add it to the latejoin menu

**Comment by lmas** [comment]
Yes, that was the main use case he mentioned.

**Comment by Awantje** [comment]
Perhaps add an option random no head. Because I hate to be a head some rounds. And ofc dont forget a check to see if someone is whitelisted.
