### ISSUE TITLE
Jukebox keeps playing music when unbolted from floor

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#248]
Play a track on the jukebox (so you hear the music), then drag it and unbolt it from the floor. Music keeps playing. I think it keeps playing for you when it's out of range too... Somewhat irritating.

Found by @HiddenKn

Edit: Yep, keeps playing even when you delete it. Also getting (another bug):

```
runtime error: Cannot read null.sound
proc name: process (/obj/machinery/media/jukebox/process)
  source file: jukebox.dm,246
  usr: null
  src: the record mixer (/obj/machinery/media/jukebox/mixer)
  call stack:
the record mixer (/obj/machinery/media/jukebox/mixer): process()
/datum/controller/game_control... (/datum/controller/game_controller): process machines process(5610, 6068)
/datum/controller/game_control... (/datum/controller/game_controller): process()
```

**Comment by ghost** [comment]
Aye. It's pretty funny. It also works for anyone in range when disconnecting/dragging it. But it should probably be fixed.

**Comment by Kwask** [comment]
Hmm, could probably fix it by telling it to kill the music when it's unbolted. That way, it updates the listening mobs and turns off the sound for them.

**Comment by ghost** [comment]
~~The sound IS killed when you unbolt it, but it starts again when you drag it.~~

**Comment by ghost** [comment]
I think the issue is with https://github.com/stuicey/ApolloStation/blob/master/code/game/machinery/jukebox.dm#L70
But I'm not super familiar with the |= and &= operators.

**Comment by GutsySS13** [comment]
I'm not so sure the sound is killed when you unbolt the jukebox from the floor, I think it restarts the audio so it has about 5 seconds of apparent quiet but then the song starts again so if you just leave it the sound starts again regardless. I unbolted it and then admin deleted the object and the song still started playing.

**Comment by ghost** [comment]
Hmm, you're right. So the actual bug is that the song starts playing again after you unbolt it. The dragging part doesn't really matter.

**Comment by lmas** [comment]
~~I think there might be a problem with the [StopPlaying()](https://github.com/stuicey/ApolloStation/blob/master/code/game/machinery/jukebox.dm#L214) proc.
The way it's coded, it assumes a bunch of things that might be true or false.~~

~~First, it will only stop playing music for living characters (no ghosts). Secondly, it will only stop playing music for mobs within range.~~
Eh nvm, the more I look at the code the more unsure I am. 

The way gutsy describes it, it sounds more like a problem in the [process()](https://github.com/stuicey/ApolloStation/blob/master/code/game/machinery/jukebox.dm#L234) proc and the confusing use of the `playing` variable.

**Comment by lmas** [comment]
No matter what, the jukebox won't stop playing again. It's secure to the floor and all.

**Comment by stuicey** [comment]
Can you give details on how to reproduce? The jukebox has a catch all when it is turned off which should turn sound off for all listeners of that jukebox

**Comment by lmas** [comment]
It was playing in the bar already. I started fiddling with the piano and
turned off the jukebox. Jukebox started playing again. It kept playing when
I left the area and went to the other side of station.
