### ISSUE TITLE
Add in more hidden content and secrets

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#249]
... A la goon style. KingNexus was hinting at adding in a "special kind of toy" mech, for example.

I think it's a great idea, the game could need more easter eggs and stuff. The audio logs during easter 2015 is a great example which I think added tons of fun and atmospheric value to the game.

There was also talk about making new sprites for the nuka cola and HappydCat offered to make new ones. He also made a bunch of them, so we could for example add in new and hidden cola cans on the station (with custom fluff and drink messages, a la fallout). Seemed like a neat and easy way to add in easter eggs.

**Comment by Kwask** [comment]
I'd rather make them have a different name other than "Nuka-Cola" if it's gonna be a bigger part of the game. At that point, it's no longer just a reference, rather you're just ripping content from other games.

**Comment by ghost** [comment]
I believe one of the suggestions was to rename it "radi-cola". Speaking of the sprites, did the shitty nuka-cola sprite ever get replaced by the one I made?

**Comment by lmas** [comment]
Not sure happy, gotta have to look in the sprite sheets.

**Comment by lmas** [comment]
@Happydacat Sorry, I have forgotten about this. Checked just now and it seems your new sprites was never merged in.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=651
