### ISSUE TITLE
Add camera assembly to tech storage for engineers

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#250]
Because there's no reason they shouldn't have access and be able to make new cameras. There's a crate in AI access for some unknown reason, which is never used. Better move it into engineering instead.

Suggested by @HiddenKn

**Comment by Kwask** [comment]
probably a good idea +1

**Comment by GutsySS13** [comment]
Whilst we're at it can I also suggest a couple of light moves. they clash with some directional signs.

Bridge:
![bridge image](https://raw.githubusercontent.com/GutsySS13/shared-stuff/master/issue-250bridge.png)

Arrivals:
![arrivals image](https://raw.githubusercontent.com/GutsySS13/shared-stuff/master/issue-250arrivals.png)

I also think maybe leave the one in AI access and just add a new one. How about here in tech storage:
![engineering](https://raw.githubusercontent.com/GutsySS13/shared-stuff/master/issue-250eng.png)

As it's a mapping issue I can probably do this if you like.

**Comment by lmas** [comment]
Please do Gutsy, the map editor scares me and I always manage to fuck something up. :+1: for adding a whole new crate.

**Comment by GutsySS13** [comment]
had a play earlier and the editor keeps wanting to do 7k deletes and 7001 additions :/ may have to live with a whole file change.

**Comment by Kwask** [comment]
don't worry about how many changes the map editor creates, it doesn't really affect anything

**Comment by lmas** [comment]
That's one of the things that keeps scaring/annoying me; add in a single item somewhere and the editor spits out 7k line deletions/additions. I know it's because of how the map files are structured, but still. Like kwask said, it should be fine (most of the time).

Closing and directing further talk to #251.

**Comment by Kwask** [comment]
that's what the mapmerge tool was supposed to be used to fix, that and it allowed you to merge changes from multiple people easily, but don't think anyone round these parts knew how to use it

**Comment by lmas** [comment]
yet another thing that scared me, a random binary in the repo. I wonder how
much it was used by the bay12 guys.

**Comment by Kwask** [comment]
Pretty sure bay uses it for all map changes actually :>

**Comment by GutsySS13** [comment]
I did find that if I just saved the file and then reverted the update it would then just make the 3 relevant changes, but then you'd have some extra junk in the merge so it was not that tidy. I'll have a look at this map merge thing.

**Comment by lmas** [comment]
FYI, it was removed when I did the repo cleanup. I made a PR ages ago for
it so you should be able to search for that and find it easily enough.

Someone should probably ask the bay12 devs how they handle this stuff.

**Comment by GutsySS13** [comment]
well it seems to be a pre-compiled (can't see source code sadly) java class files. the batch files I can probably get working in unix so it looks like it should work. The main java class file was updated in June 2014 so it should still work with modern java's.

**Comment by lmas** [comment]
told ya, binary blobs are scary

**Comment by GutsySS13** [comment]
well it seems to work after some major modifications of the scripts. it basically looks in your .git repository for the old map and compares it to the new one. as we've changed all the map names I just hard wired it to point to the apollo/apollo-1-Main.dmm file and it seems to work. It adds two extra blank lines to the file, one between each section and one at the end of the file, but that seems much better than 7k changes.

Lets see if I can remember how to do this in a couple of months :P (I did leave myself some notes).

The java file does seem to list 7k changes but git just registered the one I made. Here's the script output:

> Loading map tmp.dmm
> Loading tiles 7451
> Loading map apollo-1-Main.dmm
> Loading tiles 7450
> Loading levels
> New map part from (1,1,1)
> We have 7450 different tiles

**Comment by ghost** [comment]
Hey Gutsy,
I was wondering where you stored that script because I want to try making some small changes to the map but I don't feel much for causing the git to register 7k of them.

**Comment by GutsySS13** [comment]
Well I just edited the cleantest.sh file.
i'm on a mac so a shell script works, there isn't much you'd need to change for the bat file, it was just the locations of things like java and where the map files are now. ie, GU_APOLLO/maps/$MAPFILE.

the mapfile variable you could probably hard code in if you wanted too, I've got an example remmed out

>  #!/bin/bash
> 
>  ## MAPFILE="apollo/apollo-1-Main.dmm"
> 
> if [ -z "$MAPFILE" ]
> then
>  echo "set the MAPFILE variable for the filename under the maps folder"
>  exit 1
> fi
> 
> cd ../GU_Apollo
> 
> echo "getting headers from GU_APOLLO/maps/$MAPFILE"
>   git show HEAD:./maps/$MAPFILE > tmp.dmm
> echo "cleaning GU_APOLLO/maps/$MAPFILE"
>   "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java" -jar "../mapmerge/MapPatcher.jar" -clean tmp.dmm './maps/'$MAPFILE './maps/'$MAPFILE
> rm tmp.dmm

to run it I just set the map file variable, make the map changes then run this script. that's it
