### ISSUE TITLE
Assistants have access to maintenance, and in proxy to the bartenders shotgun.

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#258]
Assistants have access to maintenance, and because of that to the bartenders shotgun.
I don't see why assistants have access to this given the fact most other staff doesn't.
If we decide this is a feature then I believe at least the maintenance in the bar basement's access should be changed to prevent every assistant being able to walk off with the bartenders shotgun.

**Comment by ghost** [comment]
I think the best thing to do would be to get rid of the access ladder to the bar backroom. Alternatively, what about some sort of floor airlock, like a trap-door?

**Comment by Kwask** [comment]
A simple solution would be to add a windoor in front of the ladder

**Comment by ghost** [comment]
I fixed it, will make a pull request soon.
(Edit: Pull request has been made and accepted, issue can probably be closed.)
