### ISSUE TITLE
Minor tweak, mainly personal preference.

### ISSUE THREAD

**Issue by OriginalHub** [Apollo-Community/ApolloStation#260]
I was just scrolling through cosmetics in the loadout, been a big fan of the jackets since forever. While making use of the grey hoodie, I thought: Wouldn't it be awesome if it had a toggling hood? Not really gamebreaking or worth five days on it though.

Another thing with that, it would be really sweet if it had pockets like the leather jackets. But that's just me I suppose, can't really complain. But both would be neat

**Comment by nullbear** [comment]
im totally fine with this. Would be very easy to do.

**Comment by OriginalHub** [comment]
Awesome, didn't think that would get looked over so soon. Thanks!

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=652
