### ISSUE TITLE
Security breaker not working

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#262]
Last night an AI turned off all breaker boxes across the station to conserve power as there was no engineers on at the time. When I joined half an hour later they posted an ahelp saying that security was still getting power. I confirmed that the breaker box and SMES was off and that a lot of the apc's across security were fully charged.

I've had a look in the map editor and cannot see any cables joining the security sub-grid and the wires under the SMES and breaker seem normal as well. My guess is there's some sort of coding error with security sub grid somewhere. (Hopefully I've not missed a wire under a grill somewhere). 

As it's not a mappnig error I can identify I can't fix it myself, hopefully someone else can spot it and suggest a fix or fix it.

**Comment by Kwask** [comment]
I'm betting this has to do with cables not properly checking their z-level before merging
