### ISSUE TITLE
Doctor can access the medbay substation when they shouldn't

### ISSUE THREAD

**Issue by warriorsofcats** [Apollo-Community/ApolloStation#264]
title say it all, I don't think a Doctor able to access the medbay
should they?

**Comment by GutsySS13** [comment]
Just having a quick look at this and there are some anomolies with SMES access across the whole station. Yes Medical have access to the medical smes, but then so do research. Security on the other hand don't. What's more concerning is that the grid the holo suit is on is accessible to anyone with maintenance access (Beepsky has been pathing badly through this room too I think).

Worrying ? Maybe. Also the engineering SMES seems to have slightly different access again requiring 
10 (Engine access) as opposed to the others which use 11(Engine Setup) and 24 (Atmospherics).

This is a pretty easy fix that I can do if someone wants, but just wondering if others have an opinion.

**Comment by GutsySS13** [comment]
see https://github.com/stuicey/ApolloStation/pull/266 if you want to go ahead with this or let me know if you want me to change some others too.

**Comment by Kwask** [comment]
Fixed in b206309e2dc2fe1429cdb7ea62f4f5d45b426540
