### ISSUE TITLE
Paper Shredders! A suggestion

### ISSUE THREAD

**Issue by MyNameIsKodos** [Apollo-Community/ApolloStation#265]
I had intended to make this my custom item for when I donate, but after further contemplation, I feel like it's something that should just be put in anyway.  Anyway, here goes:
# Paper Shredder
## What is it?

It's a paper shredder you insipid dolt...
## What's it do?

... It shreds paper?
## How do you make it?

Good idea, I have no fucking clue, but it should have a 'recipe' in the event we want more or need to replace one.
## How do you use it?

I'm glad you asked. Basically you use anything that counts as `/obj/item/weapon/paper` on the shredder, and it magically makes it disappear. Well, not really..

The shredder can shred (20-30) pieces of paper before needing emptied.  Once it's full, you'll have to right-click the shredder and hit 'Empty'.  This will empty the shredder and spawn a 'wad of paper shreds' that will need picked up and taken to a disposal unit.

(Optional: Make it possible to attempt to reassemble the paper(s) but the more papers that were shredded before being emptied, the less chance of success)
## Other notes

Other possible features include, but are not limited to
- E-Mag the Shredder in order to force a person's hand into it. (As suggested by Kwask)
- Some sort of machine or way to recycle the paper shreds into new paper, so in longer rounds or rounds with tons of paperwork, we don't run out of paper.

Suggested sprite can be found [here](http://i.imgur.com/kC8KDwd.png).
This is just a suggested sprite, if you guys can come up with something better, I am okay with this.

As for sounds,  I found a couple decent ones for both the actual shredding, and a shredder being opened/closed to empty it. It's just a simple click, so it wouldn't be any more bothersome than some noises.  Those can be found over on freesound.org and if necessary, I can provide links to the ones I liked.

**Comment by Awantje** [comment]
I know for a fact baystation is working on this.

**Comment by Kwask** [comment]
Added in 720138dfec475d3553e156bee80f114c67764f04
