### ISSUE TITLE
Can hold given items in missing hand 

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#27]
If you're missing a hand, but someone gives an item to you, you can still hold that item with your missing hand.

**Comment by lmas** [comment]
The file in question is https://github.com/stuicey/AS_Project/blob/master/code/modules/mob/living/carbon/give.dm
There's no checks if the target bloke's hands is still attached to him. Should be easy enough to check for them if one manages to get the actuall organ references (which I failed to understand how to do, damned voodoo... something about the get_organs proc).

**Comment by stuicey** [comment]
fixed in 75fc61692e6bcf5406c6bcecae4e892aeeb01994
