### ISSUE TITLE
[DEV] The Big Bad Bucket of Bugs

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#277]
Here are all of the bugs currently present on the dev branch. **These should be fixed before merging with master.**
- [x] Lightswitches
- [x] Shuttle controller tags
- [x] Brig timers
- [x] Previously fullbright areas now require lights
- [x] Aghost can't hear mob chat
- [x] Updated color lighting colors
- [x] Disposal pipes need to be properly GC'd
- [x] Cables need to be properly GC'd
- [x] Supermatter pulls lighting overlays

**Comment by GutsySS13** [comment]
no minerals under the ground in the mining outpost ?

**Comment by Kwask** [comment]
That's been around since before this update, this list is just for bugs caused by the update
