### ISSUE TITLE
Fast Light Replacer Refill

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#278]
Clicking on a light replacer with a box of lights should add all the lights to the light replacer

**Comment by nullbear** [comment]
"priority: low" ARE YOU CRAZY!? THIS IS OF UTMOST IMPORTANCE! ILL MAKE SURE ITS DONE RIGHT AWAY!

**Comment by nullbear** [comment]
Added in https://github.com/Apollo-Community/ApolloStation/pull/338

**Comment by nullbear** [comment]
close dis.
