### ISSUE TITLE
Dark Areas

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#282]
Areas that are just too dark
- [x] EVA
- [x] Bar 
- [x] Basement
- [x] Starboard Primary
- [x] Medbay Staff Room
- [x] Operating Theatre
- [x] HOP Office

**Comment by Kwask** [comment]
EVA

**Comment by GuidoBelluomo** [comment]
Bar

**Comment by GuidoBelluomo** [comment]
Spread out patches in the bar basement

**Comment by GuidoBelluomo** [comment]
Starboard primary hallway

**Comment by GuidoBelluomo** [comment]
Medbay staff room

**Comment by GuidoBelluomo** [comment]
Operating Theatre Storage

**Comment by DreadedReborn** [comment]
everywhere is too dark
dont argue with me

**Comment by GuidoBelluomo** [comment]
Outside medbay secondary storage

**Comment by GuidoBelluomo** [comment]
HOP Office
