### ISSUE TITLE
Lower Bar layout change 

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#285]
It's still a bit of a rough design, but I think changing the area under the bar to make it more secure would be a good idea.

Here's something I sort of knocked together this afternoon (haven't tested it yet) where I've moved the dance floor up a bit, the SMES room and the bar area to a more central location.

Ideally I'd rather the bar was in front of the stairs like we used to have it as a sort of greeting area for functions (most theatres push people to the bar as a waiting area for extra revenue) but I think this would sort of work. I've re-routed the pipes and power a bit so they look the part, but I mainly would like to know if this is something you'd agree to.

There is more space available for the barman's storage if you wanted to move that down from upstairs and it's just an empty corridor at the moment, let me know what you think.

![possible bar layout](https://raw.githubusercontent.com/GutsySS13/shared-stuff/master/barproposal2015-10-14.png)

ps. It would need a new area code for the now separate bar.

**Comment by Kwask** [comment]
I'm confused, is this the upstairs bar being moved downstairs? Or the wet bar being moved outside of the dance floor?

**Comment by GutsySS13** [comment]
I've moved the dance floor bar over, the smes room has moved and I re-routed the maintenance pathway behind the now moved bar so people with maint access (Assistants) can't go upstairs and access the shotgun as the barman has an extra store room. 

The upstairs is staying the same, although I have a future plan of re-introducing the mulebot delivery area at some point but space is so tight I can't unless I revamp a lot of areas nearby.

**Comment by Kwask** [comment]
I think it'd be better to move the dance floor east so the stairs go down into the dance floor, the wet bar looks odd sitting out in the hallway.

**Comment by GutsySS13** [comment]
Idea Mk2.

I've kept the bar in the same zone as the dance floor, moved the dance floor up closer to the stairs. changed the SMES room to landscape.

What do you think? 

![Basement Bar move 2](https://raw.githubusercontent.com/GutsySS13/shared-stuff/master/BarProposal2-2015-10-16.png)
