### ISSUE TITLE
Drones can't climb stairs.

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#29]
They can go down, but not up.

**Comment by Fleegle2000** [comment]
I'm willing to take a shot at this. I was able to duplicate the bug on my end with the stairs in the bar.

**Comment by Fleegle2000** [comment]
I've found the source of the issue in the /mob/living/silicon/robot/drone/Bump() proc in drone.dm. This proc does not trigger when going down stairs but it does trigger on going up stairs. The proc checks if the player is colliding with doors, portals, etc. but doesn't check for stairs, so I just added stairs to that list and the problem went away.
