### ISSUE TITLE
Emitters are broken

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#291]
Emitters only put their beam on their own tile, not in a line like normal.
This means the engine cannot be started because the beam never hits the super-matter.

**Comment by nullbear** [comment]
There was a bug at one point with projectiles in general not moving. Do other gun-type weapons work?

**Comment by Kwask** [comment]
At least all beam projectiles are broken:

runtime error: Cannot read null.overlays
proc name: process (/obj/item/projectile/beam/process)
  source file: beams.dm,50
  usr: null
  src: the emitter beam (/obj/item/projectile/beam/emitter)
  call stack:
the emitter beam (/obj/item/projectile/beam/emitter): process()
