### ISSUE TITLE
Sort Proc Functioning Strangely

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#299]
- Object Loadout Menu
- Ventcrawling destination selection
- Teleportation beacons

**Comment by Kwask** [comment]
Maybe this is still relevant

**Comment by lmas** [comment]
Player tab isn't being sorted either. Not sure about the who/staffwho commands but I think they're bugged too.

**Comment by stuicey** [comment]
The recent & operator fix has broke | and ^ which may be the cause. 
As for the player panel the sort is currently disabled as it chops the associated value for all items apart from the last.

**Comment by Kwask** [comment]
Changing to high priority due to the annoyness this causes

**Comment by lmas** [comment]
It first breaks with a runtime error for a null.name at:
https://github.com/Apollo-Community/ApolloStation/blob/master/code/__HELPERS/lists.dm#L223

Then it breaks with a bunch of runtime errors for a null at:
https://github.com/Apollo-Community/ApolloStation/blob/master/code/__HELPERS/lists.dm#L220

and then it begins again with a runtime error for a null.name. This is done whenever sortmobs() is called (most often by the ghost follow() verb).

**Comment by lmas** [comment]
That was not ment to close this ticket just yet.

**Comment by GutsySS13** [comment]
player panel still borked. created a human and he died for science as the round started but it still bugged. There was a xenobiologist feeding slimes.

**Comment by lmas** [comment]
I know, I'm still hunting for the cause of this bug. It's not fixed yet.

**Comment by lmas** [comment]
It's a bug with the monkey cubes and when you wash them in a sink, multiple times in a row with the same cube.

**Comment by stuicey** [comment]
Is this maybe the issue, https://github.com/Apollo-Community/ApolloStation/blob/master/code/modules/reagents/reagent_containers/food/snacks.dm#L1550

The proper way would be new/mob/carbon/human/monkey (SRC.loc)

**Comment by lmas** [comment]
Yep, you got it. Already found the fix in the bay12 repo.
