### ISSUE TITLE
Atmospherics additional pipe, main station vent not configured and missing Zone overlay

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#31]
There seems to be a couple of current issues with the new, live,  atmospheric design.

There seems to be an extra pipe leading nowhere for the scrubber network that may render scrubbers in atmopherics un-useable: Horizontal Pipe location 97,77,1

The zone for atmospherics on the south wall seems to be missing passing through all 4 external tanks, it just looks like the tanks were moved but someone forgot to move the area zone along with it. missing zone starts at 76,74,1 and runs east.

Pressure regulator at 100,87,1 is not turned on and as it supplies the station with air if there's no atmos tech it needs a default setting on. (PS this is a great idea instead of a pump, as these don't use any power)

**Comment by Kwask** [comment]
Fixed in 362cf4edd5877b3dd0d8bbb1e69ddeb07e24c6ae

Thanks for pointing these out!
