### ISSUE TITLE
AI Can't Turn APC's ON

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#319]
Station had low power and shut down some apc's. Was not able to turn them back on afterwards.

**Comment by Kwask** [comment]
And you're sure the AI wire wasn't cut?

**Comment by nullbear** [comment]
The ai tested it again by shutting down the RD's apc then turning it back on, but couldn't turn it back on.

**Comment by lmas** [comment]
It's apparently fixed now according to an ingame AI player.
