### ISSUE TITLE
Medical waste pipe wrong facing on master

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#32]
The waste loop passing through medical has one of the disposal pipe junctions facing the wrong direction. The junction at: 139,114,1 is facing down instead of up.

This results in all trash for the station to be thrown into the emergency treatment centre instead of passing on to cargo for disposal.

**Comment by Kwask** [comment]
Fixed in 4b171bb9b7484b7ba4f9b34eb7bd0ff04c4a4108
