### ISSUE TITLE
SM critical failures use impossible values.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#321]
ex. Engine is at 40% integrity. Critical failure occurs, message appears on radio saying 40% integrity was lost. 12% integrity remaining.

This is caused because higher level SM's have a higher integrity than 1000, but critical failure calculates with the assumption that there is only 1000 integrity.

**Comment by Kwask** [comment]
Might want to check if this is still the case with the new values. I saw that and I think I fixed it. Just need someone to check to make sure.
