### ISSUE TITLE
Wrong area layer for windows in Descublimation room

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#33]
Windows at in mining corridor: 82,110,1 and windows in the new Descublimation room:82,99,1 have the wrong area layer code.

Possible oversight also in the Descublimation  room, the atmospheric alarm at: 87,104,1 is sealed off from the rest of the room, perhaps adding shutters around the area for it to operate, or putting vents/scrubbers for it to control inside would give it something to do. I recommend it's removal.

**Comment by GutsySS13** [comment]
Also the escape shuttle in the area also has the wrong area information, it's classed as in space.

**Comment by Kwask** [comment]
Fixed in 4b171bb9b7484b7ba4f9b34eb7bd0ff04c4a4108
