### ISSUE TITLE
Admin Tools

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#331]
New tools to help admins better administrate without all of the current hassle.

Administration
- Grouping Panel
  - Player grouping: Players are assigned into groups when they first join the server. Staff only see logs for groups assigned to them.
  - Moderators automatically assigned to watch X number of groups, splitting them up evenly among all active mods. AFK mods won't be counted
- Player marking: Mark a someone as a player of interest, which will highlight any logs caused by them

Fun
- RTS-style admin control for clientless mobs. Left-click to select a mob, then using hotkeys, they can make the mob do various things.
- New AdminHUD which has buttons for most commonly used verbs / procs

**Comment by GutsySS13** [comment]
add a few (3?) people to view their recent chat and actions to help with disputes.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=653
