### ISSUE TITLE
Hungry Hungry Glowsticks

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#339]
Nucleations feel hunger, and be forced to walk at a snails pace for rounds lasting longer than half an hour, because they have no way to sate their hunger.

**Comment by lmas** [comment]
Ops, food is handled the same way as any other chemicals last I checked. Going to have to add another check and allow nutrient, like radium. Don't know what the lore says about that though.

Edit: lore check, nucleations doesn't need food. Calling bug.
