### ISSUE TITLE
Add persistent OOC notes.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#340]
OOC notes tab per character that allows players to keep persistent notes per character. Either some chemistry recipes for chemist characters, a prompt for the characters personality, etc.

**Comment by lmas** [comment]
Is it really needed? Sure it's simple to add, but it's way easier to keep notes on our own computers or on some "cloud platform", with better text formatting, file handling, backups etc.

**Comment by stuicey** [comment]
Going to close this as it seems like something nobody would use over just using notepad or wikis.
