### ISSUE TITLE
Cannot drop grabs.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#344]
People are having issues letting go of people.

**Comment by GutsySS13** [comment]
Not sure if it's just a visual bug (ie you do actually drop the person but the icon doesn't change) a few people have had this, but when they move away from whoever it updates.... I've not had it happen to me though.

**Comment by lmas** [comment]
It's a visual bug, happends quite a lot for me. Not just people either, items and things does that too.

**Comment by Kwask** [comment]
Fixed in #351
