### ISSUE TITLE
Omnitool Screwdriver opens door as well as doing it's screwdriver action.

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#347]
The screwdriver omni-tool opens the door when left-clicking with it on the door as well as open the maintenance hatch.

**Comment by ghost** [comment]
The same happens with all other tools in the omnitool and on different things such as glass.

**Comment by nullbear** [comment]
Ah, that's a bug with the way it works, fixing this will allow it to fit in toolbelts as well. ie. -hits door with multitool, hits door with screwdriver-

**Comment by halworsen** [comment]
Omnitool isn't even on the station. Closing this.

**Comment by BlueSushii** [comment]
Atebite the omnitool exists it is made though science.. Although it doesn't have a Sprite it still works as a tool Iam pretty sure.

**Comment by Atebite** [comment]
Yeah, it has no sprite. Considering that among other things, this isn't really a big problem.

**Comment by ghost** [comment]
Yeah, I was told to post this on here even though it was an issue on the development server at the time.
