### ISSUE TITLE
Escape pods do not greentext

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#348]

**Comment by Kwask** [comment]
I can't think of the last time escape pods have ever greentexted

**Comment by nullbear** [comment]
When im trying to decide on what to work on next, i often check the issues. This wasn't in there, and is such an old issue.

**Comment by Awantje** [comment]
I think this can be removed now.

**Comment by stuicey** [comment]
I don't think this applies anymore with the new traitor system.

**Comment by astralenigma** [comment]
@stuicey Everyone keeps getting marooned despite the new traitor system not needing escape on their green text.
