### ISSUE TITLE
Monkeys can wear rig suits.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#349]
Monkeys can deploy rig suits. They should instead break every bone in the monkeys body when deployed :3

As well, monkey backpack inventory icon is placed in a different position than the backpack is placed. Suggest moving backpack inv icon to human position.

**Comment by lmas** [comment]
Monkeys are a subclass of humans, code wise, so that's why they can wear them.

**Comment by lmas** [comment]
It would be easy to check for /mob/human/monkey in the proc for deploying the suit and take "appropiate actions".
