### ISSUE TITLE
Electrocution dmg too random and OP

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#35]
Per 01b37c8dc4c6f3f43133fb07d0b7f6048c7db186, touching an electrified door (for example) _might_ now insta kill you... I would suggest nerfing it some. It could easily be abused by griefers.

**Comment by Kwask** [comment]
As of 96972f519eedce4c47d3d0ee7a1d4b5e7b72953d only cutting powernet cables can cause this much damage anymore.
