### ISSUE TITLE
Omnitool shouldn't be able to be put in a pocket if its engaged

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#353]
If an omnitool has a tool active, it shouldn't be able to be put in a pocket, similar to a telebaton or switchblade.

**Comment by nullbear** [comment]
easy fix. one second.

**Comment by valzargaming** [comment]
Was this ever resolved? Omnitool is currently commented out in the code.

**Comment by Kwask** [comment]
No, omnitool was nuked, this can be closed
