### ISSUE TITLE
Handcuffs cannot be resisted.

### ISSUE THREAD

**Issue by DreadedReborn** [Apollo-Community/ApolloStation#354]
Don't make any robocop references.

But seriously, you are no longer capable of resisting out of handcuffs of any form.
Eating your hands is still viable for escape, if I'm right.

**Comment by Kwask** [comment]
resistance is futile

**Comment by DreadedReborn** [comment]
god damnit

**Comment by stuicey** [comment]
Fixed in c44797396be22cffbf43d922d82faa98e5c3012c
