### ISSUE TITLE
Omnitool hits windows

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#355]
From Happydacat:
Wield omnitool in hand, click on window and you hit the window.

**Comment by nullbear** [comment]
Uhm. I don't understand the issue with this.

**Comment by stuicey** [comment]
It should be using the crowbar / screwdriver

**Comment by lmas** [comment]
But it's not, you merely bonk the window with it like a fire extenguisher when having the screwdriver out.

**Comment by stuicey** [comment]
Doesn't exist anymore
