### ISSUE TITLE
Master branch atmos southern external tank vents have various issues

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#36]
The vents on the 3 external tanks of CO2, Phoron and N2O seem to have various combinations of wrong frequency and/or wrong ID tags that cause the nearby management computers be unable to manage the tanks output.

I've made and tested a map with the attached changes made for you to cut and paste:
https://drive.google.com/file/d/0Bw3ZV7xxvq78b3RNNHl1a0RKRXM/view?usp=sharing
Created pull request 37 for this file: https://github.com/stuicey/AS_Project/pull/37

It looks like someone copied the non functional CO2 vent into the plasma tank so a new vent instance will need to be created if you are editing manually.

The frequency for all 3 vents should be: 1441
the ID's should be: co2_out, tox_out and n2o_out

**Comment by Kwask** [comment]
Fixed in 4b171bb9b7484b7ba4f9b34eb7bd0ff04c4a4108
