### ISSUE TITLE
Suggestion - Vine mutations and Expanding on Spread Genome.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#361]
I don't remember what code it was one, but they didn't have xenoflora, so probably /tg. Instead, they had vine mutations. I'm thinking of adding a similar mechanic on top of what we already have.

A couple ideas for vine mutations:
- Transparency, vines become quite transparent, making them less of a bother to find stuff in, but simultaneously more difficult to remove.
- Endurance, affects how many hits it takes to destroy a vine. 
- Resistance, affects the vines resistance to chemicals and fire.
- Spread, affects the rate at which the vine spreads.
- Overtake Turfs, this will cause the vine to replace walls and floor tiles with vinefloor and vinewalls after a long period of time on them. Welding the walls/floor will replace them with the previous floor.
- Thickness, this will cause vines to block movement if they're given enough time to grow thicker. 

As well, i'm thinking of adding a couple of different spread types. Currently, there is only vines. Here are a couple of my ideas:

Vines. Grows outwards, spreading across any and all surfaces. It requires sustenance to expand, it will take sustenance out of snack vending machines, water tanks, food on the ground, hydroponics trays, etcetera. For every tile that is able to eat, it will grow faster as a whole. The most effective way to kill it is to cut it off from its food sources. When it matures, it will drop its fruit, potentially allowing it to grow further. Its main strength is the rate at which it spreads. Its main weakness is its reliance on food and water. Carnivourous variants of the plant will consume meats, and are able to ensnare its victims, feeding on them.

Spores. Grows like glowshrooms. When matured, if stepped on, it will release a cloud of spores which will affect the person stepping on them, as well as allow it to spread further. This is a much slower spreading plant. The main strength of this plant is its ability to transfer chemicals into people walking over them. It's main weakness is its slow growth and expansion. Carnivorous variants of the plant are able to attach to human hosts, using their bodies for sustenance, and allowing them to spread much further.

Roots. Grows UNDER the floor tiles. It will generally grow in a long gridlike pattern, and occasionally sprout when it finally matures, (more like burst, it will do tons of damage to anyone who happens to be there at the time.) creating a solid pillar that acts as a wall. Its main strength is its durability. It will take a long time for someone to destroy one of its roots or trunks, which drop wood when destroyed, and its ability to grow underneath floor tiles, hiding itself from the crew. Its main weakness is its slow rate of growth. Carnivorous variants will attempt to sprout trunks underneath of living things.

Grass. The most tame of spreading types. It can be placed as a floor tile, and when it matures, it will spread to the next tiles around it. Its main strength is its passiveness. It is the least dangerous, which generally results in it being left alone. Its weakness is its  slow spread, and the ease at which it can be removed. Carnivourous variants will wrap around prone mobs, (such as corpses, resting, sleeping, etcetera), paralyzing them and eating them slowly.

---

just leaving this here instead of the forums, for some reason.

**Comment by Kwask** [comment]
Before anything, vines need to be nerfed, pretty crazy overpowered with their speed.

**Comment by nullbear** [comment]
yea the requisite for vines to have water and food to grow makes them easier to kill, as well as limits their growth distance by the locations of food/water stuff. Cut off the water, and they will stop growing.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=654
