### ISSUE TITLE
Scythe transcends windows.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#362]
The scythe is able to interact with vines and stuff behind windows and possibly walls when the person using it wouldnt be able to.

**Comment by Kwask** [comment]
what is the scythe?
a tool of death.
what is death?
an incorporeal being which transcends all forms.
by necessity, the scythe then must also be an incorporeal object which transcends all forms.
therefore this is a feature, not a bug. QED.

**Comment by Haldreithen** [comment]
As the tag says, feature!
