### ISSUE TITLE
Power

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#363]
A bunch of issues with station power:
- [x] APCs are not charging, there is power in the wires.
- [ ] Substations insta charges when the engine is running and you toggle on charging for them.
- [x] Runtime errors for solars:

```
runtime error: Cannot read null.powernet
proc name: set angle (/obj/machinery/power/tracker/proc/set_angle)
  source file: tracker.dm,57
  usr: null
  src: the solar tracker (/obj/machinery/power/tracker)
  call stack:
the solar tracker (/obj/machinery/power/tracker): set angle(74)
Fore Starboard Solar Control (/obj/machinery/power/solar_control): update()
/datum/sun (/datum/sun): calc position()
sun (/datum/controller/process/sun): doWork()
sun (/datum/controller/process/sun): process()
/datum/controller/processSched... (/datum/controller/processScheduler): runProcess(sun (/datum/controller/process/sun))
```

**Comment by Kwask** [comment]
Might be worth checking if any of these are related to #281

**Comment by lmas** [comment]
Oh yeah, related for sure. I forgot about that one.

**Comment by lmas** [comment]
Gonna close this for now, two issues have been solved over time it seems and I almost consider the substation instacharge to be a feature.
