### ISSUE TITLE
Can't replace air in room

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#364]
Vent all air in a room, try to refill with new air. Not working

**Comment by Kwask** [comment]
Vents seem to not be outputting any gas to the environment, yet they can still take gas from the environment.

**Comment by MysticalLatios** [comment]
It appears to be a problem with the floor vents. I tested on a small scale closed loop system of a vent a tank and some pipes and I was unable to use the vent to output from the tank.

**Comment by nullbear** [comment]
This greatly affects mining/xenoarch and engineering as it prevents airlocks from functioning properly.

**Comment by lmas** [comment]
Same thing with any escape shuttles. I'm going to upgrade this issue, it's quite game breaking in a major way now...

Edit: tested the airlocks as far back as 
~~d914a5e40eeb79fc634b224f575bf8e40931eb3b~~
~~687fb4743b1903eb7a88b8e0b9155d1bd2cda7b6~~
~~6a3a844a79382c17a26f7d458b6913cf4e501345~~
still not working. ~~It's a really old bug, apparently~~. Running on Byond Stable, Build 508.1299. 

Edit2: I'm now going to blame it on Byond.

Edit3: Some issues on bay: https://github.com/Baystation12/Baystation12/pull/11123. Closest match I could find related to the failing airlocks. Found nothing that's closely related to buggy air vents. I have no idea why anything of this is broken.

**Comment by Kwask** [comment]
Urgent is reserved for server-crashing bugs :p 

Low: No real effect on anyone's round
Medium: Has a noticeable effect on a few people's rounds
High: Has a noticeable effect on everyone's round
Urgent: This kills the server
