### ISSUE TITLE
Reagents taking forever to metabolize

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#365]
It seems every time we lower the tickrate, metabolism rates decrease exponentially. I saw someone who was injected with sleep toxin and 10 minutes later they had metabolized less than 0.01 units.

**Comment by lmas** [comment]
I noticed the same thing with the engine emitter, it's greatly slowed down with the lower tickrate.

**Comment by lmas** [comment]
Food too, you never get hungry anymore.

**Comment by Kwask** [comment]
Fixed in fd31a5b77532689d8014cc91bf8b47052f692d82
