### ISSUE TITLE
Suggestion: Add new vendor/lathe for stock components

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#376]
As it is, in order to craft new machines, you NEED to have a scientist. I'm suggesting to add a new vendor that starts with the basic machine components: laser, matter bin, etc.

The vendor is able to scan new components and add them to its vending options. So a scientist can discover upgraded stock parts, put them in the machine, and an engineer can use them as needed. Instead of needing to be restocked with a restocking kit, or with individual components, it will need to be restocked with metal, glass, diamond, etc. The number of components available to vend would depend on the amount of materials in the machine.

There could be a variant for circuit boards as well, that vends basic boards, and once new boards are scanned, can be stocked with materials and vend those.

These vending machines still require support from mining in order to upgrade machines, as well as support from science in order to get new machines and new upgrades, but allow engineering to actually upgrade machines around the station and build more devices and rebuild rooms that have been, well, blown up.

If balancing is needed, we could adjust the material costs for the components, or remove certain circuit boards from tech storage to prevent them being produced easily.

Ideally, this concept of vendorlathes could be ported over to other vendors as well. Allowing them to scan certain objects in order to add new "recipes" to the vendor. And require them to be stocked with materials rather than with cargo-ordered restock kits that noone ever orders. It's more futuristic and stuff too. (cargo could still get specialized restock kits as well, though.)

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=655
