### ISSUE TITLE
Suggestion: Add new stock component

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#377]
New stock component used in specific machines that adds a scaleable useage for power.

Transformer.

The transformer component comes in all the same tiers as other components like capacitors, matter bins, etc. And its main function is to affect the rate at which a machine charges.

Here is an example of its use:

Vendorlathe for a circuit, takes approx. 1 full minute to finish producing. The transformer component inside can be upgraded through 5 tiers (i think there's 5 tiers of components? It might have been 4 but someone added a fifth. or they added a sixth)

tier 1 - 1x charge speed.
tier 2 - 2x charge speed.
tier 3 - 3x charge speed.
tier 4 - 5x charge speed.
tier 5 - 10x charge speed.

As well, there will be a wire for "overclocking" specific machines to cause them to operate faster, at the cost of more power. The rate at which they are overclocked is dependent on their components. Primarily the transformer:

1x speed and 1x power usage.
2x speed and 2x power usage.
3x speed and 3x power usage.
5x speed and 5x power usage.
10x speed and 10x power usage.

---

Along with this new component, im thinking macahines could be changed in the way they operate to something like this:

they have a small internal energy storage which charges slowly depending on the transformer component. Once it is fully charged, it is able to perform ten processes. Assuming this is the autolathe, you need to wait 30-60 seconds between each ten processes before it will finish charging, and process again.

Upgrading the capacitor in the autolathe allows it to overcharge 1,2,3,5,10 times. Assuming you're using a t5 capacitor, when not in use, the machine will slowly overcharge to 10x, allowing it to be used 100x before it will tell you it needs time to charge. This gives incentive to upgrade machines around the station so people don't have to wait an age, and then upgrade he power so that the machine doesnt sap the SMES's, and so on.

Lets say we have a fully upgraded autolathe, that's been overclocked. It will be able to process 10x before needing to charge (becuz overclocked at t5 uses 10x as much power) but will process about 100x faster (t5 manipulator + t5 overclock = 10x10xprocessingspeed) 

Gimme yo feedback on this.

**Comment by BlueSushii** [comment]
Would definitely be very useful for the Chem dispensers in chemistry as they recharge extremely slow and half the time your sitting around waiting for them to recharge.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=656
