### ISSUE TITLE
Malf AI and rev rounds just immediately end

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#386]
We just had 2 rounds auto end as soon as they start. one was malf AI and the other revolutionary.

(also server boots me after it reconnects but that may not be a server issue)

**Comment by stuicey** [comment]
Sounds like a good feature to me

**Comment by stuicey** [comment]
On a serious note, was it voted in or randomly chosen as the game mode?

**Comment by GutsySS13** [comment]
both were voted for

**Comment by GutsySS13** [comment]
extended now works though

**Comment by stuicey** [comment]
Just tried locally with 4 active accounts and revolution started fine.

**Comment by lmas** [comment]
Happend last weekend too, people voted for Malf (and there was a AI player) but the round just ended. I think you were there Stu. Friday or something.

**Comment by Kwask** [comment]
Disabled the gamemode, unsure if it'll be re-enabled in the future.
