### ISSUE TITLE
Can't change direction of gas coolers

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#39]
Per https://github.com/Baystation12/Baystation12/issues/7652, one can't change the direction of coolers either by applying a screwdriver to the circuitboard or by facing the correct direction when making a machine frame. 
Someone removed the code setting the dir on the machine construction.

**Comment by stuicey** [comment]
Added rotate() verb to freezers and heaters in 75fc61692e6bcf5406c6bcecae4e892aeeb01994.
