### ISSUE TITLE
Dislocating and Eye-squishing.

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#393]
They both seem to be commented out in the code, on ApolloStation/code/modules/mob/mob_grab_specials.dm . I'm not too good at coding and what not, but wouldn't simply un-commenting them make it work once more?

**Comment by Kwask** [comment]
I commented them out for some reason, but I can't remember why. I think they just don't work without porting some more stuff from bay.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=657
