### ISSUE TITLE
Omni gas mixer is broken

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#394]
No gas flows through omni gas mixers.

Ruins a lot of possibilities when constructing pipes.

**Comment by lmas** [comment]
Yep, I've had problems with it too. There's another gas mixer that works though, can't remember it's name right now.

**Comment by GutsySS13** [comment]
could be a problem for atmospherics then, it uses omni filters to filter the incoming gasses into their respective external tanks. Want me to map edit to make the older pipe routing system?

**Comment by Atebite** [comment]
This has nothing to do with the map. Mixers in general are broken. For example, if you replace a manifold with a mixer, no gas is gonna flow through that mixer.

**Comment by halworsen** [comment]
Atmos seems to work fine as it currently is. Only mixers you place yourself have this issue.

**Comment by runedog48** [comment]
You cannot turn them on? That's what I'm experiencing.

**Comment by runedog48** [comment]
It's working for me.
https://www.dropbox.com/s/5h173hs2pdi9tud/Screenshot%202016-01-13%2017.31.25.png?dl=0

**Comment by halworsen** [comment]
Works sometimes, most of the times, though, I find it doesn't. Try taking out some pipes in atmos and replacing them with a mixer. That's usually where I have issues with it.

**Comment by rjtwins** [comment]
I've been using the omni gass mixers and filters allot, they work just fine for me

**Comment by halworsen** [comment]
Reported to have happened today

**Comment by rjtwins** [comment]
Ive looked into the code seems a working spageti ball. I need more feedback on what the exact situation was.

**Comment by CakeQ** [comment]
Seems to be working now.
