### ISSUE TITLE
Web page for player deaths, stats etc.

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#399]
Any interest for a new statistics page filled with player deaths, ban logs and other misc. goodies from our game database on the server? I got the idea from [Goon](http://goonhub.com/) and [/vg/station](http://ss13.pomf.se/index.php/bans).

List of example pages (more or less a ripoff of goon and /vg):
- Account item log (granted item, to player, for cause)
- Player deaths (killed player, IC name, time, cause, location for death)
- Ban logs (banned player, by admin, time, cause for ban)
- End round stats log (straight copy of the existing end round stats window IC, if we could store it in the DB)
- ~~Git commit/server version log (could try pulling this info from the local repo on the server)~~

I could cook something up with a little bit of Go and make a stand alone linux binary that could easily be run on the same server that runs the game itself.

**Comment by stuicey** [comment]
From what I believe someone was working on that? I remember seeing a heatmap of deaths somewhere

**Comment by lmas** [comment]
Now that you mention it.. I think I saw that on reddit? or some wiki page.

**Comment by stuicey** [comment]
Calling @kwask

**Comment by Kwask** [comment]
@HiddenKnowledge made a rudimentary python script that would generate a heatmap. @Anonanimal did as well, but we didn't have a high-resolution image for him when he did his.

**Comment by GutsySS13** [comment]
not sure about bans. that could be used as a bragging tool either evading or being banned so many times etc. I like the heatmap for deaths etc. 

Would even be funny so see the paths people take but that may be a bit much as it would just be a novelty thing. maybe count doors that open or co2 in a room to calculate room count, not sure.

**Comment by lmas** [comment]
Yes I was thinking of that too, with the bans. But it could be the same
thing with deaths I guess? Yet another incentive for doing bad stuff on the
server.

I like the idea oh showing the walk path prior to a death. Seems a bit
expensive to calculate and display, though.

**Comment by Kwask** [comment]
I think public bans is fine. If people want to brag about how many bans they have, they'll do it with or without proof anyhow, so I think that's a non-issue.

Deaths would be hilarious as well I think, but would need to be updated only on round end, so people don't use it to metagame. We still have rules on the server, so people won't go and break roleplay to get themselves killed because they'll get banned.

**Comment by ghost** [comment]
I think you mean @HiddenKn, not @HiddenKnowledge.

**Comment by lmas** [comment]
Alright, I've started working on it and begun making drafts for the pages in a [new repo](https://github.com/lmas/ApolloStats). Tell me if you would like to have it transfered to the apollo organization instead or if there's something else you would like to see on the pages.

Any specific reason for setting it as urgent? I've set a soft deadline, for public display of the pages, on New years eve :p

**Comment by Kwask** [comment]
urgent because mega-cool. 

Would be good for it to be under the apollo organization so anyone who knows what they're doing can contribute to it easily

**Comment by lmas** [comment]
My thoughts exactly.
