### ISSUE TITLE
The custom gas sprites block clicks

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#4]
After c064dd6594021511a2427f84713340d969ae9d5e, the sprites will block any attempts to click on stuff in the main window, like items, machines and bodies. The only way to interact with things is to alt+click on the tile and use the stuff as it pops up on the item list.

Unsure what the cause is. ~~The gas sprites are probably on the top of the tile drawing order, while they should be on the bottom instead?~~ Or is ss13 utilizing image transparency in tiles somehow, which the new sprites lacks?

**Comment by Kwask** [comment]
Fixed in 6bfaa694b01c6586ba82dc0a0b7c608fc5622d0e

**Comment by lmas** [comment]
Cool man
