### ISSUE TITLE
Missing various assets

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#40]
- [x] More hairstyles for nucleations.
- [x] Some missing sprite for skrell. A giant ERROR shows up over them.
- [x] Sprites for dmg tape recorder is missing (or what it's called), in bar basement.
- [x] Sounds for breaking wooden barricades
- [x] Supermatter floor splatter, after detonation, shows up as a blank tile

**Comment by Kwask** [comment]
I was thinking we might make it so you can't unwrench the record mixer and move it around, since in reality it's probably hooked up to a sound system in the dance floor. That would remove the need for that sprite at tleast

**Comment by JMMJ01** [comment]
As long as I can throw it like a ghost in Build-mode. Also, unwrenchable
would be a good idea. As you said, no way in hell would moving soundboard
be that easy. Way too many hookups.

**Comment by lmas** [comment]
Agreed.

**Comment by Fleegle2000** [comment]
As I'm a newbie DM coder, I'm looking for things I can help out with - I'm looking into the missing skrell sprite as I saw that the other day, but I'm not sure what's missing.

**Comment by lmas** [comment]
It's probably some changed/renamed sprites. You could try compare the
sprites in our repo with the skrell sprites in the upstream bay12 repo. The
files are probably somewhere in the /icons/mobs/races something something
directory.
I've been thinking of taking a look myself but you're more than welcome to
check too :D

**Comment by Fleegle2000** [comment]
The skrell sprites are in icons/mob/human_races in r_skrell.dmi and r_def_skrell.dmi. The bay12 and apollo sprites are identical. I suspect it is not an issue with the skrell sprite itself but an article of clothing or other wearable - perhaps specific to skrell. I've looked and haven't found anything like that so far.

Edit: well, I've ruled out anything wearable.

**Comment by stuicey** [comment]
If I recall correctly it is an issue with missing/renamed sprites for skrell hair.

**Comment by lmas** [comment]
Correct, there's an issue in upstream about it and a fix for it in the dev-freeze branch. The file human_facial.dmi (I don't know why the hell they named it that way..) inside icons dir, contains all "facial features" such as a beards and skrell tentacles. It's missing two standard sprites for skrell.

There's some custom apollo sprites in that file so it needs to be moved to the icons/apollo dir and all code referencing the custom sprites needs to be updated aswell. Then we can merge in and replace the sprites with the file from dev-freeze.

**Comment by Fleegle2000** [comment]
Doing a search for human_face.dmi in all files only turned up a handful of references, all of them generic (none specifically reference the custom sprites). One of the missing skrell sprites is skrell_eyes_s, and I notice that there is a reference to human_face.dmi and current_species.eyes in preferences_setup.dm. So I don't think we have to change the code at all.

Edit: sorry, no, I take that back - we do need to change the references to icons/mob/human_face.dmi to icons/apollo/human_face.dmi

**Comment by Fleegle2000** [comment]
I moved human_face to icons/apollo and copied the skrell_eyes_s from upstream to that file, and the error is no longer there. If you like I can push my branch over.

**Comment by stuicey** [comment]
go for it @Fleegle2000

**Comment by Fleegle2000** [comment]
So, the only thing left here is more hairstyles for nucleations - about how many more are we talking about and what kind of guidelines should we follow? In other words, what will it take to call this one complete?

**Comment by Kwask** [comment]
Probably 5 or so different hairstyles would be good. Mohawks, big spikes afros, etc etc, anything that looks spikey is what we're goin' for wth them

**Comment by lmas** [comment]
What about colors? Mostly SM yellow I guess? Maybe a dash of human blood red to make things more colorful?

**Comment by Fleegle2000** [comment]
I added a new unisex nucleation do to my branch. I like it, but then I am a bit biased.

**Comment by Kwask** [comment]
I was playing around with the idea of nucleations being allowed to be multiple colors, but I'm not sure yet. Also, originally nucleations were going to be unisex, but I couldn't get it to work because of reasons. If you managed to get it, that'd be fantastic

**Comment by Fleegle2000** [comment]
Well, I had it running okay. I can try to make the default nuke hairstyle unisex too.

**Comment by Kwask** [comment]
yus, also make is so that is the default hairstyle, instead of baldie

**Comment by Fleegle2000** [comment]
That should already be the case, as in the code Nucleations are not listed as one of the allowed races for Bald, and it doesn't show up as an option when I run it.

**Comment by Fleegle2000** [comment]
I see now what you mean about bald being the default hairstyle - looks like that is still the case, and I'm not sure why. You can't select it, but if you don't bother setting a hairstyle it defaults to bald.

**Comment by Fleegle2000** [comment]
I think we can call this one closed.

**Comment by JMMJ01** [comment]
I prefer calling it missing various assets.
