### ISSUE TITLE
Permanent bank accounts ICly

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#400]
Permanently store the balance of a characters bank account in the server DB, at the end of a round. 
- New characters would get a standard (but slightly random) starting balance (just how it's currently done on each new round).
- New money is earned by completing (aka surviving) a round and is modified by the station's end round performance rating.
- Security could give out fines or players thrown in jail is automatically fined a sum based on their cell time.
- Recalling a shuttle and stuff like that will actually dock the employe payments.
- New traitor objective: steal money.

Pros:
- More reason to use money ICly, RP wise (broke characters, beggars).
- Already a lot of machines that handles a player's money.
- Simple to implement.

Cons:
- Giving players money at the end of a round would probably be a strong incentive to green text and/or grief.
- Abusive security could grief and waste a lot of player money.
- Less reason to call the shuttle.
- Characters actually getting broke and can't get money for vending machines (solution: start a new character).

Edit: Time to celebrate the 400'ed issue ticket in our server repo? :D

**Comment by stuicey** [comment]
I believe we discussed this before and came to the conclusion that it would be best to wait until we had implemented major economy mechanics. Such as cargo auction house, updated EFTPOS and rebalanced vending machines.

My major issue with it is people may start charging for medical or cloning procedures. Or only play jobs that give the most potential for money. Ie - someone may enjoy playing janitor but they earn pennies compared to another role.

**Comment by lmas** [comment]
I haven't thought about charging for medical, that's kinda bad. 
And yes, I was thinking about jobs paying differently so I avoided adding it to the pro list (but forgot to add it to the cons). Was thinking of giving an equal sum for all surviving players but that feels kinda meh when you get the same payment as a captain and janitor.

It's too bad it's such a strong incentive for so much bad behaviour...

**Comment by stuicey** [comment]
The only way I can see it working is if you tie money to characters rather than players. That way you could RP as a poor janitor just scraping by or a well off doctor ect.

**Comment by lmas** [comment]
That was what I wrote in the first post. It's easy enough to make a new char and start off with more money again if you would lose it all.

**Comment by Kwask** [comment]
Yeah, this would be introduced with a whole bunch of other stuff that I have planned, which I'm just vaguely referring to as "persistance" at this point. Stuff like permadeath, security / medical logs that persist through rounds, etc etc

**Comment by lmas** [comment]
Great, I've been wanting more persistance too.

**Comment by lmas** [comment]
Closing until further notice.

**Comment by nullbear** [comment]
Well another way you could do it is to give players a small amount of cash at the start of their shift, so that they never 'run out' of cash and have to make a new character. This small amount of cash would only be triggered if they had less than x. And preferably wouldn't be enough to abuse.

**Comment by stuicey** [comment]
Or pay a hourly salary, so the first tick starts when they arrive on station. Time would be different for everyone which is annoying but seems like the fairest way to do it.
