### ISSUE TITLE
Empty Player Panel list

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#401]
With dev rank at least, the player panel buggs out sometime and won't list any players and their IC names and options. Seems to always work near round start but bugs out after a while in a round. Unknown what causes it.

Today I joined a 1:38h long round, for the first time today, and the list was bugged out.

**Comment by Kwask** [comment]
Yeah, I'm still not certain when any why it bugs out. Whenever it does, a lot of procs break at the same time. Allow Player to Respawn, Follow as ghost, ventcrawl

I'm still pretty sure there's a list proc thats going bonkers somewhere, see #299

**Comment by lmas** [comment]
Closing due to duplicate issue
