### ISSUE TITLE
Slime golems

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#403]
Reported by King_nexus:
Golems made from adamantite slimes won't take any damage and can't die.

**Comment by Kwask** [comment]
Still not certain this is a bug, considering adamantine literally means "unbreakable", and is more commonly known in mythical settings as the strongest / hardest material ever.

If anything, making adamantine golems should just be incredibly difficult

**Comment by lmas** [comment]
Maybe but isn't it too OP? Imagine griefers getting their hands on one.

**Comment by DreadedReborn** [comment]
its called gibbing griefer golems
GGG for short

**Comment by Kwask** [comment]
GGG no re

**Comment by lmas** [comment]
It's your call, I'll close this for now then until it may become an actual issue.
