### ISSUE TITLE
Cloning issue - Cloned person dies before reaching cryo

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#404]
Last night I had an issue where I tried twice to clone the chef (Richard Williams). The cloning process went smoothly itself, but before I could put them into cryo they died. The second time I waited for them to pop out and put them in as fast as I could and they still died.

The person reported they were in pain even in the cloning vat. Kwask said they had high toxin level, but I hadn't injected them with anything, just moved them from cloning to cryo tube.

**Comment by lmas** [comment]
Could be the increased metabolism rate that was raised a day ago.

**Comment by Kwask** [comment]
Should've been fixed in db64c052bdd91f08df8f991232972edcd87b0fd8

**Comment by lmas** [comment]
Nope, people die in the cloner now. Tried it locally.

**Comment by Kwask** [comment]
I'll have to check what reagents are being injected into clones when they're being cloned. There's probably one with a toxpwr level.

**Comment by Kwask** [comment]
Fixed in ac186e8f73837e8dc7d1f1e46ad223f99707d00d
