### ISSUE TITLE
anesthetic tank doesn't keep people under

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#407]
as title says. anaesthesia doesn't seem to work fully. people keep waking up briefly.

**Comment by Kwask** [comment]
Like actually wake up where they can talk and stuff? I know part of the anesthetia knockout screen overlay has a brief flicker where it shows everything.

**Comment by GutsySS13** [comment]
no they can say 1 word before it kicks in again aparently

**Comment by lmas** [comment]
Bug that has been in there for ages. I don't know how it's now, but before the metabolism change the patient would wake up for about a minute and could talk, feel pain and stuff before returning to sleep again.
