### ISSUE TITLE
A bunch of machines not finishing work

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#408]
Examples:
- [x] The grill won't stop cooking
- [ ] The cryofreezers won't get rid of stored bodies.

Not sure, but I guess it's related to time and/or the spawn/sleep proc?

**Comment by Kwask** [comment]
Since this doesn't actually prevent anyone from playing, am setting it to low priority.

**Comment by lmas** [comment]
I was unsure if there was any other, more important machines so I winged it.

**Comment by lmas** [comment]
Noticed that when someone was inserted into a cryopod `time_entered = 5587.68` was set.
After `18000 ticks` the body should be despawned by https://github.com/Apollo-Community/ApolloStation/blob/master/code/game/machinery/cryopod.dm#L282, but after the ticks have passed it's still not being run. Must be a problem with `machinery/process()`.

**Comment by lmas** [comment]
Found the problem with cryopods, opened a new issue just for them at #428.
