### ISSUE TITLE
Bugged wires on space tiles

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#41]
Wires should need some kind of foundation to be laid up on?

Also, when layin wires on space tiles, the tile itself turns into a solid grey sprite. Stepping onto said tile might randomly teleport you into space I think.. On some other level too, can't escape it by floating to the borders.

**Comment by Kwask** [comment]
I think this has to do with z-levels. When you place a cable on them, it somehow makes a connection between the top level and the bottom level, and when you move into it and get teleported somewhere random in space, that's actually just moving down a level.

**Comment by stuicey** [comment]
This is due to kwask's awful cheaty fix he did to get latices to work. He made lattices an object instead of turf so had to do some special code that generates a fake space tile when you place wires.

**Comment by Kwask** [comment]
hey man, it works (most of the time)
