### ISSUE TITLE
Unable to create/remove antags

### ISSUE THREAD

**Issue by bryanlavergne** [Apollo-Community/ApolloStation#411]
In the traitor panel, there's the TRAITOR line with two clickable options: Traitor and Employee.

When the server selects a traitor in AutoTraitor, it changes that line from Employee being selected to Traitor being selected.

Admins are suppose to be able to click and change this as well through the TraitorPanel, but clicking it does nothing. Therefore, one can't add someone as an antag or get rid of somethings antag status, i.e. remove their traitor status.

**Comment by lmas** [comment]
I might try merge in https://github.com/Baystation12/Baystation12/commit/ec5e05b9f1835fc65a9d773c1aff2badb6ab0629 and related fixes to clean up the antag panel.

**Comment by bryanlavergne** [comment]
I'm completely in favor of that. That commit really cleaned up the antag system. I'd like to have it here.

**Comment by lmas** [comment]
Lemme see if I can do some magic.. Also setting this to medium because it's so bloody boring for everyone when an antag goes SSD and leaves the rest of the round uneventfull.

Edit: Ops, this is a hard one to merge... Eh crap, this will take a lot of work.

**Comment by lmas** [comment]
FYI, you can make a bunch of antags all at once using the `Create Antagonist` verb found [here](https://github.com/Apollo-Community/ApolloStation/blob/master/code/modules/admin/verbs/one_click_antag.dm#L2). Do note that a "bunch" of players will be selected (usually 3 players).

Edit: Oh yeah! Looks like the antag spawning was commented out during my monkey patch for some reason. No idea how I have missed that D:
