### ISSUE TITLE
All pills do not work.

### ISSUE THREAD

**Issue by GuidoBelluomo** [Apollo-Community/ApolloStation#413]

**Comment by DreadedReborn** [comment]
Yeah, they are consumed but do not provide any of their reagents.

**Comment by Kwask** [comment]
Fixed in f354804c7c8a7783ca37ecc537a408f7ee99e4de

**Comment by lmas** [comment]
So it was the two `spawn()` lines that screwed things up?

**Comment by Kwask** [comment]
Yeah

**Comment by lmas** [comment]
Nice catch, good to know.
