### ISSUE TITLE
ripleys only mine 1 square at once

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#415]
Ripleys seem to only mine 1 square at once. I tried a diamond drill on it aswell, no joy.

They are pretty much pointless as you can mine faster yourself and you auto pick up stuff.

**Comment by GutsySS13** [comment]
i spawned in a mining ripley too and same thing. it doesn't pickup ores either and also mines 1 square at once.

**Comment by lmas** [comment]
Ripleys works again. I think I accidently fixed this in 486a369fdc2146c98229d19304a0a292659d1607.
