### ISSUE TITLE
Monkeys and backpacks

### ISSUE THREAD

**Issue by Hate9** [Apollo-Community/ApolloStation#418]
Monkeys can be picked up, and have backpacks equipped to them (containing any item which a backpack could normally contain), but (of course) backpacks cannot be placed in eachother. However, monkeys **wearing backpacks** can be placed in backpacks.
This means that you can increase your storage space by as many backpacks as monkeys you can obtain.
I'm pretty damn sure breaking reality should be fixed.

**Comment by nullbear** [comment]
This should be fixed by my storage changes.

When i do them.

**Comment by Hate9** [comment]
Oh! Hey, Null!

**Comment by lmas** [comment]
We could simply forbid dropping monkeys into a backpack and blame it on their size ;)

**Comment by Hate9** [comment]
It probably would, and if I knew Git, I'd probably just change their size and make a commit request (or whatever they're called).
Also, I think fixing their interaction with bags of holding would be harder (since I think they only check their immediate contents).
