### ISSUE TITLE
Language and Papers are Meta-able

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#419]
Tested with AI. Reading a page as an ai will show something like:

"N**l**r L_u_*\* C*_e"
"1_5*3"

But if you read it again, a different text will appear:

"_uc_ea\* _a_nch _od_"
"_2_4*"

making it possible to determine what something says, or another person is speaking, by saying it a few times, or reading it a few times.

"Nuclear Launch Code"
"12543"

**Comment by stuicey** [comment]
I feel like I'm fine with this, as it only happens when the page is written in an unknown language. 

It's quite a rare occurrence and putting the effort in to decode it warrants the reward on my books.
