### ISSUE TITLE
Gas coolers cannot be rotated

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#420]
You can't open their maintenance hatches to deconstruct them either.

Obviously an ultra-high priority issue because it means I can't complete this wonderful piece of art.
![hlp](http://i.imgur.com/h89HDyB.png)

**Comment by nullbear** [comment]
but those look like they've been rotated? O.o

**Comment by halworsen** [comment]
I had to ahelp to get them rotated. Even then, I couldn't get them working properly.

**Comment by lmas** [comment]
I've had this issue too, varedit the direction will not solve the problem. The coolers apparently needs to connect to the pipe using a new "Node" obj, in a Node list for the cooler.

I'm betting it's because of #409 and the name change of metal sheets.

**Comment by lmas** [comment]
After 1ea05b8fd0a4454b2513dc3f34fec88a02503211, an admin can now varedit `dir` and `initialize_directions` to the same value to manually change the direction of the cooler and the player can himself connect the cooler to a pipe with a wrench.

Players still can't change direction or open the hatch.

**Comment by Kwask** [comment]
Fixed in e4ab151dafefe99fd8025ef1a26c4e7bdeb9582e

Now you can unwrench unary atmos machines to rotate and drag them.
