### ISSUE TITLE
Xeno blood is red? Language stuff.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#423]
I'm working on chemspills and porting over blood splatters to be a part of the chemspill code (which is really just an expansion of blood splatters to include other chems too) 

And doing some testing, i noticed, taking a blood sample from a xeno, or any other race with coloured blood, results in basic-bitch red blood. Digging a little deeper, i found that the issue was caused by one part of the take-blood procedure using data["blood_color"] and another using data["blood_colour"] and the question came to me:

What fucking language/spellings should we be using for apollo-code? American vs. English spellings? As far as i was able to tell, byond uses american spellings for built-in variables and stuff.

**Comment by lmas** [comment]
I usually stick with american english, not _british_ english, because it's uh.. simpler, sorta I guess? If most of the code is using american then we should do the same. 

And whoever coded that `blood_color` thing is probably stupid.

**Comment by Kwask** [comment]
Yeah, the vast majority of the playerbase is american, so stick with american english
