### ISSUE TITLE
Stools go poof!

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#425]
click stool to pick up.
drop stool to disappear.

**Comment by Kwask** [comment]
Fixed in 1f62079cf9d399fa8e58b2b53b37f2010f46428e

**Comment by lmas** [comment]
All stools on the map needs to be replaced with the new object, as the current stools still uses the old object path and therefore are invisible.

**Comment by Kwask** [comment]
Looks visible to me http://i.imgur.com/bKNmYCs.png

**Comment by lmas** [comment]
- [ ] Also stools in medbay.

**Comment by lmas** [comment]
- [ ] Virology
