### ISSUE TITLE
Cryopods don't store bodies after a while

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#428]
Resulting in a lot of sleeping AFK bodies in cryo and no radio notifications. It's been like this for a long while now.

Today I noticed it was because of:

```
DEBUG: Cryopod in the Cryogenic Storage could not find control computer!
```

**Comment by lmas** [comment]
[This line](https://github.com/Apollo-Community/ApolloStation/blob/master/code/game/machinery/cryopod.dm#L256) will not return the cryocomputer for some reason, even though the area pointed by `src.loc.loc` (aka Cryogenic Storage area) does have a cryocomputer in it's content list.

**Comment by nullbear** [comment]
Cryo will only store afk bodies if there is no mind attached, otherwise it will ask the player if they want to be cryostored. So oftentimes when you attempt to stick a sleeping body in cryo, they'll still be connected to the server, just inactive, preventing it from happening.

**Comment by lmas** [comment]
I know that already... It's not working.

**Comment by Kwask** [comment]
Fixed in e481a0db592df3a8b3a46742446046a40de004c8

**Comment by lmas** [comment]
the pods worked on a local server, so i think it was an issue with main
server. a clean compile might have fixed it.

also, i dont think the kitchen knife was related to this issue :p

**Comment by Kwask** [comment]
Whoops, meant 6e1638391eb5b1a834cc75a1276d7e68383b8385

**Comment by lmas** [comment]
Thanks.

**Comment by lmas** [comment]
still getting:

```
DEBUG: Cryopod in the Cryogenic Storage could not find control computer!
```

Think it's a mapping thing.

**Comment by Kwask** [comment]
Already tried fixing it via mapping, no luck. Considering there's a discrepancy between local server and host, I think there's something else causing the issue.

**Comment by lmas** [comment]
I got that error on my local server, btw.

**Comment by Kwask** [comment]
Hum, it works on my local server

**Comment by lmas** [comment]
It's a bug with Byond and the `locate()` proc, according to bay12 https://github.com/Baystation12/Baystation12/issues/11785
