### ISSUE TITLE
Suggestion: Paint Reagent Recipe. Clotting agent.

### ISSUE THREAD

**Issue by nullbear** [Apollo-Community/ApolloStation#430]
Paint -> Oil + Clotting Agent. Etc. Color is decided on reaction based on the color of all other reagents in the beaker. Paint can also be resolved into a reagent by grinding crayons (for the respective colors). 

This should allow for more colors of paint, as well, since mixing paints will mix the colors. Grind up a crayon for 20units of paint of a very bold color. 

Oil is black.
Clotting agent is white.
Crayons are red,blue,green,purple,yellow,orange. And can be mixed.

Oil+Clotting agent with no other chemicals present, is grey paint. With excessive oil, is black. With excessive clotting, is white.

Clotting agent -> Aluminum+Silicon+Oxygen. Based on aluminum oxide pigments (hence their use in paint) and this thing i found: https://en.wikipedia.org/wiki/QuikClot

Clotting agent when applied topically, will stop/slow bleeding, and raise temperature, potentially causing burn damage in high doses. When injected, it's quite a bit more dangerous.

Should also be possible to make crayons and candles using plasticide + paint. And to use paint in pens to make colored pens. (syringe->inject or dropper->inject to a pen?) 

Using this, phoron paint would generally be purple. Because phoron + oil + cagent = purple phoron paint. But it would be possible to make other colored phoron paint as well. Such as: red paint + oil + phoron + cagent = redish-purple phoron paint.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=658
