### ISSUE TITLE
Flashlight Sprite(off) not activating

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStation#431]
The code for the flashlight activation will turn the flashlight on and create light. You can then turn off the flashlight and it will take away the light source it is creating, however the Sprite for the flashlight won't update and it will remain as a flashlight(on) even though it is off. Could be fixed by fixing the code to update it when activated.

**Comment by Kwask** [comment]
Fixed in ce4fdf2981284ddc379a20b81e22f30fdbc1dc11
