### ISSUE TITLE
Ghost HUDs broken

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#44]
As a ghost, picking the medHUD and the antagHUD options does nothing.

**Comment by lmas** [comment]
Did a git bisect, turns out the medHUD works up until https://github.com/stuicey/AS_Project/commit/11377c58ae1bd2934f625cd7cbd1a682958d93c3.

https://github.com/stuicey/AS_Project/commit/11377c58ae1bd2934f625cd7cbd1a682958d93c3#diff-95ac0fc852f871a734e18de2185f0990R172 Is the bad line in question.

Ghosts have a life proc too, which renders the medHUD and antagHUD, see https://github.com/stuicey/AS_Project/blob/master/code/modules/mob/dead/observer/observer.dm#L95.

**Comment by stuicey** [comment]
Hopefully fixed in 858485e225e2c73d6676fde12a5fcdbd8a81e76f.

**Comment by lmas** [comment]
Yep, I tried the medHUD and it shows up now. Thanks man!
