### ISSUE TITLE
spider problems.

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStation#445]
- [x] when a spider tries to cocoon a dead spider they will wont stop cocooning and to the point where if you right click the cocoon there will be soo many it can crash you. it happens on certain objects such as dead spiders and dead carp. even beepsky sometimes. this can cause a bit of a problem as cleaning these cocoons up is very difficult.
- [x] also the cocoons have too much health they take forever to break them. makes it hard to clean the station up.
- [ ] another problem with them is the fact that once they see a entity to attack they will go for it and only it forever. meaning someone could walk by then the next person walks in and kill them easily since they wont fight back. makes it to easy to kill the spiders in my opinion.

**Comment by lmas** [comment]
The spider AI could probably need a rewrite. 
An idea is that we could let the spiders check for a new target that's closer than the current target, during each `life()` iteration for the AI. Seems to be a simple fix, but I assume it would be a little too dumb and slow to process (for the CPU, especially if there's a lot of spiders, which happends from time to time).

**Comment by BlueSushii** [comment]
yeah could cause some problems due to the fact if a single spider gets in dorms and makes eggs from the AFK people spiders will be absolutely everywhere. This could slow some things down.

**Comment by Kwask** [comment]
AI in general needs a rewrite so things aren't nearly so dumb

**Comment by rjtwins** [comment]
Spiders should now get a new target if their current one gets out of view range.
They will also switch targets to whoever is closer.

**Comment by CakeQ** [comment]
RJ has fixed target locking
