### ISSUE TITLE
Buff lights

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#448]
With the new lightning system, a lot of light sources could need a boost in their light power. Things like floodlights outputs almost no light.

**Comment by Kwask** [comment]
List of dim lights:
- [x] Floodlights
- [x] Spacepod lights

**Comment by lmas** [comment]
- [x] PDA lights?
- [x] Fairly sure exosuit lights needs some buffing too.

**Comment by ghost** [comment]
- [x]  AI camera lights.

**Comment by lmas** [comment]
- [ ] lanterns, from mining
