### ISSUE TITLE
Spaceacillin doesn't cure mild infections

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#451]
Just happened to one of my patients, overdosed on Spaceacillin trying to cure the infection. The area was bandaged/salved too. Infection kept going and produced a lot of toxins. Not sure if it's just me being worthless with chemistry or actuall bug.

**Comment by BlueSushii** [comment]
Are you sure it was just a infection. They could've caught necrosis or another disease type infection that can't be cured using spaceacillin. Did you try using ointment on it that with spaceacillin usually fixes most regular infections.
I've had that thought the first time I saw necrosis the scan said it was a infection tried to cure it as one and he just kept pouring out toxin damage.

**Comment by Kwask** [comment]
If the infection has advanced too much, spacecillin wont cure it. The only thing you can do at that stage is amputate the limb.

**Comment by lmas** [comment]
Unsure, I haven't played with infections before. All I noticed was his `germs level` was set to 227 for his affected body part.

Edit: The affected limb was the groin so good luck amputating that :D

**Comment by BlueSushii** [comment]
Peroxidone could help it restores infected limbs and can fix internal organs.

**Comment by stuicey** [comment]
Spacicillin isn't meant to cure infections, it slows down the rate of spread in mild infections. However does nothing in more advanced infections were amputation is needed. To cure mild infections repeat a cycle of spacicillin followed by lots of antitoxin.

**Comment by stuicey** [comment]
Spacicillin isn't meant to cure infections, it slows down the rate of spread in mild infections. However does nothing in more advanced infections were amputation is needed. To cure mild infections repeat a cycle of spacicillin followed by lots of antitoxin.

**Comment by lmas** [comment]
My fault then.

**Comment by Kwask** [comment]
Also, regenerative membrane also does a lot to cure mild infections
