### ISSUE TITLE
Duct tape

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#453]
Due to popular requests, let's add some more uses for duct tape:
- [ ] Tape as a weak muzzle.
- [ ] Tape as a weak restraint.
- [ ] Attach notes to people, not just walls.
- [ ] Plug floors and walls when there's a hole in them.

**Comment by BlueSushii** [comment]
We should totally add this. We need the ability to tape a note saying "kick me" on someone's back.
Muzzles would be nice use for it to. Although it would need to  give suffocation damage to unathi as they can't breath though their noses

**Comment by Kwask** [comment]
should also be able to make very weak plating tiles using an entire roll of duct tape, for maximum ghetto repairs :>

**Comment by BlueSushii** [comment]
Yeah because duct tape fixes everything

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=659
