### ISSUE TITLE
New blast doors for engine core

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#456]
As requested by Zer0 The Dragon: http://puu.sh/lXN1p/28e2cafa2c.png
Replace the blast doors for the engine core with the new blast doors that's already being used for pod bays, but with the new sprite Zer0 showed.

**Comment by BlueSushii** [comment]
I would agree those doors would look nicer and would look more natural as it has the radiation danger sign on it.

**Comment by lmas** [comment]
Fixed in 82a69ae8866e787564a738b2fe9340c3460185d3
