### ISSUE TITLE
Messed up computer access

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#460]
Unfortunately, with [this block of code](https://github.com/Apollo-Community/ApolloStation/blob/master/code/game/machinery/machinery.dm#L317) access to the different computers are kinda messed up. 

You must wear a valid access card to open the computer at all and get the popup window.
If you put the card into the computer to authenticate, you won't be able to open the window again until you have a valid card on you again. 
If there's a card in a computer and you have the window open, you can't use the interface since you're not wearing a valid card.

It's a bit hard to explain, but you'll understand what I mean if you try to play around with a computer that requires a card.

**Comment by Kwask** [comment]
Could add a check that returns true if there's a card within the computer

**Comment by BlueSushii** [comment]
Temporarily you can still access it by opening it put your ID card in. Log in. Then right click it eject I'd then open it again. Just a way to get around it for now.

**Comment by Kwask** [comment]
Fixed in 8f65fdfa1ddd1d4a234e287415383579e44ea8b9
