### ISSUE TITLE
Xeno bugs

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#470]
- [x] Xeno embryos doesn't show up on medical scanners.
- [x] People stuck on a xeno nest can still fight any xenos in reach.
- [x] Too easy to break free of a xeno nest?
- [x] Facehuggers can infect people with masks (I think) and hardsuits.
- [x] Neurotoxin damages a target in a hardsuit, bug?
- [x] See #236, can't kill spiders or carp.
- [x] Corrosive acid "melts" energy barriers in podbays.

**Comment by lmas** [comment]
Saw a facehugger do:

```
the alien leaps at Leon Jester's face!
the alien tears the breath mask off of Leon Jester's face!
```

So that might be why they can infect people with masks.

**Comment by BlueSushii** [comment]
When wearing advance hardsuits the suits blocks the face hugger when thrown at you. However they do not block them from latching onto you when you walk past them.

**Comment by halworsen** [comment]
Corrosive acid can take down energy barriers in the podbays.

**Comment by halworsen** [comment]
~~The issue with hardsuits and facehuggers is that the helmets are headgear. Some headgear doesn't cover the face, some do.~~ Nevermind! Apparently there's a `HEADCOVERSMOUTH` bitflag.

Currently, there's a 20% chance that when wearing a mask, the alien won't attach, but I guess it could be nerfed to tearing your mask off and toppling you over, not immediately infecting you.

**Comment by lmas** [comment]
Nice work @Atebite, think you can squash the two last issues too? I'll give you a poorly made medal of approval for your services in spaghetti land if you do.

**Comment by halworsen** [comment]
Sure thing.

**Comment by lmas** [comment]
@Atebite, I am hereby awarding you a Medal of
![Medal](http://i.imgur.com/sWiUZoJ.png)
for solving the xenomorph bugs.

**Comment by halworsen** [comment]
oh my god thank you so much

first of all I'd like to thank my family for supporting me so much but I also want to thank all of you for being there, always, and helping me out. I never would've gotten this far without you, thanks
