### ISSUE TITLE
Cycle between race de-whitelist automagically

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#471]
So we don't have to manually do it ourselves (and risk forgetting to do it). 

Easiest way to do it would be to hard code a race for each day of the week and then simply check, on round start, which day it is and automagically de-whitelist that race for that round (and for the rest of the day, of course).

The harder way is to store the current race and a timestamp somewhere (files, db). On round start we check if the timestamp is over a day/week/month old and if so, cycle the current race and store the variables again.

**Comment by Kwask** [comment]
There's world.realtime which you could calculate what week of the year it is, and then divide what week it is by total number of alien races, and then uses that number to select the corresponding race.

**Comment by lmas** [comment]
Nice, even better. I'll take a look at it.

Edit: Nope, nope I [don't like world.realtime any more](http://www.byond.com/docs/ref/info.html#/world/var/realtime).

**Comment by Kwask** [comment]
just do 

``` DM
var/deciseconds_in_week = 6048000
var/selected_race = (((world.realtime/deciseconds_in_week)%num_of_races)
```

**Comment by lmas** [comment]
That would return the total number of weeks since the "Byond era" aka since 00:00:00 GMT, January 1, 2000.

**Comment by Kwask** [comment]
Yeah, and then you use the modulo (%) operator on it by the number of races, which returns a number between 0 through num_of_races, and use that as your selection

**Comment by lmas** [comment]
Nvm, I missed that last part. Took me waay much longer than anticipated. This is why I don't make new features and should stick with fixing bugs.

**Comment by Kwask** [comment]
eww, it picked catpeople as the first race
