### ISSUE TITLE
New slime types

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#472]
Another popular request. There's some ideas from [King_nexus](https://apollo-community.org/viewtopic.php?f=10&t=139) and someone else wanted some new code for the existing rainbow slime (existing as in there's already a sprite for it).

**Comment by nullbear** [comment]
Like stuff to do with supermatter, for sure.

**Comment by KingNexus0** [comment]
By "someone else" you mean King_Nexus

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=661
