### ISSUE TITLE
Security gets picked for antag roles

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#476]
Thanks to game mode. Someone said security and the captain wouldn't be?

**Comment by lmas** [comment]
Nevermind, looks like it was manually set by an admin.

**Comment by Kwask** [comment]
Sec / captain can get selected by autotraitor, so this is a perfectly valid issue

**Comment by stuicey** [comment]
This is an option in the config, we can turn it off if people want it to be

**Comment by Kwask** [comment]
Yeah, sec / captain aren't supposed to be able to get picked as antag, its not terribly balanced.

**Comment by halworsen** [comment]
Thought it was HoS, warden and captain only that are loyalty implanted?

**Comment by lmas** [comment]
We talked about this the other day and it was said that the whole security force was exempt from antag roles.

**Comment by Kwask** [comment]
There's no loyalty implants, its just that security / captains have had extensive background checks. Plus gameplay wise, it's bad to make sec traitors because then A. they're incredibly powerful from the get-go and B. people will be less willing to trust sec / captain

**Comment by Kwask** [comment]
To add to this, borgs can also be chosen as traitor

**Comment by Kwask** [comment]
Fixed in 18b364bba36a01a2e0e9ea8fec1dc36e8a1e273b
