### ISSUE TITLE
Player trophies

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#478]
I've been wanting to extend the account items and make them more publicly shown as I think it's a really cool system for adding more customisations to the characters and for showing off as throphies.

The problem I've had with them though, is that they seem to be mostly unknown and rarely shown in the game. I guess it's because we haven't really released that many items yet, but still. How about making them more publicly shown? Kinda like achievements I guess, which is a really silly thing in games now a days. But it's still a cool thing for well behaved players to show off and let everyone know they're not just another plebeian.

I've also been wanting to utilize the players tab more. What if we could tie in the account items with the players tab? We could show the account items as tiny icons after the player ranks in the list, with titles and descriptions for when you hover over them with your mouse.
The problem is there's not much horizontal space in the list though, so we can't really shown that many icons if we would use the same icon size as the current rank icons.

I would also like to add a new string column to the account items SQL schema, used for giving a reason for why a player got that account item.

**Comment by Kwask** [comment]
I've always wanted an achievement system, and I think a lot of other players would like that too. This would be a good step towards that.

**Comment by ominousbrainworm** [comment]
I slashed a alien queen to death in a breacher suit can I get a achievement for that.

**Comment by lmas** [comment]
As an example of a trophy, I have issued one in #470.

**Comment by ominousbrainworm** [comment]
Can I have a medal for maybe being the first person to punch a xenomorph to death! Using no weapons.

**Comment by stuicey** [comment]
As a side note, trophies achieved could be selected and added to player listing - like how admins and mods have an icon currently. It would probably be best to keep those sprites around <20x20 so they are clearly not resembling admin/mod ones.

**Comment by lmas** [comment]
Yep, that's exactly what I had in mind.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=662
