### ISSUE TITLE
Grabs can be put into lockers

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#479]
apparently

**Comment by valzargaming** [comment]
Wow. This should definitely not be a thing. Not even sure how to code a fix for that. 

What did you do to replicate this? By definition, clicking a locker with someone grabbed should put that person in the locker, not the grab.

**Comment by halworsen** [comment]
Exactly that. Grab someone, click on locker => grab is placed in the locker.

**Comment by stuicey** [comment]
Doesn't seem to exist anymore
