### ISSUE TITLE
Can't pick whitelisted race

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#484]
This week's race is tajaran, which you can't pick.

**Comment by lmas** [comment]
Just tried it again, this week was Unathi which I could successfully pick.

**Comment by Kwask** [comment]
would not complain if this only affects tajarans :^)

**Comment by lmas** [comment]
Whew whew whew! Did someone just hate on tajarans? That's racism bro! I'm PC bro, I'll unwhitelist tajarans.

**Comment by stuicey** [comment]
Didn't know there were other PC people in town. I remember trying this when it was Tajaran week and it worked perfectly for me. Likely a false report by the guy who was saying he couldn't pick the race.

**Comment by lmas** [comment]
Jokes aside, besides me there was a bunch of other guys not being able to pick it.
