### ISSUE TITLE
Bed issue

### ISSUE THREAD

**Issue by Lucien93** [Apollo-Community/ApolloStation#489]
Last round I tried pulling on a roller bed that had someone buckled to them and I could only pull the bed. With the person still buckled to it staying in the same tile.

**Comment by Kwask** [comment]
Marking as medium since it could lead to someone not getting the treatment they need

**Comment by Lucien93** [comment]
Actually, I have to restate something. The bed I pulled was not a roller bed, it was a normal bed from the patient room. The ones that have blankets on them. Roller beds work fine.
I have no idea why I wrote it was a roller bed.

**Comment by Atebite** [comment]
Medium > low, I've never seen someone drag regular beds around.

**Comment by stuicey** [comment]
From what I'm aware regular beds are anchored to the ground.
