### ISSUE TITLE
Add slot-grabbing

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#492]
Instead of having to click on the item itself in your HUD, you could just click anywhere on its slot to grab it. Useful for grabbing small items out of your bag.

**Comment by halworsen** [comment]
Problem with storages

The entire thing (all the slots) is one single object, so I'm not sure how you'd figure out which slot you're clicking.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=663
