### ISSUE TITLE
Aliens take damage by Phoron

### ISSUE THREAD

**Issue by valzargaming** [Apollo-Community/ApolloStation#495]
What happens:
Aliens can not regenerate Phoron storage while in a Phoron atmosphere.
Aliens take damage to exposure to Phoron storage.

What should happen:
Phoron atmosphere should regenerate Alien health.
Phoron atmosphere should replenish Phorom storage.

**Comment by halworsen** [comment]
Stu already fixed aliens taking damage from phoron in 34449d8

**Comment by valzargaming** [comment]
So we thought. However, the damage being dealt by skin burning at the time was 5, so it wasn't enough. My first pull request changed the burn_skin damage from 5 to 0.75 while my second pull request changed adjustFireLoss(-1) to adjustFireLoss(-1.75) to compensate for the differences. This should resolve the issue, but will not remove the debug logs to notify the user that their skin itches, burns, blisters, and peels. The damage was also preventing aliens from generating phoron.
