### ISSUE TITLE
Gamemodes not properly spawning antags

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#499]
Mercenary / Heist are the two known ones. On a merc round start, the mercs are just crewmembers who have been teleported to the merc based. They dont have any merc gear and are all on the crew manifest.

Heist rounds they're vox at least, [but are still equipped with their crew gear](http://imgur.com/N4DEpy6), and are still listed on the crew manifest.

Pretty hilarious, but still makes these gamemodes unplayable.

**Comment by stuicey** [comment]
Fixed in 0.3
