### ISSUE TITLE
Bone repair surgery always fails

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#500]
Every time you try to use the bone gel to repair the bones, it just breaks them further.

**Comment by halworsen** [comment]
You sure? I was able to mend a broken groin about two days ago.

**Comment by stuicey** [comment]
The area has to be at 100% heath or the surgery will fail

**Comment by lmas** [comment]
I've been told the same, if it's not healthy it will rebreak the bones. We should probably change that, it's confusing and just annoying.

**Comment by Dragarien22** [comment]
That's nothing new.
