### ISSUE TITLE
del() woes

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#501]
Edit: See https://github.com/Baystation12/Baystation12/issues/11674 for more.

`del()` has been replaced by the much better `qdel()` (for garbage collection reasons I think) and so there's a lot of lines that needs to be changed to the new proc. Note that `del()` is still required in some places, so it's not just as simple as replacing all `del()` with `qdel()` on a global scale.

I've hooked up `del()` with another proc (`generate_debug_runtime`) that will generate a stack trace in the runtime logs whenever `del()` is incorrectly called, which gives a list of procs run up until `del()` was called and should help you in tracking down the faulty `del()` line. 
(There's also some bug with `generate_debug_runtime` so it won't be called each time, sometimes...).

Find these lines and either fix them or report them here.
I'll start:
- [x] /obj/item/projectile/beam/stun
- [ ] ~~/obj/item/device/flash/synthetic~~
- [ ] ~~/obj/item/clothing/suit/fire/firefighter~~
- [ ] ~~/obj/item/device/mmi~~
- [ ] ~~/obj/item/device/mmi/radio_enabled~~
- [ ] /obj/item/device/spacepod_equipment/engine
- [ ] /obj/item/device/spacepod_equipment/misc/cargo
- [ ] /obj/item/device/spacepod_equipment/misc/tracker
- [ ] /obj/item/device/spacepod_equipment/shield
- [ ] /obj/item/device/spacepod_equipment/weaponry/burst_taser
- [ ] /obj/item/device/spacepod_equipment/weaponry/taser
- [ ] /obj/item/mecha_parts/mecha_equipment/anticcw_armor_booster
- [ ] /obj/item/mecha_parts/mecha_equipment/antiproj_armor_booster
- [ ] /obj/item/mecha_parts/mecha_equipment/generator/nuclear
- [ ] /obj/item/mecha_parts/mecha_equipment/repair_droid
- [ ] /obj/item/mecha_parts/mecha_equipment/tesla_energy_relay
- [ ] /obj/item/mecha_parts/mecha_equipment/tool/drill/diamonddrill
- [ ] /obj/item/mecha_parts/mecha_equipment/tool/syringe_gun
- [ ] /obj/item/mecha_parts/mecha_equipment/weapon/ballistic/missile_rack/flashbang
- [ ] /obj/item/mecha_parts/mecha_equipment/weapon/ballistic/scattershot
- [ ] /obj/item/mecha_parts/mecha_equipment/weapon/energy/ion
- [ ] /obj/item/mecha_parts/mecha_equipment/weapon/energy/laser
- [ ] /obj/item/mecha_parts/mecha_equipment/weapon/energy/laser/heavy
- [ ] /obj/item/mecha_parts/mecha_equipment/weapon/energy/riggedlaser
- [ ] /obj/item/mecha_parts/part/ripley_left_arm
- [ ] /obj/item/mecha_parts/part/ripley_left_leg
- [ ] /obj/item/mecha_parts/part/ripley_right_arm
- [ ] /obj/item/mecha_parts/part/ripley_right_leg
- [ ] /obj/item/mecha_parts/part/ripley_torso
- [ ] /obj/item/pod_parts/armor/command
- [ ] /obj/item/pod_parts/armor/security
- [ ] /obj/item/pod_parts/armor/shuttle
- [ ] /obj/item/weapon/cell
- [ ] /obj/item/weapon/cell/high
- [ ] /obj/item/weapon/cell/super
- [ ] /obj/machinery/door/poddoor/filler_object
- [x] /obj/effect/decal/cleanable/liquid_fuel

**Comment by valzargaming** [comment]
I'll be keep an eye on how this works as garbage collection on anything that doesn't touch any of the processing loops has been observed to do weird things. It's safest to do this on particles/effects/construction parts/fuels/non-nested items first before we start touching things like vehicles and items.  
For now it looks like only pod_parts, weapons, and poddoor may or may not cause unpredictable problems to occur. Let me now when we start to merge this.
