### ISSUE TITLE
People can send empty chats

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#502]
This affect IC chat at least, I think you can send empty messages in OOC too. Really anoying.

**Comment by stuicey** [comment]
You sure, sanitize proc which is called on both IC chat and OOC should filter this out. If it is the case, it must be some non printable character getting through.

https://github.com/Apollo-Community/ApolloStation/blob/master/code/__HELPERS/text.dm#L27

**Comment by lmas** [comment]
That line you highlighted is completely useless, you could simply send a line of spaces and it would pass that check. Just add a trim before it and we should be good.

**Comment by runedog48** [comment]
I can't even reproduce this.

**Comment by halworsen** [comment]
You can't send empty messages in OOC, IC, deadchat or msay, at least. You can do it in donsay, though.

**Comment by lmas** [comment]
Alright, did you try some weird and invisible unicode symbols? I haven't tested it myself, but I've seen other people do it recently.

**Comment by GutsySS13** [comment]
hold alt and type 255 on your numpad for an empty looking character

**Comment by nicemoreoften** [comment]
What Gutsy said is right: Here's an example:

**Comment by nicemoreoften** [comment]
‮‮‮‮

**Comment by valzargaming** [comment]
So it's technically a unicode character then? Pretty sure that's not a bug.

**Comment by stuicey** [comment]
Byond doesn't understand unicode by default and translates it into "?"s or other strange characters.

**Comment by stuicey** [comment]
Never seen any evidence of this ICly
