### ISSUE TITLE
Buffing Library (suggestion)

### ISSUE THREAD

**Issue by minutekiwi** [Apollo-Community/ApolloStation#506]
Making Library a lot less of a pain to do would be nice.
At the very last, adding support for a "mass order" would be really helpful. Let me order a bunch of books at a time, and they can print whenever able. To pair with this, letting the barscode scanner work on entire bookcases (so I can add an entire bookcase of Fiction books to the General Inventory) would be a big help.
Other nice things (not nearly as necessary) would be things like making book stacks (maybe able to carry like 5 or so books in one hand?) so they don't take up so much space when trying to put them away. 
Not sure if possible, but also the ability to preview a book before printing it on the computer would be nice too.

For people who mark this as low/high priority, this is extremely low priority. But yeah. Would be nice.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=664
