### ISSUE TITLE
Equipping Items to Belts

### ISSUE THREAD

**Issue by ChaosTheory1** [Apollo-Community/ApolloStation#513]
This suggestion is entirely for Hotkey users. If your pockets aren't full and you have an item in-hand that can fit, CTRL+E should add said item to either pocket. If your pockets ARE full, you have a belt equipped, and you have an item in-hand that can fit on a belt then CTRL+E should add said item to your equipped belt.

**Comment by Kwask** [comment]
Could also add CTRL+B to place things in your backpack

Or maybe the default E hotkey could just be expanded to fulfill all of these, so it does the usual to place the object in its appropriate slot. If that doesn't work, try pockets, belt, suit slot. If that doesn't work and there is a belt equipped, try belt. If that doesn't work and there's a backpack equipped, try backpack.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=665
