### ISSUE TITLE
Pipes don't connect correctly in templates

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#515]
Some pipes seem to disappear entirely, even.

Example:
In DM
![idm](http://i.imgur.com/88v4mlw.png)

In-game
![ig](http://i.imgur.com/U4gamkF.png)

**Comment by halworsen** [comment]
Might be caused by the order that things are inserted in. I think it's moving upwards, filling out rows from left to right.

Still, that's a bit weird, considering how the pipe directly right of the phoron tank poofed.

**Comment by Kwask** [comment]
There's a way to pause recalculating these things I think. If you could make it do that until it finishes loading in the whole template, it should work.

**Comment by halworsen** [comment]
Pipes get deleted in their initialize proc. Dunno why the others aren't connecting properly yet, but this is a start.

**Comment by halworsen** [comment]
~~For some reason, pipes already on the station (e.g. ![AI chamber](https://vgy.me/RhLX0x.png) (AI chamber)) get initialized when templates are placed????~~ Other objects take the reference of the deleted pipe

Pipes are also looking north/south for node candidates when initializing, even though their nodes are facing east/west.

Something to do with directions/initialization directions (not being set properly)? I think it might be the case, since pipes going north/south seem to be connecting fine, for the most part.

EDIT: I'm placing my bet on this! Pipes that have dir = 4 in the map maker end up having dir = 2 in New, which gives the pipe the wrong initialize_directions.

EDIT 2: Visible pipes are fixed! For some reason hidden pipes are still broken (they seem to get "unwrenched" before they even have a chance to initialize)

**Comment by halworsen** [comment]
Fixed in a91950a
