### ISSUE TITLE
Filter Records in Medical/Sec/Employment Computers

### ISSUE THREAD

**Issue by minutekiwi** [Apollo-Community/ApolloStation#516]
Something to make it easier to use would be to filter records in those computers.
Some filters that'd be nice!:

> By Department: Civilian, Sec, Med, etc
> By Blood-type (For Detective, probably, and also med)
> By Presence of Notes (REALLY nice for Med especially, makes it easier to see if any crewmembers have a prescription roleplayed in or something)

Not sure if this could be done, but it'd be cool if able.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=666
