### ISSUE TITLE
Can't create a new APC after the old broken one was removed.

### ISSUE THREAD

**Issue by Lucien93** [Apollo-Community/ApolloStation#521]
This happened in a round where I was CE, all of telecomms exploded, and when I was trying to rebuild it, I saw the APC was broken and unusable.
I hacked at the cover until it came off, took out the power unit, cut the cables, took out the broken power card and then unlwelded the frame. 
When I tried to attach a new frame to the wall, it just said "there's already an APC in this area." I couldn't build a new APC there for the rest of the round.

**Comment by Lucien93** [comment]
Notable things I did: I hacked at the cover with many different tools.
I tried putting a power card in the unusable frame. 
After it told me I couldn't, I unwelded it from the wall.
I wasn't clear on how to get the cover off, so it took me a while until I understood I was just supposed to hit it till it fell off.

**Comment by KingNexus0** [comment]
Might also be noteworthy that it gives the same message no matter where you're trying to build an APC. I used the station blueprints to set a new room in space and got the same message.

**Comment by valzargaming** [comment]
What area did this occur in? If it was off the main Z-level it might be an area code issue as I cannot replicate this on the main station.

**Comment by Lucien93** [comment]
It was under the main Z level, at telecomms. Under engineering.

**Comment by rjtwins** [comment]
I know this issue has been on the tracker for some time but I wanted to give and update/twist to it.
I have been able to replicate it, namely somebody blew up the SMES in the west corridor and the APCs in the area with a bomb. I could not place new APCs even tough they had been completely destroyed. It gave me the messensage this area already has an APC. Another issue I have run into, ant this is probably related, is that when you build a new room and add it to the station via the chief engineers blueprints and try to place an APC there it will also refuse and give you that message. Furthermore this is also the case when you try to install APC;s in the derelict station near the engineering outpost. I hope this sheds some new light on this issue and possibly gets it fixed.

**Comment by rjtwins** [comment]
Just fixed this myself, pr in now.
