### ISSUE TITLE
Escape pods don't work

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#53]
The escape pod doors don't open when the escape shuttle docks. In order to get in you have to hack the airlock doors.

**Comment by Kwask** [comment]
Is this also true for when the emergency shuttle arrives? I think it's expected behavior for them to not open on crew transfers.

Also, knowledge of whether this is the case for all pods or just one specific one

**Comment by halworsen** [comment]
It's for all pods, but I think you might be right that they only open for emergency shuttles. Opened for me now (emergency shuttle).

My bad.
