### ISSUE TITLE
Users are able to make votes when the round hasn't started

### ISSUE THREAD

**Issue by runedog48** [Apollo-Community/ApolloStation#532]
Title.

Already fixing, just making this for eh.. "paperwork" reasons.

**Comment by lmas** [comment]
~~Hey think you can disable the votes for when a shuttle is on the way too? See #446~~ Nvm, I see you found it already.

**Comment by stuicey** [comment]
Also, could you let admins still be able to call these regardless of ticker state. Useful if people pick a stupid mode or something.

**Comment by runedog48** [comment]
Funny you said that stuicey, I was actually adding an admin override and decided just to leave it out.
