### ISSUE TITLE
Electricity doesn't hurt people

### ISSUE THREAD

**Issue by KingNexus0** [Apollo-Community/ApolloStation#535]
Shocked doors, hacked machines, etc., do no damage to a player without insulated gloves. It has been this way for some time. The only way someone is shocked is if they accidentally click a powered wire or electrified grille.

**Comment by runedog48** [comment]
Bumping into / attacking grilles does shock the user, however airlocks are not shocking. Haven't tested machines yet. Gotta go to bed, so I'll get to it first thing tomorrow.

**Comment by runedog48** [comment]
This is officially a pain in the ass to fix. Almost got it.
