### ISSUE TITLE
Rat King bugs

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#541]
- [x] Only hugs people
- [x] Can use most of his abilities after death
- [x] Chews open 0 access doors
- [x] Can pick up items

**Comment by lmas** [comment]
I think we might need to come up with a better way to disable any game related verbs for dead mobs. 
Maybe have to refactor all verbs so they follow a common "practice" and categorize them better, ie:
- Group all ingame verbs into group "Game" and disable this group for dead mobs.
- Group all ghost verbs into group "Ghost" and only enable the group for ghosts.
- Group all admin verbs into "Admin" etc.

I'm not too familiar with the verbs code, but what little I've seen from it a verb can be written in different ways which affects how they are called, ie:
- Player mobs automagically gets a list of verbs added to them on creation.
- Some admin verbs are added to the admin panel on admin login.
- Some other verbs are not added to a panel and can only be typed (like `.getruntimelogs` and `.ping`).

It's all very confusing and could really need an overhaul to clean things up.
