### ISSUE TITLE
Species suggestions.

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStation#542]
Trading though the lord on all the different kinds of species. I have come up with some cool things that maybe could be added into the game. These are just to maybe make the species a bit more unique from the human race.

Skell. 
Due to closely resembling a jelly fish and some back stories say when they are in danger or dieing a skell, will secrete a poisonous substance the on contact will poison the other creature. Fatal upon eating.

Unathi. 
Should be able to earn more nutrients from eating raw meat then normal due to their carnivorous habits. Since currently eating raw meat gives you next to nothing.

Dinoea. 
Upon death adult dinoea corpses should be harvestable for wood when hit by a hatchet. Due to their treelike nature.(due to the adults splitting maybe the nymphs could produce wood.)

Tajaran.
(Couldn't think of anything at the time, I'll edit something in.)

**Comment by Kwask** [comment]
Dionae corpses split apart on death, releasing several nymphs, so there's not much of a body to chop.

**Comment by nullbear** [comment]
could give foods/reagents different tags such as 'meat' 'vegan' 'dairy' etc. specifically for adjusting nutrient value to species, and making food poisoning easier. Such as a vegetarian species gettign food poisoning from any 'meat' tagged food.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=668
