### ISSUE TITLE
Bluespace and SpacePods

### ISSUE THREAD

**Issue by stuicey** [Apollo-Community/ApolloStation#544]
Space pods are constantly getting stuck in bluespace for indefinite amounts of time.

**Comment by runedog48** [comment]
Needs the "Pain in the ass" label.

**Comment by stuicey** [comment]
Adding urgent since this is hands down the most annoying bug

**Comment by runedog48** [comment]
I can't find out how to fix it,  but I can check to see if it failed and attempt to teleport them until they get there

**Comment by stuicey** [comment]
likely it is some bug with the bluespace teleport code - I remember modifying the end of it to stop humans getting trapped there and building houses.

**Comment by valzargaming** [comment]
Ehehe, can vouch that I have tried to do that before. Turns out it's rather hard to maintain life inside of bluespace.

**Comment by Kwask** [comment]
Fixed in 41785f39ebf9c979a6c676c2c3e50ed4a2a8e136
