### ISSUE TITLE
Catametallic Alloy doesn't stack when using machinery

### ISSUE THREAD

**Issue by runedog48** [Apollo-Community/ApolloStation#549]
Stacking machine in mining?
Or ore processor.

Working on this already, Is there a way for me to add my own labels?

**Comment by halworsen** [comment]
Not entirely related, but the ore processor needs to be rewritten a bit. Plasteel is supposed to be platinum + metal, but the ore processor still makes it with phoron.

**Comment by runedog48** [comment]
#550 
Will do ~~shortly~~ eventually :<
