### ISSUE TITLE
Heat Exchange pipes delete themselves when wrenched

### ISSUE THREAD

**Issue by NijiShadow** [Apollo-Community/ApolloStation#551]
You can wrench as many of them in the same place, even without pipes around. They just go poof.

**Comment by Kwask** [comment]
Is this wrenching them in place? Also are they fully gone or does their icon disappear?

**Comment by halworsen** [comment]
I blame 25b2608

Basically, you can wrench pipes in place anywhere, even if they're not connected to another pipe. That, in turn, makes them get deleted.

**Comment by valzargaming** [comment]
I'm not seeing anything in [25b2608](https://github.com/Apollo-Community/ApolloStation/commit/25b2608789843fcdc250400a897be35dead96cb3) that would be causing this issue as the only changes to unary were sanitary. I'll take a look into this.

**Comment by halworsen** [comment]
Just a wild guess, since that's the last time I saw someone touch any atmos-related code.

**Comment by valzargaming** [comment]
It looks like the decision on deletion happens in he_pipes.dm relating to node1, node2 where  
if(!node1 && !node2)
            qdel(src)
            return  

Is this issue occurring with all heat exchange pipes? Last time I checked these need to be attached first to a normal pipe before they are able to be placed. If it is happening regardless, then node1 and node2 are not being properly notated. I've only ever touched atmospherics when it comes to the processing loop.

**Comment by valzargaming** [comment]
[Tested and could not reproduce, verified proper functionality](http://puu.sh/mATNi/bf41039a57.png)  
This can be closed.

**Comment by halworsen** [comment]
Because you're connecting it to a valid pipe node. For example, it'll disappear if you wrench it down in the middle of an empty 3x3 room, or to the right of a connector port facing up. Also, this bug happens to pipes in general.

**Comment by valzargaming** [comment]
I suppose we could just remove the qdel(src). Then it would just stay on the ground without being wrenched into oblivion.
