### ISSUE TITLE
Items can get dropped into spacepods

### ISSUE THREAD

**Issue by runedog48** [Apollo-Community/ApolloStation#559]
And the items are stored in its contents, which cannot be accessed.

**Comment by rjtwins** [comment]
I've done some testing and the only way something can get stuck into the pod is if somebody SSDs inside it. If you are in the pod you cannot dorp items in your hands. If you exit the pod you will stand on top of the icon if you drop something then it lands under the pod. If you trow something ad the pod it bounces off. If you drag something onto the pod (mouse drag) or click on it with and item and the pod has a cargo hold it gets added to the cargo of the pod. Wich can be jettisoned by the pilot. I've found no way to "drop" items into the space pods in a way they can get stuck. Closing this issue.
