### ISSUE TITLE
Blackhole grenades locks character movement

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#56]
And doesn't let go when it goes out. I think.. Or it stuns you for a looong time or something

**Comment by Kwask** [comment]
hmm, that, uhh, ain't good

The grenade is suppose to stun people for 1-5 seconds when it goes off, not sure why it locks people though

**Comment by Kwask** [comment]
Found out Stun() stuns for seconds, not deciseconds, fix'd in f5f02d1758c9c60e385533b28a75407a1dced97f
