### ISSUE TITLE
Glass tables don't break while being walked on

### ISSUE THREAD

**Issue by Hate9** [Apollo-Community/ApolloStation#560]
When climbed onto, glass tables crack (the first time) and break (the second time), but when walked on, they do neither. Not major, but it /should/ get fixed eventually.

**Comment by BlueSushii** [comment]
Adding to this issue once the table is broken the Sprite for glass table parts is either not made or is just invisible.

**Comment by runedog48** [comment]
I worked on this a little, but I couldn't find an efficient way to check if someone is walking on the table.

**Comment by stuicey** [comment]
Bit of a cheaty fix, but you could add : 

```
    spawn(/*interval*/)
        if(istype(get_turf(src),/obj/structure/table/glass)
            /* break table */
```

Maybe break the whole table instead of just one piece too?

**Comment by Kwask** [comment]
Crossed() is a proc that gets called any time one object moves onto another. Just have the table check if the crossed object is a mob, and have a chance to break if it is
