### ISSUE TITLE
Random job allows alien heads of staff

### ISSUE THREAD

**Issue by stuicey** [Apollo-Community/ApolloStation#562]
Create a list of blacklist jobs for each alien race and stop them joining the round as that job.

**Comment by BlueSushii** [comment]
By aliens do you mean Xenomoprhs or species alien such as Skrell,Unathi and Wryn? Is this supposed to stop the other species from becoming heads?

**Comment by stuicey** [comment]
Station aliens such as wryn or tarj becoming a head of staff. This is suggesting to blacklist specific jobs from races that make no sense such as a CMO unathi.

**Comment by Kwask** [comment]
IPCs aren't supposed to become heads either, because NT treats all synthetics like pieces of equipment.

**Comment by BlueSushii** [comment]
Does this mean non humans cannot be heads? I'll be a bit upset if my unathi can't be HOS anymore. Or are they just restricted from certain jobs?

**Comment by Kwask** [comment]
No, it means certain species can only be certain heads.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=669
