### ISSUE TITLE
Dying as a nucleation allows you to respawn instantly

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#563]
Probably has something to do with time of death not getting set properly.

**Comment by stuicey** [comment]
its because timeofdeath is stored on the mob, so when the mob is deleted timeofdeath is also removed

**Comment by GutsySS13** [comment]
leave their head so they can be cloned?

**Comment by Kwask** [comment]
It doesn't store time of death on the ghost? Also @ gutsy, nucleations aren't supposed to be cloneable

**Comment by valzargaming** [comment]
Can we implement a fix by changing respawn verb to not allow respawn if time of death is null or 0 and add time of death to a reference to the ckey?.

**Comment by Kwask** [comment]
If we changed the respawn verb like that, then people who die as nucelation would never be able to respawn. I am almost certain time of death is set on the ghost, and is failing to do that in this situation. If time of death is tied to the dead mob as @stuicey said, then anyone who is gibbed would be able to respawn instantly as well.

**Comment by stuicey** [comment]
This issue also effects rats ghosting then re-spawning instead of the 5 min timeout.
