### ISSUE TITLE
The random Artifact rooms on the asteroid no longer spawn.

### ISSUE THREAD

**Issue by mewseht** [Apollo-Community/ApolloStation#564]
I have scanned the entire asteroid as a ghost multiple times, over multiple rounds, and am confident to say that the artifact rooms are no longer spawning.

**Comment by lmas** [comment]
Yeah old bug. Rooms disappeard with the new asteroid map I think. Hopefully it's just some missing area that prevents spawning new rooms or something like that.

**Comment by stuicey** [comment]
The z-level might be hard coded

**Comment by lmas** [comment]
I'm fairly sure I fixed the zlevel when I fixed the mining turf generation, but yeah better to check that again.

**Comment by stuicey** [comment]
Fixed in 0.3 - they don't spawn in random asteroids
