### ISSUE TITLE
Atmos tech can't use pipe dispenser

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#570]
Reported by mongoon. Medium for preventing atmos doing their job.

**Comment by valzargaming** [comment]
Probably related to https://github.com/Apollo-Community/ApolloStation/pull/556. It's checking for access to both atmospherics AND toxin storage. Since this works on a declaration based on calling a list, I'm going to remove the requirement for access_tox_storage.

**Comment by Kwask** [comment]
Fixed in 8c8535109451791305af4c7a5600c0d9ce107d29
