### ISSUE TITLE
Chugging Drinks

### ISSUE THREAD

**Issue by minutekiwi** [Apollo-Community/ApolloStation#574]
Clicking and dragging a drink (or some other kind of system) on yourself should let you chug it.

Why? Why not.

**Comment by valzargaming** [comment]
Interesting proposal. How many units should you drink by chugging instead of the standard 5? The whole thing?

**Comment by minutekiwi** [comment]
I _THINK_ standard glasses hold 30 units. So, probably 15 per each chug.
