### ISSUE TITLE
Deleting walls and tables deconstructs them

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#575]
Deleting walls turns them into girders + drops metal insteading just deleting the object.

Tables also do this and drop table components instead of disappearing

**Comment by stuicey** [comment]
Haven't checked, but it's likely that wall.del intentionally creates these

**Comment by lmas** [comment]
Don't forget the tables.

**Comment by stuicey** [comment]
I think this is a non-issue.
