### ISSUE TITLE
Changelings can farm monkeys

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#577]
If a changeling gets hold of a box of monkey cubes, they can farm the monkeys for massive points.

**Comment by valzargaming** [comment]
Alien Queens can also go to Xenobiology and use them for facehugger fodder.

**Comment by minutekiwi** [comment]
Maybe try setting a hard limit on how many monkeys a changeling can farm? Makes it still viable in a pinch, but not something to depend on. IC reasons could be something along the lines of "You have nothing more to gain from this creature", so they require human DNA past a certain number of points.

**Comment by Kwask** [comment]
I think they shouldn't gain anything from absorbing monkeys, because it encourages boring antags.
