### ISSUE TITLE
Flash Bangs

### ISSUE THREAD

**Issue by scubadave** [Apollo-Community/ApolloStation#579]
The only way security can avoid getting flashed is to use earplugs and glasses but, in order to use ear plugs the coms piece has to be removed. This seems to be more trouble then its worth please look into this.

**Comment by valzargaming** [comment]
The ear plugs as a concept seems a little silly to me, considering everyone in the game wears headsets. If that had to be a thing, I'd give security special headsets that double as earplugs against flash bangs.

**Comment by stuicey** [comment]
I like the idea of security having to prepare and think out their plan before just jumping into the action. 

Personally I think flashbangs are overpowered, and making security invulnerable to then would just make it worse.

**Comment by Kwask** [comment]
Yeah, sec isn't supposed to be the catch-all, able to overcome any foe. Each tool they use needs to have its own drawbacks. 

If you look at how flashbangs are used in real life, you'll see not something you just pop when you're in trouble. It's something used to incapacitate an entire room.

**Comment by JMMJ01** [comment]
This is a bit late to the party, but the whole point of a flashbang is to toss it into a room, THEN enter and clear it while they are down.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=670
