### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by Fofofo21** [Apollo-Community/ApolloStation#580]
http://prntscr.com/9uuooz

It should be Name is trying to preform CPR on Name! rather than
Name is trying perform CPR on Name!

**Comment by halworsen** [comment]
[Perform](http://www.thefreedictionary.com/perform) is correct.

**Comment by valzargaming** [comment]
... I'm pretty sure that proper grammatical usage is "is trying to perform."
Damn it Atebite, don't close stuff at 3 in the morning without understanding what you're reading. The message is missing the "to" in the sentence.

**Comment by halworsen** [comment]
more like 7 in the morning but o k i'll take it
