### ISSUE TITLE
Add colours to interface buttons

### ISSUE THREAD

**Issue by stuicey** [Apollo-Community/ApolloStation#594]
Talked about in community meeting - adding colours to Wiki/Forum/Rules buttons at the top right.

Suggested : We use light colours so it isn't harsh on the eyes but is easily recognisable
Wiki - sky blue
Forum - light orange (kwask orange)
Rules - light purple

**Comment by Kwask** [comment]
Added in 8d45076f4e455efd0e78afac4dda40167645af8d
