### ISSUE TITLE
Drop-down menu is View Variables is inaccessable to Mods

### ISSUE THREAD

**Issue by minutekiwi** [Apollo-Community/ApolloStation#597]
I don't know if Stuicey already fixed it, but I forgot exactly how he said it. Basically, by default mods can't Fix Nano-UI and the like from the View Variable menu. I think it has something to do with how it's assigned to the wrong flag.

**Comment by stuicey** [comment]
From what you said it checks for +DEBUG instead of +ADMIN.

**Comment by halworsen** [comment]
I'll make Fix NanoUI available to mods. Reopen if you need more
