### ISSUE TITLE
Polyacid can just be splashed on the floor

### ISSUE THREAD

**Issue by runedog48** [Apollo-Community/ApolloStation#601]
Perhaps it should destroy the floor tile and cause damage to the underlying plating?
Same for the poly smoke

**Comment by stuicey** [comment]
Should just do the circular explosion damage effect on a floor tile. Wouldn't want a silly chemist to be able to space the whole of medbay.

**Comment by runedog48** [comment]
It shouldn't delete the underlying plating unless it has multiple exposures to the polyacid. The first time it should delete the floor tile and damage the plating
