### ISSUE TITLE
Last words succumb

### ISSUE THREAD

**Issue by minutekiwi** [Apollo-Community/ApolloStation#606]
This is something that another server I played on had.

When in crit, instead of just being able to succumb, you also had the option to use Whisper. Basically, you'd whisper your last words, and then succumb right after.
(For bonus points, it'd be neat if you could hear if people were in whisper distance instead of just passing out and not hearing anything. But I don't know if that's possible.)

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=671
