### ISSUE TITLE
chem dispenser

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStation#608]
in chemistry the chem dispenser recharges at a insane slow speed, once you drain it, they will take forever to recharge and really slows down production and as a chemist you start to get bored, I suggest we increase the speed at which they recharge for the sake of medbay.

**Comment by Kwask** [comment]
I've personally never had an issue with the recharge rate. It feels balanced to keep chemists from making unlimited chemicals.

**Comment by minutekiwi** [comment]
I can agree and disagree here. The two machines are perfectly balanced enough to where making all of the necessary medication is viable and still keep a good supply.
More so than a recharge rate, maybe we should allow robotocists or engineers to come in and supercharge them? That way they need a reason to have it charged or else it'll look suspicious.

**Comment by Kwask** [comment]
Pretty sure if engineers upgrade the capacitors in the machines, they recharge faster

**Comment by BlueSushii** [comment]
Closing ticket as this has been talked about in a meeting, no longer needed.
