### ISSUE TITLE
Attach prescription glasses to HUDs and Scanners

### ISSUE THREAD

**Issue by minutekiwi** [Apollo-Community/ApolloStation#609]
Brought up in the forums. A way to make using HUD and glasses together viable.

HUD in hand, click on your glasses, and then something like "You attach the HUD to your prescription glasses" comes up. Keeps the benefits of the glasses and you can use equipment you need.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=672
