### ISSUE TITLE
A nerf idea for unathi.

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStation#611]
I think that since unathi are soo robust and deadly I felt like coming up with a nerf for them that relates to their biology. And I came up with this. Unathi have very long and sharp claws. I feel like those would get in the way of some actions. Such as, if a unathi is delicately placing wire into a mech while building it there could be a chance where they would accidentally cut the wire and shock themselves with it due to their sharp claws. Or whenever a unathi is dragging someone there could be a chance their hands would slip resulting in them cutting the flesh of whomever they are dragging. 
These are just some ideas.

Was discussed in community meeting.
Unathi would no longer be able to use guns do to their lore. and would get burned sometimes if messing around with some tasks.
would get their natural scale armor implemented.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=673
