### ISSUE TITLE
Ending up on z level 1.

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStation#624]
Under the special circumstances while your in a pod and get in the way of a shuttle that happens to land on top of you. You will end up in the overmap (z level 1) at full size. You can see the icons for the ace, engineering outpost and the moon.  You can't interact with them, but that's not really the problem. The problem is when you attempt to fly off the z level. Doing this causes you to end up a 0,0,0 and you basically have been deleted but the game just mimics your existence.

**Comment by runedog48** [comment]
Perhaps if a shuttle lands on top of you, or another shuttle, you should be gibbed, and if two shuttles collide, they should be destroyed :L

Perhaps it should check to see if the landing position is clear of any other shuttles before launching?

**Comment by Kwask** [comment]
Would be fine with that, though it should only cause a minor explosion if there's a spacepod in the way

**Comment by GutsySS13** [comment]
I think this is only an issue with pods that move. when a regular shuttle lands on top of another one all the contents are merged together in a godly mess, but no one dies or gets stuck somewhere.

**Comment by runedog48** [comment]
Just realized this is talking about shuttles landing on pods, not pods on pods Destroying the pod and causing a small explosion seems logical, what extent of damage would occur? ( Eg. Breach or smaller than that? ) The people inside the spacepod would be gibbed by this?

**Comment by rjtwins** [comment]
With the new shuttle code pods SHOULD get destroyed with no explosion when a shuttle lands on them. I will make the pod go boom with a small explosion. Also if admins do be to badmin shuttles can not land on one another any more.
