### ISSUE TITLE
Player panel periodically breaks

### ISSUE THREAD

**Issue by bryanlavergne** [Apollo-Community/ApolloStation#627]
The issue is marked by a completely empty player panel.

**Comment by Kwask** [comment]
Sounds like the same issue we had a few months ago when monkeys were being deleted incorrectly

**Comment by stuicey** [comment]
oh yeah, I looked at the debug list and there is indeed another null mob.

**Comment by stuicey** [comment]
Haven't seen this issue in the wild or heard any recent complaints
