### ISSUE TITLE
Headgear sprites

### ISSUE THREAD

**Issue by stuicey** [Apollo-Community/ApolloStation#63]
Headgear sprites are not showing up in-game. The icon sprite shows up in the inventory but in-game the sprite is missing.

**Comment by Fleegle2000** [comment]
/icons/apollo/mob/head.dmi, which contains all the helmets, was changed in the last update.

**Comment by stuicey** [comment]
fixed in 95e3affb84fd490078796b274bebcff7aa62e6aa
