### ISSUE TITLE
When downloading a local branch of Apollo machine processing just hangs

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#635]
When you launch a local server instance the machine process just seems to time out and make the game very laggy (and hard to test stuff). 

it eventually kills machine processing after 3-5 mins or so but it's pretty annoying and may even start up again after a bit. I reverted to an older apollo.

**Comment by Kwask** [comment]
calling stu since that thing is his baby

**Comment by stuicey** [comment]
Does this happen every round? and what are the steps to reproduce - as it is very likely to be a wine issue due to this not happening on the live server.

**Comment by Kwask** [comment]
Also what version of BYOND?

**Comment by GutsySS13** [comment]
use github to download a local copy of apollo. run dreamdeamon. login, game lags

**Comment by GutsySS13** [comment]
509.1319

**Comment by GutsySS13** [comment]
well it's wierd. it was doing it this morning, I just updated and now it's not .....

The cpu time in the status window would just stop for a few seconds then resume for another couple then stop again.
