### ISSUE TITLE
EMPLOYEE UPDATE BONANZA

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#639]
- [x] Can't modify a blank ID
- [x] Can't transfer department as HOP / Captain
- [x] Cant select account items
- [x] Character records aren't added to computer records
- [x] HOP and captain can assign access from centcomm
- [x] Updating PDA wont update name
- [x] Cannot delete characters
- [x] Cloning doesn't work 
- [x] Admin OOC doesnt work (its because they're not donators)

**Comment by halworsen** [comment]
- [ ] "Needs glasses" can't be toggled in character setup.
- [x] Organs & limbs button says "ajust".
- [x] Custom loadout button says "add"
- [x] Characters lose all settings (division & unlocked roles included) outta nowhere???

**Comment by MyNameIsKodos** [comment]
Supply is missing an entry level position (afaik, might have been full when I tried to join)

**Comment by lmas** [comment]
- [x] ~~I think missing a lot of crawlable vents, like kitchen, hydroponics.~~
- [ ] No tazers to build robots from.
- [ ] Can't grab a dead mouse.

**Comment by BlueSushii** [comment]
Imas, kitchen and hydroponics are their own separate vent system, if you go to those ones you can access all the kitchen ones

**Comment by Kwask** [comment]
@lmas, it seems like a fair tradeoff for a sec officer to give up his taser to get another robot sec officer

**Comment by lmas** [comment]
Eh I don't care, it was reported by someone else who thought it was annoying.

**Comment by lmas** [comment]
- [x] Can't randomize names anymore. Example: All my chars have a "description" as a name, as I always had the "random name" option on. Now I'm stuck with a bunch of chars with stupid "names" which I can't change.

**Comment by Kwask** [comment]
We removed always random names, and you aren't allowed to change names on saved characters. You're supposed to be playing persistant characters now, rather than a newbie character every round.

**Comment by lmas** [comment]
Welp, my chars are fucked then. I might aswell go grab a new ckey instead, as it's easier to start from scratch.

Some random notes I grabbed from metichi:
"What about a traitor that goes into the captains office and promotes himself"
"Or a griefer that demotes everyone"

I'm sure this was discussed but I can't remember what was said, so I'm noting it down in here again.

**Comment by Kwask** [comment]
You should be able to delete characters, but I forgot to add the query to remove characters from the database. 

Antags are not persistant, so promotions you get as antag will not carry over between rounds. You also cannot promote with the spare captains ID card, you need a card from an existing command staff member. 

If a griefer somehow does manage to get promoted to head, admits can very easily demote them and restore any roles they removed from other players.

**Comment by lmas** [comment]
Assuming there are any admins on at the time of the griff. I'll keep forwarding players into here if it comes up again.

**Comment by stuicey** [comment]
- [x] Move department related Assistants to their actual departments in crew manifest
