### ISSUE TITLE
Can't access the character or editor if you have no occupations selected.

### ISSUE THREAD

**Issue by Weer6** [Apollo-Community/ApolloStation#641]
If you turn off all of your occupations, including assistant, you can no longer access the appearance section of the character editor and you can no longer hit the "character setup" on the starter menu. You can still join as normal, but  you can no longer edit or choose a different character. I personally believe this has something to be tied with the character picture. What should happen is that it shows a naked character, but something along the lines is causing a problem where it can't show the picture, and can't open any sections with the character picture. this includes the appearance section of the character editor and the character selector that opens when you hit the character set up.

Steps to reproduce
1. Head to the character editor.
2. select the Character occupations section
3. Turn /all/ the occupations to never, including assistant.
4. the bug has been successfully reproduced, you should not be able to change to the appearance section of the character editor, and if you close the editor entirely, you will be no longer able to open the character setup section.

**Comment by Weer6** [comment]
I'd think it would be a little bit more severe since you can't edit your characters if you are affected by this bug, or choose a new one at all.

**Comment by Kwask** [comment]
Fixed in 4dc9e33807621533639eb31dac31f42ee8072cbe
