### ISSUE TITLE
Changeling bug (Character Save corrupted)

### ISSUE THREAD

**Issue by Delnth** [Apollo-Community/ApolloStation#647]
When I played as changeling earlier, I played as Violet, when the round ended, my character save has been modified as the character of my victim. It was just the appearance, anyway. But still a problem.

**Comment by Kwask** [comment]
I suppose it didn't make the changelong non-persistant for some reason, I'll have to check the transformation code

**Comment by Kwask** [comment]
Fixed in cc9e48f6a863ae4c8a92227a125ba5498d1f472b
