### ISSUE TITLE
Faxes

### ISSUE THREAD

**Issue by JMMJ01** [Apollo-Community/ApolloStation#654]
This isn't a huge, glaring issue, but it'd be nice if we'd be able to see the fax replies sent out to the plebians on station.

**Comment by GutsySS13** [comment]
can i add it would also be nice to fax certain fax machines on the station from centcom too... but that may take a bit more sorting out

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=676
