### ISSUE TITLE
Brig-Section of Escape shuttle

### ISSUE THREAD

**Issue by TheGrandVosk** [Apollo-Community/ApolloStation#655]
Not sure if it was posted on here or not, but It seems that when you sit in the brig-section of the escape shuttle, it says you've missed the shuttle completely. (And In one case, I believe it said I didn't survive at all.) I've heard a few other people screaming about this, so I decided to post it.

Edit: Turns out, It's not even the Brig-Section of the escape shuttle that does it. It seems to be the whole shuttle. (At least, that what I just saw.)

**Comment by halworsen** [comment]
I think it has to do with not triggering completion for the "escape alive and free" objective if you're shuttle-brigged.

**Comment by CakeQ** [comment]
We don't have "escape on the shuttle" objectives anymore so I don't think this is important anymore
