### ISSUE TITLE
Cargo bay trolley bug

### ISSUE THREAD

**Issue by Dominhiho** [Apollo-Community/ApolloStation#657]
Strange bug where if you try to put a crate onto the first connected tug trolley it won't do it, but the other ones work. Also once a crate has been dragged onto a trolley, if you remove it from the trolley you can't put another crate onto that specific trolley until you put a crate on a different trolley.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=677
