### ISSUE TITLE
Slashing instead of stomping?

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStation#658]
As a species with the ability to slash someone, you should be able to countiue to slash that  person when they are on the ground, instead of resorting to the much less powerful stomp. 
Just a suggestion

**Comment by Kwask** [comment]
How would you switch between those modes?

**Comment by BlueSushii** [comment]
Disarm for stomp. Harm for slash if your species can slash?

**Comment by Kwask** [comment]
disarm is disarm, it's not supposed to cause damage

**Comment by BlueSushii** [comment]
Would you need to be able to switch? If you intend to harm someone slashing does more damage.

**Comment by Kwask** [comment]
it makes more sense to be stomping someone on the ground than bending over and slashing them

**Comment by BlueSushii** [comment]
Species that can slash, have clawed feet?

**Comment by Awantje** [comment]
Perhaps give it a verb? Activate the verb to extend claws activate again to rectract them?

**Comment by BlueSushii** [comment]
Yeah a verb could work. But why would the claws be able to extend? The claws of your species can't really retract or extend. But maybe a verb to change between them could work.

**Comment by Awantje** [comment]
A cat can extend and retract them. So for tajarans it would at least seems to be so.

**Comment by BlueSushii** [comment]
Yeah but what about the unathi? There claws are longer but they can't be retracted. And I don't think a tajaran can extend them long enough to really make a difference

**Comment by Awantje** [comment]
Even so, using your claws is a bonus. And a verb would let you choose when you use them. Same with harm, disarm and grab.

**Comment by BlueSushii** [comment]
By default you use claws all the time. Maybe we could have a special ability where you kneel down and start to shred them open? And do damage the longer you are next to him  and not moving?

**Comment by Awantje** [comment]
Thats not very nice now is it? And also that in my opinion puts humans behind quite a bit.
