### ISSUE TITLE
DNA modifier console only works if built after DNA modifier

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#66]
The UI for the DNA modifier only comes up if the console is located inside the room with reinforced floor in miscellaneous research.

**Comment by halworsen** [comment]
Nevermind, it appears that it just doesn't work if the console is built before the modifier. Not a major bug, but annoying and deceiving nonetheless.

**Comment by lmas** [comment]
Closing this as the geneticists job have been disabled and noone will ever play with this console again.
