### ISSUE TITLE
Asteroid has air

### ISSUE THREAD

**Issue by JMMJ01** [Apollo-Community/ApolloStation#664]
http://i.imgur.com/YKJgIyy.png
http://i.imgur.com/jVyeFxV.png
http://i.imgur.com/epWMoOA.png
http://i.imgur.com/60OKMGq.png

No pressure, but there is air on the asteroid. The ground is also known as plating now, it appears.

**Comment by lmas** [comment]
The ground tiles are subclassed from the metal plating floor tiles or something like that, that's why it appears to be "plating". Same thing with the asteroid rock walls I think.

**Comment by rjtwins** [comment]
With the new moon tiles this should not be an issue anymore
