### ISSUE TITLE
Template GetCollection() gets stuck in an infinite loop

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#666]
> Infinite loop suspected--switching proc to background.
> If it is not an infinite loop, either do 'set background=1' or set world.loop_checks=0.
> proc name: GetCollection (/datum/dmm_parser/proc/GetCollection)
>   source file: dmm_parsing.dm,274
>   usr: null
>   src: /datum/dmm_parser (/datum/dmm_parser)
>   call stack:
> /datum/dmm_parser (/datum/dmm_parser): GetCollection(/list (/list))
> /datum/template_controller (/datum/template_controller): GetTemplateSize("maps/templates/random/template...")
> /datum/template_controller (/datum/template_controller): PlaceTemplates()
> /datum/controller/game_control... (/datum/controller/game_controller): setup()
> world: New()

Template system disabled until this is fixed, since it crashes the server.

**Comment by JMMJ01** [comment]
I'd like to point out this is the devil's issue.

**Comment by halworsen** [comment]
I find it fitting that it's an infinite loop bug

**Comment by JMMJ01** [comment]
Because the power of Jesus is infinite and he will fix this bug.

**Comment by halworsen** [comment]
o7
