### ISSUE TITLE
Diona nymphs have larva alien interface

### ISSUE THREAD

**Issue by Metichi** [Apollo-Community/ApolloStation#67]
Diona nymphs have an alien interface instead of a monkeys, thus not allowing it to have hands or inventory or anything. Also, cannot steal blood.

**Comment by lmas** [comment]
Stealing blood doesn't do much anymore I think. Dionas have an internal timer on them instead, that counts down until they can grow into full form.

**Comment by JMMJ01** [comment]
Yeah, Bay swapped them to vegetarians or something along the lines of that.
No more Mr, Bitey.

**Comment by lmas** [comment]
Per 29435d8750a58c339356a6b8c787d4fffe8d2767, hands for diona nymphs have been disabled in bay12. That's the reason they got the [alien larva hud](https://github.com/stuicey/ApolloStation/blob/master/code/_onclick/hud/hud.dm#L242) too.

I'm going to close this for now. If you guys think we should add in the nymph hands again you could reopen this issue and comment.
