### ISSUE TITLE
The outpost camera monitor in cargo can use the AI Chamber South Camera

### ISSUE THREAD

**Issue by MysticalLatios** [Apollo-Community/ApolloStation#673]
The outpost camera monitor in cargo can use the AI Chamber South Camera.
Its the console just to the right of the mining pod bay, it might also effect the one in eds office too.

**Comment by halworsen** [comment]
Cake fixed this, but the fix won't come along until arrivals gets its update.

**Comment by stuicey** [comment]
Fixed in 0.3
