### ISSUE TITLE
Scientists don't have access to chemistry

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#68]
It's pretty obvious that the map is laid out for scientists being able to share chemistry with medical, but they don't have have access to the windoor leading into chemistry.

**Comment by Awantje** [comment]
I think its not the plan that they can actualy get in. There is a chem cooler where you can come.

**Comment by halworsen** [comment]
Fun fact regarding that: scientists can't access the refrigerated storage (chem storage) that literally faces into the science hallways.

If scientists actually aren't supposed to get into chemistry, please just remove the entry into chem from science entirely and expand the lab instead. It's incredibly annoying to have the chem dispenser tease you from behind closed doors when you need sulphuric acid for the circuit imprinters. Going to the research outpost for something as simple as that is really unnecessary.

**Comment by Awantje** [comment]
The rd can get in scientists cannot.

**Comment by Kwask** [comment]
You can get sulphuric acid from the limited chem dispenser on the science outpost. If scientists want to play chemist, they should join as chemist

**Comment by Fleegle2000** [comment]
I don't think Science should have access to the windoor, however I do think Chemistry needs to be modified such that it shares a counter with Science - essentially a mirror version of what exists between Chemistry and Medbay. The current layout is a bit confusing.

With regards to the sulphuric acid though, I think science could use a single-purpose dispenser like the radium dispenser in virology. Making the Scientist travel to a remote station just to get some sulphuric acid doesn't make a lot of sense to me.

**Comment by halworsen** [comment]
If scientists aren't supposed to do any chemistry, I think the map needs to be changed. To be honest, the science side of chemistry serves no purpose at all - it's a waste of space.

![](http://i.imgur.com/qMWuZqo.png)

I agree with Fleegle if the case is that scientists aren't supposed to have chemistry access. It's less of an issue in regards to actual chemistry (which I haven't seen any scientists even wonder if they could do), but more so about ease of access to sulphuric acid.

**Comment by Awantje** [comment]
Perhaps put a chem dispenser in that room that is the same as the outpost one?

**Comment by Fleegle2000** [comment]
Here's what I propose:

![newchem_rd](https://cloud.githubusercontent.com/assets/6960986/7117792/23a8269a-e1c9-11e4-891a-1bd48121dc5c.png)

Ignore the air alarm I forgot to remove. I took out the little maintenance area and bathroom and added an area similar to the one in Medbay lobby.

I would be fine with just giving Science a single-purpose dispenser of sulphuric acid, too, though. I offer to reskin the radium dispenser in virology for that purpose, if that is more suitable. It would avoid ripping out the maintenance closet and blob spawn point as I've done here.

**Comment by Kwask** [comment]
Single-purpose sacid dispenser would be perfectly fine, I would think

**Comment by Fleegle2000** [comment]
Cool, I'll get started on that.

**Comment by Fleegle2000** [comment]
I've added a sacid dispenser object and icon to the "dispensers" branch, and as an added bonus, I also made a space cleaner dispenser for the janitor. I haven't added them to the map because reasons. I leave that to more capable hands.

**Comment by Fleegle2000** [comment]
I've sorted out the mapping issues and will upload a new map tomorrow with the sacid dispenser.
