### ISSUE TITLE
No radiation from sm.

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#686]
It seems like the supermatter does not give off radiation to people. Or not enough. I can just be in the room without problems.

**Comment by Kwask** [comment]
Was the SM active? Or was it at round start?

**Comment by Awantje** [comment]
it was completely active

**Comment by MysticalLatios** [comment]
I have had this happen before also. SM was active and even was actively be charted by the emitter but it was not causing any damage to a human player standing right next to it without any protection.

**Comment by stuicey** [comment]
fixed in 0.3
