### ISSUE TITLE
Engine is no longer a perpetuum mobile

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#691]
Keeping the emitter on in the current engine setup causes it to overload after some time.
I am unsure if this is intentional but the guide/book still says you can keep the emitter on.

**Comment by Kwask** [comment]
The guide says it only works for a level 1, aka a green supermatter core. If you fail to put in the coolant or turn on the coolers, it won't work either.

**Comment by Awantje** [comment]
It does not work for a level 1 green sm core. Coolers on coolant in. N2 or phoron as coolant. The temp will rise
