### ISSUE TITLE
IC chat muted because of appendix 

### ISSUE THREAD

**Issue by Krutzelpuntz** [Apollo-Community/ApolloStation#700]
I had some trouble with my appendix, and my character kept messaging 
: winches slightly.

This resulted in a ic chat mute, and I had to get unmuted by an admin.

**Comment by rjtwins** [comment]
I've looked into this, and the spawn checker will now look trough a list of allowed emotes and "ignore" them in the check.
This needs feedback

**Comment by Hate9** [comment]
Is it possible for the ignore list to have player-specific additions? I have a mute character, and I end up nodding enough to nearly trigger the mute semi-frequently.

**Comment by Kwask** [comment]
I'd rather not, because then people will just add a player specific whitelist for *scream and then what's the point of the whole thing?

**Comment by CakeQ** [comment]
Rjtwins already fixed this for 0.3

**Comment by Hate9** [comment]
I'd assume most admins wouldn't do that.

**Comment by rjtwins** [comment]
Also can get muted if you insists on grabbing something with your broken arm.
Putting that in aswell.
