### ISSUE TITLE
Suggestion: Triggerable Tape Recorders

### ISSUE THREAD

**Issue by Draco16** [Apollo-Community/ApolloStation#703]
Add an option to add a sensor to a tape recorder so that if the sensors picks anything up it will playback whatever is recorded on the Tape.  

Could make department greetings with this. "Hello, and welcome to Cargo, Someone will be with you in just one moment."  Would be even more awesome if you could rig it with a radio so it plays the message on the supply channel so Cargo knows when someone walks in.

**Comment by Kwask** [comment]
Suggestions go on the forums, sorry
