### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#71]
I tried something and I think I did it.
All I have to do is find a way to upload huge files.

I have a file with all wiki extentions.

https://docs.google.com/spreadsheets/d/1R4LozfF6S2tdKm2RAeQssiJxvi7M410XwSNrUzrtlFc/edit?usp=sharing

You can use it here.

http://wiki.baystation12.net/index.php?title=Special:Export&action=submit

**Comment by Awantje** [comment]
You have to remove the non wiki sites such as byond. Before using it. I cant do it now.

**Comment by Awantje** [comment]
did my best and this is what i got.
http://apollo-community.wikia.com/
Bit unsure if we have all the pages.
I know I somehow cant get the main page.
All jobs are there.
All locations (afaik)
All guides are there.
No images.

**Comment by Fleegle2000** [comment]
I can fix up the main page if you want, however I will need permission to edit the main page.

**Comment by Awantje** [comment]
Sure, I am not home but ill try by phone. Though I am not sure if we want this wikitype.

**Comment by JMMJ01** [comment]
Our wiki was sort of taken over by bots sorta. Navigate to some of the
pages.

**Comment by Fleegle2000** [comment]
I looked at a few pages. I hadn't noticed anything unusual.

Question: does wikia use MediaWiki? If not that might explain why it didn't transfer entirely correctly. I have to leave for a while so I can't get started on anything right away, so there's no urgency.

**Comment by Awantje** [comment]
I saw some things did not copy well. But almost no edits are made yet. And all pics are missing but thats a known issue.

**Comment by JMMJ01** [comment]
I'll look into it more. Unless Kwask went in and cleared them out, there
were a dozen or so randoms about selling products, and one about staring a
business.

**Comment by Awantje** [comment]
also its a free wiki. It uses their own stuff. I can also find something payed and add free.

**Comment by JMMJ01** [comment]
Oh, you made a new one?

**Comment by JMMJ01** [comment]
I see now. We had one before, here
http://apollo-community.org/wiki/index.php?title=Main_Page. Kwask took it
down I believe after the bot issue. He took it deepen about a week ago.

**Comment by Kwask** [comment]
I took it down because there was 23 gb of spam over thousands of pages. I'll put a new one up with the exported pages from bay. I won't use the wikia one because we already have a domain, hope you didn't go through too much work to set that up, Awan

**Comment by Awantje** [comment]
Nah its ok.
Though I would love to see the domain and aid with administrating its easy to stop bots if you close normal accounts.

**Comment by Fleegle2000** [comment]
Whenever you get the new one up, I'll help out where I can.

**Comment by Awantje** [comment]
I can take the one I made down and add the pages from bay. All you have to do is make the wiki and have an admin on it.

**Comment by Kwask** [comment]
You can find the new wiki located here: http://wiki.apollo-community.org/

If you want an account for it, let me know and I'll get one set up for you

**Comment by Awantje** [comment]
I want one. Name Awan

**Comment by Fleegle2000** [comment]
I would also like to be added. Same username as here.

Also, question about images - can we use the baystation ones or are they supposed to be unique to Apollo? I'm meaning like the ones for the main page. Obviously the things that are specific to Apollo would not use bay images.

**Comment by Awantje** [comment]
we can make our own imo. to prevent copyright

**Comment by Fleegle2000** [comment]
Yeah that's why I ask. I wasn't sure if the images were covered by the same attribution licence as the Bay text. Better to be safe than sorry.

**Comment by Kwask** [comment]
There's no copyright on the baystation wiki, hence why we can import all of their pages without legal incursion. Feel free to take as many images from them as you like, it just happens that the export pages function on media wiki doesn't include images, which is why our wiki is currently devoid :P

**Comment by lmas** [comment]
You got a source on that kwask? I just want to be sure.

Also might want to get rid of that wikia wiki, might confuse the search engines and future visitors.

Edit: And remove that pesky http://apollo-community.org/wiki/index.php?title=Main_Page wiki too, that's going to be a problem in the future for sure D:

**Comment by lmas** [comment]
:pager: Paging @Kwask and @Awantje for status update.

**Comment by Awantje** [comment]
ill take a look

**Comment by lmas** [comment]
Thanks man.

**Comment by Awantje** [comment]
I send a mail.
