### ISSUE TITLE
Cargo MULE can't move

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#713]
I set destination (currently tried kitchen, medbay) and click on proceed.
MULE buzzes once and complains about "Status: Unable to locate destination" and don't move.

**Comment by Kwask** [comment]
Probably missing the destination landmarks

**Comment by CakeQ** [comment]
Mulebots are being removed in the new map due to being too buggy (Also might as well just use the new disposals system)

**Comment by CakeQ** [comment]
this should be closed now
