### ISSUE TITLE
Character creation bug: changing species

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStation#716]
While making a new character, if you try ti change its species to anything. It will bring the menu up normal too allow you to see the species, however the "[select]" button is missing. So you can't actually pick the species and change it, if you try you open the species selection tab and you can't really close it.

**Comment by Kwask** [comment]
It's there for me
![ynkl5in](https://cloud.githubusercontent.com/assets/6261478/14163820/19610026-f6c7-11e5-86d7-b0f79cb1e374.png)

Any steps needed to reproduce?

**Comment by BlueSushii** [comment]
Maybe something has changed since then, I'll see tommorow if it has been fixed for me aswell
