### ISSUE TITLE
Robust coffee is unsprited

### ISSUE THREAD

**Issue by Metichi** [Apollo-Community/ApolloStation#718]
Robust coffee from the vending machines doesnt have a sprite associated, so its invisible. You can pick it up by using alt-click o the tile it is and picking it up form the floor tab, or drink it while in hand, and generally everything you can do with a coffee. But it is invisible.

**Comment by BlueSushii** [comment]
This has already had a issue ticket submitted for it,

**Comment by CakeQ** [comment]
issue has been fixed for hangar update

**Comment by minutekiwi** [comment]
already referenced here #688 & here #642 . @Kwask pls
