### ISSUE TITLE
Telecoms access ladder area turret issue

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#72]
The turrets take a while to pop up and the room is so small you can easily run across it before they do it's almost not worth having them. Please make the room/pathway longer (maybe a glass corridor or something) as it's very easy to traverse right now.

**Comment by Awantje** [comment]
they pop up to late. Its not the roomsize

**Comment by halworsen** [comment]
Those turrets are broken anyways.

**Comment by lmas** [comment]
What do you mean broken anyways?

**Comment by halworsen** [comment]
Turret controls aren't connected to the turrets, so they'll shoot anyone on sight no matter what. The only way to disable them would probably be to destroy them.

**Comment by lmas** [comment]
Apparently there's multiple turret objects and someone picked the wrong one.

**Comment by lmas** [comment]
Still not sure how to speed up the turrets though..

**Comment by Kwask** [comment]
Decreasing the animation time on the turret icon might work, I think

**Comment by lmas** [comment]
Turrets [sleep for 10s](https://github.com/stuicey/ApolloStation/blob/master/code/game/machinery/portable_turret.dm#L531) when it's animating the popup/popdown states. We could turn down that time I guess.

Edit: Actually, now that I tested it they popped up pretty quick as soon as I entered the room. Closing this issue for now.
