### ISSUE TITLE
Snow White recipe

### ISSUE THREAD

**Issue by Hate9** [Apollo-Community/ApolloStation#727]
The current recipe for the Snow White cocktail is 1 part beer, 1 part lemon lime.
According to the internet (http://www.bacardi.com/ca-en/cocktails/snow-white http://www.absolutdrinks.com/en/drinks/snow-white/ http://www.diffordsguide.com/cocktails/recipe/1787/snow-white-daiquiri)
A Snow White contains about 2 parts rum, 1/2-1 parts lime juice (not lemon lime), pineapple juice, and sugar syrup, in addition to an egg white.
2 parts rum sounds fine, and half parts suck, so because pineapple juice and egg whites don't exist, my suggested recipe is:
2 parts rum, 1 part lime juice, 1 part sugar.

Because beer isn't a fucking spirit.

**Comment by Kwask** [comment]
I think every drink is 3 parts or less, would equal parts rum, lime juice, and sugar be fine?

**Comment by lmas** [comment]
Hey don't forget to add an egg in there (in place of egg white), no matter how many parts the other drinks ussually have.

And of course proper testing should be done too. This is done most easily with a real life drink test, using the final recipe you decide on :p

**Comment by AquaDraco** [comment]
Isn't the Gargleblaster like five different things?
