### ISSUE TITLE
Alert words pick up bits of the code

### ISSUE THREAD

**Issue by Metichi** [Apollo-Community/ApolloStation#730]
The alert words feature picks up and shows parts of chat that were meant to be not shown, if you so happen to have an alert word that is contained there.
For example: 
[Common] Lupita De La Rosa excLaims, <.span cLass='body'>"Hello!" ((Its picking up the word 'La' from my name)) (((added a dot because the comment removed the bit of the code)))

You can solve this by removing the word from your alert word list, but the issue will pop again when you ghost, or are cloned, or basically any time that causes the word list to reset.

**Comment by Kwask** [comment]
Fixed in ace8b6acc975ed5dfff61e2e759cd11d251abcb9
