### ISSUE TITLE
Characters with ' in their names get deleted after saving and switching characters

### ISSUE THREAD

**Issue by Arrowhead154** [Apollo-Community/ApolloStation#733]
Found the issue as to why a few characters keep getting deleted. Any race with an apostrophe in their name gets deleted even after being saved.

**Comment by astralenigma** [comment]
Honestly " ' " bugs might be BYOND related.
BYOND seems to add "\" char before it and it's also seen as a change line char.

**Comment by astralenigma** [comment]
I meant byond.

**Comment by Haldreithen** [comment]
I've personally many characters that has apostrophes in their names and this never happened. Either it was fixed or not, could not reproduce.
