### ISSUE TITLE
gummy bear injection

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#75]
Trying to inject something in a gummy bear gets a syringe flavored gummy bear.

You take a bite of the orange and syringe flavored giant gummy bear.

**Comment by Awantje** [comment]
That's an orange and syringe flavored giant gummy bear. It is a small item.
Cover it in chocolate and a miracle or two,
 You think you can see the syringe in there.

**Comment by JMMJ01** [comment]
Can you fill the syringe up with space drugs and the people get the effect?

**Comment by Awantje** [comment]
Idk normaly you can inject spacedrugs into food for fun times though!

**Comment by lmas** [comment]
This is a limitation with the TG cooking we imported. Basicly, any food made with the TG kitchen tools (oven, grille etc) turns the food item into a "food container" and so you can add anything to it. Would have to do manual checks for syringes and do something else with them (just like I did with the kitchen cutlery, see https://github.com/stuicey/ApolloStation/issues/13)

**Comment by lmas** [comment]
Let's hope I won't be killed for helping you guys inject nasty things into food now! \* takes a bite of his sandwhich*
