### ISSUE TITLE
Cannot stack cable pieces

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#758]
Just as the title says, if you cut a laid cable, you cannot rejoin the pieces into a coil.

**Comment by Draco16** [comment]
Is this still being looked into? As it is right now, wiring solars is harder, and borgs can't restock their cables without spending a very long time in the recharger every time they use up 30 wire.

**Comment by CakeQ** [comment]
@Draco16 I don't think anyone is looking into this at the moment if you're interested at looking into it. Be sure to check that wires still work with the wire painter if you make any changes.
