### ISSUE TITLE
Miscellaneous Map Bugs

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#78]
Rogue glass table in the RD's office.

![nasty tables](http://i.imgur.com/qISULgs.png)

Directly underneath the research monitor.

**Comment by JMMJ01** [comment]
Just smash it.

**Comment by Awantje** [comment]
Ill add my point here because its both a mapfix.

Fire alarm in a disposal unit
http://gyazo.com/7a1cf098d9cec2add97ddec2e8811a6d
Location medbay under the the reception.

**Comment by Awantje** [comment]
Middle of the screen camera on a vendor.
http://gyazo.com/323714f9e3d038902bd38615b67f5f36
Also medbay

**Comment by GutsySS13** [comment]
does this need to still be open ? the glass table in the RD's office has been changed to a normal steel one so the table bends properly once more, the fire alarm under medbay reception is now located on the right hand wall of the room and the security camera also seems to be in the correct place and has no pixel_x/y variables assigned to it.
