### ISSUE TITLE
Mods listed as admins

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#79]
See title
http://gyazo.com/cff3f79958b8e4af8f102f5077cf1edd

**Comment by JMMJ01** [comment]
That would be due to Mods having a lot more powers in our server vs. in others. They have a lot of the abilities of admins, but not all of them.

**Comment by JMMJ01** [comment]
To add on more of what I said, I believe it's SS13 itself just recognizing permissions and it lists off of those who is what rank. It would have to be changed in the coding for the ranks to edit how it shows off the admins vs. mods.

**Comment by Awantje** [comment]
I think if you have +mod its a mod +admin you are an admin

**Comment by Kwask** [comment]
Except all the mods have +ADMIN. :P

**Comment by JMMJ01** [comment]
That's what I was trying to get at. We should change it from saying mods
and aspirins online to saying staff online.

**Comment by Awantje** [comment]
It is a minor problem lol

**Comment by lmas** [comment]
Or you could change the mods to be regular mods, but with the extra admin permissions. Easily done in the admin_ranks config file.

**Comment by Ccomp5950** [comment]
https://github.com/stuicey/ApolloStation/blob/master/code/game/verbs/who.dm#L73

You're going to need to change this check to reflect your difference in Admin / Mods.  R_ADMIN on baystation means "ur an admin Harry!" but if your mods have R_ADMIN then welp.

Either that or just change it to just a general staff listing.

**Comment by lmas** [comment]
Easy enough to [change line 78](https://github.com/stuicey/ApolloStation/blob/master/code/game/verbs/who.dm#L78) from `msg += "\t[C] is a [C.holder.rank]"` into `msg += "\t[C] is a admin"`, for example.

**Comment by ghost** [comment]
@Awantje Is this still a issue? I'm a mod and it shows Moderator for me.

**Comment by lmas** [comment]
If that's the case, Hidden, I guess one of our hosts updated the RANKS file.

**Comment by Awantje** [comment]
I have not checked because I am rarely on ss13 these days because its always on when I aint.

**Comment by lmas** [comment]
It's been corrected.
