### ISSUE TITLE
Fuel doesn't work correctly

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#8]
Fuel doesn't burn correctly. If injected in a cigarette and it is lit up, the cigarette explodes but causes no damage. If the fuel is on the ground is does not stay lit up for more than a second and worst of all it does not spread to fuel on adjacent tiles.

**Comment by lmas** [comment]
Seems like someone turned up the anti-griefs level to max. Not even a flamethrower will do any harm.

**Comment by stuicey** [comment]
done some digging - liquid fuels are currently disabled after gasses where moved from being hard coded in.

**Comment by lmas** [comment]
Per https://github.com/Baystation12/Baystation12/issues/8108 liquid fuel fires have been disabled for now. Lag something something.. 

Someone made a fix but I think it hasn't been merged into bay12 yet.
