### ISSUE TITLE
Windoor recipe doesn't add up

### ISSUE THREAD

**Issue by Hate9** [Apollo-Community/ApolloStation#806]
When you make a windoor, it requires reinforced glass, but when you destroy it, it doesn't give you bars. Not only that, but it gives you more cable coil on deconstruction than it requires to make.

**Comment by rjtwins** [comment]
fixed by Awan, if the pr's compile error gets fixed up.

**Comment by Awantje** [comment]
hey I fixed it then you changed the file when i was not looking
