### ISSUE TITLE
Can't put new flooring ontop of a hole to another z-level.

### ISSUE THREAD

**Issue by DreadedReborn** [Apollo-Community/ApolloStation#81]
Basically, whenever you try to fix the flooring of an 'open space' it just turns the tile grey, then puts it back to its normal self. Can't fix without admin assistance.

**Comment by lmas** [comment]
Same problem as #41. Apparently you can't place anything on the "open space" tiles.

**Comment by lmas** [comment]
Imma go and close this ticket, it's basically a duplicate.
