### ISSUE TITLE
Destructive analyzer wont deconscruct.

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#822]
You can use the screwdriver but not the crowbar on it!

**Comment by rjtwins** [comment]
Works just fine, just tested this in the dev.
![image](https://cloud.githubusercontent.com/assets/18174634/15672043/6f124e20-272e-11e6-8d22-c14211ceae58.png)

**Comment by Awantje** [comment]
is this before linking it? Because I am sure the one in rnd would not let me deconstruct it the crowbar just kept being added to it. Can you try to link it first?

**Comment by rjtwins** [comment]
I'll look into it.

**Comment by CakeQ** [comment]
Surely if you wanted to deconstruct it you would un-link it? That makes sense. Seems like the intended method.

**Comment by rjtwins** [comment]
Right I've edited the code so it's impossible for the machine to eat items when the panel is open I'll test it when I get back from work. So everyone hold your horses.
