### ISSUE TITLE
Telecoms green cable missing

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#83]
Walker's found a missing connection for the green cable just before it comes into the SMES room. As it passes under the turret it's missing one of the cable pieces so it doesn't connect to the cable under the wall.

**Comment by lmas** [comment]
Fucking.. that's from when I changed the turrets. I thought I fixed the cables I screwed up. Someone who can use the mapeditor should probably fix it then D:

**Comment by Kwask** [comment]
I fixed it yesterday, should be all good now
