### ISSUE TITLE
Randomly generated asteroids dont have light

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#830]
It's impossible to light up the asteroids at all.

I'm guessing the lighting overlay isn't getting properly initialized.

**Comment by rjtwins** [comment]
I had a similar problem with hangers where the lighting overlay was not recreated properly so I did it manually:

Wherein T is the affected turf.
You may have to do this for all non space turfs in your asteroid field.
        T.lighting_clear_overlays()
        T.lighting_build_overlays()
You may also want to clear the effecting lights before doing this.
        T.affection_lights = list()
