### ISSUE TITLE
Request; Floral Data Disc

### ISSUE THREAD

**Issue by Grant4455** [Apollo-Community/ApolloStation#841]
In Xenobotany, only 14 Floral Data Discs (Used for the storing of genes ripped from plants) are available from start, and obtaining more requires ordering a crate full of otherwise useless supplies. Could they be produced from the protolathe like the technology storage discs, perhaps at biology 2-3?

**Comment by KingNexus0** [comment]
You can easily wipe and re-use the discs, this really shouldn't be necessary.

**Comment by Hate9** [comment]
I use barely any, but it _would_ make more sense if they could be produced in protolathes.
EDIT: And it'd be one more thing that R&D could do, which is always nice.

**Comment by wykthor-btracker** [comment]
Code for making flora disks is in the source now, they can be produced on protalathe once you reach biotech level 3, thanks for pointing that issue out.

**Comment by wykthor-btracker** [comment]
Fixed on e1815fc
