### ISSUE TITLE
Medbay Issues: Not enough NanoMeds, and Medical Doctors can't access Medical Doctor lockers.

### ISSUE THREAD

**Issue by NovusLuna** [Apollo-Community/ApolloStation#854]
There is only one NanoMed vending machine that I've noticed, and it's secluded in a storage that I didn't find for a while. The Medical Doctors can't access a locker that is literally labeled for them. Also, I, as a standard Medical Officer without Senior access, can make myself a Virologist on a Job Transfer Console. Also, not enough medical emergency uplink radios...only 1 of those doesn't serve much a purpose.

**Comment by CakeQ** [comment]
fixed
