### ISSUE TITLE
The moon doesnt have telecoms.

### ISSUE THREAD

**Issue by Metichi** [Apollo-Community/ApolloStation#857]
I think you forgot the telecoms room? Havent found it yet and cant speak.

**Comment by CakeQ** [comment]
there is one, are you sure it wasn't working?

**Comment by Metichi** [comment]
Ill check again now but there were no communication even tho it looked like it was set up.

**Comment by Kwask** [comment]
Fixed in 60e9b915118bb7252903b5b6c5668c60948bcc67
