### ISSUE TITLE
Buggy spacepods/spacepodfab

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#86]
Can't finish construction on the spacepod spawned in the podbay by default. [/datum/construction/reversible2/pod](/datum/construction/reversible2/pod) is fucked and needs lots more work on it before a player can interact with that thing. See [mecha_construction_paths.dm](https://github.com/stuicey/ApolloStation/blob/master/code/game/mecha/mecha_construction_paths.dm) for a guide on how to build stuff. Also [construction_datum.dm](https://github.com/stuicey/ApolloStation/blob/master/code/datums/helper_datums/construction_datum.dm) for the helpers.

And pod fabricators are bugged too, building parts never finishes. The time cost for parts are always 0.

Get going @Kwask!

**Comment by Kwask** [comment]
the enigmatic Higgs-Bugson strikes again!

**Comment by Kwask** [comment]
Known bugs:
- [x] Pod Fabricators too far from science to be able to sync
- [x] Pod Fabricators keep going after all of their items have been completed
- [x] Pod construction is totally bonkers
- [ ] Pods fly too quickly

**Comment by hexagoncode** [comment]
Podbay is missing radio.

**Comment by hexagoncode** [comment]
Podbay is missing AI/computer controls for podlocks.

**Comment by Kwask** [comment]
Just need to slow these puppies down, and we can close this issue

**Comment by Kwask** [comment]
All of these are fixed now, closin'
