### ISSUE TITLE
random mining asteroid (forget number) no ore underground

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#863]
The mining drill and scanner doesn't detect ores underground and the drill won't start because it can't find any either.

**Comment by GutsySS13** [comment]
i did hit a xeno arch hidden object so they're spawning ok and their normal rocks are spawning ok

**Comment by halworsen** [comment]
May be related to how asteroid turfs were changed so that they don't leave space holes behind when blown up or otherwise removed?
