### ISSUE TITLE
surgeon spawns with psychiatrist jumpsuit, can't open medical doctor lockers

### ISSUE THREAD

**Issue by TheFlyingMako** [Apollo-Community/ApolloStation#864]

**Comment by CakeQ** [comment]
This is caused by leftover alt titles from the old role-set. You can't be a surgeon as a medical doctor anymore, so make sure you change that before joining next time. Lockers have been fixed too.

**Comment by rjtwins** [comment]
Kwask may have to do some sql magic to fix it globally.

**Comment by Kwask** [comment]
Fixed in 4c50367f15c953cf63af50c9e852e3dd7b064d98
