### ISSUE TITLE
Unbearable lag

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#865]
For some reason there are horrible, freezing lagwaves every once in a while.

Seems that there's some sort of machinery processing that's the culprit.

**Comment by Kwask** [comment]
My main suspect is shuttle code, it seemed to start and stop whenever I walked on or off the shuttle

**Comment by stuicey** [comment]
Added a few people to profiler to check it out

**Comment by Kwask** [comment]
Suspected to be from disposal waste ejected into space, should be fixed in e35d9e488feb0c9beb8ad41ed32faec5a94caf8e

**Comment by halworsen** [comment]
Yap. Fixed in e35d9e4

**Comment by rjtwins** [comment]
Champaign time!
