### ISSUE TITLE
Adding traitors mid-round contract list is empty

### ISSUE THREAD

**Issue by CakeQ** [Apollo-Community/ApolloStation#873]
I added a traitor mid-round for testing purposes, and I'm aware that normall you shouldn't add traitors mid-round, but I can see several situations where we could add traitors mid-round as admins to spruce things up. The contracts list was completely empty for the traitor.

**Comment by halworsen** [comment]
Contract picker chose a contract with a notoriety restriction as the first one, then. Give it a bit, and normal ones will come around.
