### ISSUE TITLE
`prefs.savePreferences()` does not work

### ISSUE THREAD

**Issue by stuicey** [Apollo-Community/ApolloStation#881]
When changing your preferences in the preferences panel this proc is called to save the change but it does not actually save it.

**Comment by Kwask** [comment]
A lot of the verbs in the preferences panel don't have the proc, or are you looking at the procs that do?

**Comment by Kwask** [comment]
Hopefully fixed in 701ff5ffc768d5e1e1de3fd1837e49560f705a3e
