### ISSUE TITLE
Operating Tables not working after putting a patient on the table.

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#885]
After you put a patient on top of the table, once they go off of the table, you can't put anybody back on that table for some reason. It says that there's already a patient on the table, when there's not.

**Comment by rjtwins** [comment]
Its probably a process being hung duel to the current lag problems.

**Comment by stuicey** [comment]
Going to close this since I believe it was because machine.process() was turned off this round.
