### ISSUE TITLE
Cargo Shuttle issues

### ISSUE THREAD

**Issue by CakeQ** [Apollo-Community/ApolloStation#886]
It seems like ordering anything over 2 crates of things just doesn't deliver anything at all.

**Comment by CakeQ** [comment]
tested 3 crates. 3 crates work

**Comment by Kwask** [comment]
Are we sure its not the type of crate thats the issue?

**Comment by CakeQ** [comment]
did two different orders of 3 webbing crates and 4 webbing crates. Both returned only 3. I'm definitely certain that only 3 crates are spawning per shipment, all other orders are lost in the process and it's first come first serve

**Comment by rjtwins** [comment]
I know what the problem is, it will be fixed sometime tonight.

**Comment by rjtwins** [comment]
Should be fixed now.
