### ISSUE TITLE
Contracts not appearing

### ISSUE THREAD

**Issue by CakeQ** [Apollo-Community/ApolloStation#890]
Played for about an hour as a traitor and there were no contracts

**Comment by halworsen** [comment]
100% certain you're not rounding up?

On release, I tweaked the delay until contracts appear at all up to 30 minutes, which is where it's supposed to be. After that, there might be some minutes where only notoriety-restricted contracts end up appearing.

**Comment by CakeQ** [comment]
It had definitely passed 30 minutes by the time I left.

**Comment by halworsen** [comment]
If it had _just_ passed 30 minutes, it's no wonder. The uplink got populated with a notoriety-restricted contract in that case. That means patience is key.

If it went more than about 40 minutes without regular contracts, though, then I'mma have to look into it.

**Comment by CakeQ** [comment]
Like I said, it had been at least an hour.

**Comment by Kwask** [comment]
Is this issue still relevant? I've not seen traitors complain about having a lack of contracts recently
