### ISSUE TITLE
Moonbase's solars doesn't works

### ISSUE THREAD

**Issue by Pygmali** [Apollo-Community/ApolloStation#895]
All the solars and the tracker who are curently over catwalks can't works. If you put the solars and the detector over a dot elswhere, it works : 
![aaaaaaaaaaaaaaaaaaaapng](https://cloud.githubusercontent.com/assets/19761758/15868589/c817efa6-2ce8-11e6-9af3-77af5780d25a.png)
![aaaaaaaaaaaaaaaaaaaapng](https://cloud.githubusercontent.com/assets/19761758/15868614/e166a3c6-2ce8-11e6-8e93-937be2dfb1a3.png)
![aaaaaaaaaaaaaaaaaaaapng](https://cloud.githubusercontent.com/assets/19761758/15868629/f63082cc-2ce8-11e6-8b53-23e76d7e6ecf.png)

(Ps : you don't need to change the computer place, I was just testing stuff)

**Comment by CakeQ** [comment]
Has been fixed
