### ISSUE TITLE
Arrivals pamphlet empty

### ISSUE THREAD

**Issue by Metichi** [Apollo-Community/ApolloStation#904]
The pamphet in arrivals has no text to it (if it was intended to)
Its also misspeled as pamplet

**Comment by CakeQ** [comment]
It was never planned to have anything in it :p

**Comment by Kwask** [comment]
What's the purpose of it existing then?

**Comment by CakeQ** [comment]
it's a folder subtype, with a fancy description. Tourists spawn with one

**Comment by CakeQ** [comment]
naming issue has been solved
