### ISSUE TITLE
Only the first vote in the commendation system for the antag works

### ISSUE THREAD

**Issue by Pygmali** [Apollo-Community/ApolloStation#909]
I was twice traitor, each time the guys told me more that one voted for commendation, but I only received one commendation each time. I think the only first one works

**Comment by CakeQ** [comment]
not the case, I have recieved more than one commendation as a traitor in one round before

**Comment by halworsen** [comment]
Never encountered this. I think it's more likely that they lied to you about commending you (if they even knew what antagonist you were playing).
