### ISSUE TITLE
Resisting Borer control.

### ISSUE THREAD

**Issue by Grant4455** [Apollo-Community/ApolloStation#913]
Borer control cannot be resisted. Using the resist verb returns no messages, nor does it stop the Borer's control after a period of time as it used to. Hosts are basically locked out of their characters without the option to even attempt fighting back. Sort of breaks the gamemode. Might be important to fix.

**Comment by halworsen** [comment]
Not that big of an issue. Borers are spawned by admins, so good control or just avoiding using borers altogether should do for now.
