### ISSUE TITLE
Multi-day sentences are broken

### ISSUE THREAD

**Issue by CakeQ** [Apollo-Community/ApolloStation#924]
A non-antag was sentenced to 1 day prison for neglect of duty but they ended up with 385 days.
https://gyazo.com/98c9a1b8e5af3ee3bbcccd94284f0a58

**Comment by Kwask** [comment]
:bell: shame :bell: 
someone still has internet explorer in their taskbar

**Comment by CakeQ** [comment]
not me :p

**Comment by Kwask** [comment]
Might be fixed in 00f6d6f9211797f353f780f9a8f8bdc164b1d5d3
