### ISSUE TITLE
Antag tokens aren't being given

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#931]
A player didn't get an antag token when they were supposed to get one.

**Comment by halworsen** [comment]
Could you elaborate? Who, when, where, etc.

**Comment by Kwask** [comment]
I'm not going to give their ckey so people won't metagame that info, but they got enough commendations that they should have gotten a commendation, but looking at the SQL they only had about 10% of a token

**Comment by CakeQ** [comment]
Can confirm that tokens are now being given out.
