### ISSUE TITLE
No Suit Cyclers in EVA or Engineering

### ISSUE THREAD

**Issue by Arrowhead154** [Apollo-Community/ApolloStation#935]
There's a Suit Cycler in Atmos for engineering, but not one anywhere else, and there's only a suit storage unit in EVA, not a Cycler.

**Comment by CakeQ** [comment]
LOOK, LOOK WITH YOUR SPECIAL EYES
engineering has a suit cycler already, and EVA storage doesn't really need one (has all race suits already)
