### ISSUE TITLE
Shuttles not moving area code

### ISSUE THREAD

**Issue by CakeQ** [Apollo-Community/ApolloStation#938]
Often leads to the shuttle having no power after jump etc. Merc shuttle ends up without power, making the gamemode unplayable

**Comment by Kwask** [comment]
This is a really important bug to fix, the merc gamemode cannot be played until this is fixed

**Comment by rjtwins** [comment]
Two more weeks until I get back. And I'll fix it.

**Comment by rjtwins** [comment]
Shuttles are not supposed to move area code, I think I know what was going wrong. Did some patching and local test show the issue is resolved. Need feedback tough.
