### ISSUE TITLE
CMO doesn't have access to the lower south east maintenance (leading to the disposal/incinerator and the private quarters)

### ISSUE THREAD

**Issue by Pygmali** [Apollo-Community/ApolloStation#942]
CMO doesn't have access to the lower south east maintenance (leading to the disposal/incinerator and the private quarters)

**Comment by CakeQ** [comment]
why would they?

**Comment by Pygmali** [comment]
Why shouldn't they ? everyone else have access there, and because as viro, you throw dead monkey in the disposal to burn them, but you don't have access to the incinerator anymore to turn it on
You have acces to all the others maintenance, only this one is locked

**Comment by CakeQ** [comment]
nobody except janitor / supply / engineering / sec / assistant should have access to maintenance. The only exceptions are maintenance areas leading to private quarters.

**Comment by Pygmali** [comment]
There is private quarters down there

**Comment by CakeQ** [comment]
which can be accessible from the other way around, yes.

**Comment by Pygmali** [comment]
Nop, can't either with cmo access, I tried to go ther to the two ends, none are working

**Comment by CakeQ** [comment]
Well this is a feature anyways, so this can be closed
