### ISSUE TITLE
Only Asteroid Spawned On Same Tile As The Apollo

### ISSUE THREAD

**Issue by Kalanken** [Apollo-Community/ApolloStation#950]
https://i.gyazo.com/533e333adcc7da1458c60d70690af0f5.png

That should explain it. When I tried to go over there, it only allowed me to visit the Apollo, plus I hardly had enough fuel to make it back to the place where the miners are set up at. I am incapable of doing my job, which I'm really not sure how to react to.

[I'm really bad at reports like these. Sorry. Ask questions if they're needed.]

**Comment by Kwask** [comment]
You can use the bluespace gates to telephort between the mining vessel and the Apollo btw, that way you don't have to use fuel to get there
