### ISSUE TITLE
Crash as AI

### ISSUE THREAD

**Issue by FoinGRC** [Apollo-Community/ApolloStation#952]
When i'm in the AI core, the game crash every few minut. window seven ask to "close program or wait" waiting look useless.
Never crash when i play other character.
Thank to try to fix that, i love play as AI ^^

**Comment by Kwask** [comment]
Was there anything specific that you do when it crashes? Like maybe jumping to a new character, or opening some menu?

**Comment by FoinGRC** [comment]
when start tracking a specific crew member with camera. (but not always)
Or in middle of displacement.

**Comment by Andrew-Fall** [comment]
I can also confirm, it appears to happen most often when you warp to someone.

**Comment by Kwask** [comment]
Fixed in affd98ddaf035b099324e831a4a5307ff240a461
