### ISSUE TITLE
Cargo shuttle not spawning cargo

### ISSUE THREAD

**Issue by Hikurac** [Apollo-Community/ApolloStation#953]
Been playing cargo for several days now, and I noticed that the shuttle would sometimes not transfer the cargo. The issue has progressed, and it seems that I cannot get any cargo at all now, no matter how many times I try, and the worst part is that it still uses up the supply points.

**Comment by rjtwins** [comment]
I will look into this.

**Comment by FoinGRC** [comment]
i can confirm : 
In multiple shift : 
I have ordered many thing for stock. For first call, shuttle delivers many of my orders (but not all)
After that, shuttle don't deliver anything. (cargo and cockpit empty)
i have tryed with 1, 2, 3 or more orders, same.

**Comment by stuicey** [comment]
was this actually fixed?

**Comment by CakeQ** [comment]
yes, praise be rj

**Comment by rjtwins** [comment]
It seems it was not

**Comment by rjtwins** [comment]
AAGGH !, I cant seem to reproduce this problem. Been trying to all morning.

**Comment by rjtwins** [comment]
I found the problem.. apparently the order list gets messed up when something is approved when the shuttle is flying from the station to cc. So if you approve an order when its flying back that can (does not always happen... no clue why :( ) mess up the list. I've made it so you cannot aprove orders when the shuttle is on station or flying back for now as a temp fix. Still working on it tough.
