### ISSUE TITLE
Engine Cooling Control

### ISSUE THREAD

**Issue by Andrew-Fall** [Apollo-Community/ApolloStation#955]
It appears you cannot connect a new coolant injector to the original Engine Cooling Control, even after removing the old injector. You also cannot use Engine Vent Pumps, they simply don't pull out gas.

**Comment by rjtwins** [comment]
Fixed, you can no replace both. Just get them from the pipe dispenser, wrench down multi-tool tag the vent/injector. multi-tool the Engine Cooling Controle computer and done.
