### ISSUE TITLE
Traitor unable to access the equipment menu

### ISSUE THREAD

**Issue by Kwask** [Apollo-Community/ApolloStation#956]
When they clicked on it, nothing would happen

Faction was Tiger Cooperative
Gammode was AutoTraitor

**Comment by CakeQ** [comment]
Was a shuttle call in progress? Otherwise IDK about this issue. Very vague and nothing we can really do about it with the current info,

**Comment by astralenigma** [comment]
Well there was one time where the traitor got a headset frequency they were unable to change to because the number after the dot is odd and the frequency was asking for an even number.
