### ISSUE TITLE
No damaged sprite for roads

### ISSUE THREAD

**Issue by stuicey** [Apollo-Community/ApolloStation#965]
Since roads are not part of `floors.dmi` they cannot access the damaged sprites like other tiles can. Hence when they are damaged - they turn into black tiles.

![](https://i.imgur.com/2eY6Z9h.png)

A possible solution would be to move the tiles into `floors.dmi` along with the rest of the base tiles - or recreate some damaged sprites specifically for roads.

**Comment by Kwask** [comment]
It'd be better if someone just made some damage overlays that you can apply to all floor sprites and add them as an overlay, rather than this nonsense of creating a new sprite for every floor type

**Comment by stuicey** [comment]
should be relatively easy to convert the damage sprites into an overlay
