### ISSUE TITLE
Scientists do not have access to the R&D maintenance door.

### ISSUE THREAD

**Issue by Newper5** [Apollo-Community/ApolloStation#970]
Scientists' maintenance access seems very confusing altogether, actually.  They can use some maintenance doors (tested near arrivals and with the outer-ring medbay maintenance) but not others (like the inner-ring medbay maintenance, the port dorm maintenance, or a lot of the science maintenance).

**Comment by CakeQ** [comment]
Some maintenance tunnels have no access requirements if they lead to a private quarter. From then on they become access restricted to maintenance access

**Comment by Newper5** [comment]
Even when access requirements are revoked during radiation storms, it stays locked.  I think its settings are just wrong.
