### ISSUE TITLE
Vacuum floors II: The redemgance

### ISSUE THREAD

**Issue by Metichi** [Apollo-Community/ApolloStation#978]
They are back and angrier than ever! (In roughly all the same spots)

**Comment by stuicey** [comment]
Details please :v

**Comment by Metichi** [comment]
http://puu.sh/pLigs/ecf5285e52.jpg
Thats today just now, after cake's fix from yesterday

**Comment by stuicey** [comment]
I'm starting to think cake hasn't pushed it

**Comment by Metichi** [comment]
I think I remember him pushing it, because it caused a few atmos issues, but I cant say 100% sure

**Comment by stuicey** [comment]
Had a look at the ingame update script and determined the problem. 

```
#Compile `apollo.dme` and output to `data/update_log.txt`
DreamMaker apollo.dme >> data/update_log.txt &
#Hot swap the resource file (rsc)
[...]
```

The `&` at the end of the line runs that command in the background which then runs the next command immediately - before the server finishes compiling.

I've restructured the command and it should work as intended now.
