### ISSUE TITLE
MASTER-FORK: Map Issues

### ISSUE THREAD

**Issue by hexagoncode** [Apollo-Community/ApolloStation#98]
- [x] The escape shuttle seems to be misaligned with departures now.

**Comment by GutsySS13** [comment]
looks like one of the merges has updated the centcom apollo map 2 to a new shuttle but not updated the escape area on apollo map 1 to match. one of them has to change or no one is gonna be escaping anytime soon.

**Comment by GutsySS13** [comment]
Kwask says that the gladiator ring is also broken so no doubt lots of other stuff on this Z level may also be broken so keep those eyes peeled. I'm busy tomorrow but will have a bit of a dig if I get some time and over the weekend (also my ISP is on the fritz).

**Comment by Kwask** [comment]
- [x] Thunderdome
- [x] Telecomms sat

**Comment by Anonanimal** [comment]
- [x] Mass driver buttons missing (Chapel, engine, waste disposal, bomb testing, etc.)
- [x] Deployed roller beds missing

**Comment by lmas** [comment]
I've fixed all maps except apollo-2, which dreammaker is even unable to read for some reason. Can't get a list of broken stuff in it. Don't know how to fix or debug it.

**Comment by lmas** [comment]
Nevermind, got list of map errors when I tried to compile. All maps have been fixed now.
