### ISSUE TITLE
Range on removing pod parts and bluespace gates

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#980]
1. I saw the bluespace gate that shows up when you recall a shuttle sucked a station intercomm off the walls.  Other anchored machinery like the podbay R&D console and relevant lathes, plus tables didn't move.
2. Prying stuff out of a pod (IDs, engines, etc) has no range.  You can do it whenevs.  This is normally harmless, but a pod ID can be swapped with, say, the captain's ID.  So you can be searched, arrested, and then suddenly manifest an all-access if you really wanted to go to that trouble.  Easy fix!  Add range check.

**Comment by halworsen** [comment]
1. is intentional, there should even be a popup saying "don't recall if the shuttle is inside the station"
