### ISSUE TITLE
Latejoin traitors have their ID name wrong

### ISSUE THREAD

**Issue by Metichi** [Apollo-Community/ApolloStation#982]
If you late join a round and are assigned as a traitor, your character gets replaced with a rando, but your ID still states your original name.

**Comment by stuicey** [comment]
I thought this was fixed a while ago?

**Comment by Metichi** [comment]
It happened twice today

**Comment by stuicey** [comment]
@kwask I recon this is happening because of the lifetime ID card.

**Comment by Kwask** [comment]
yeah, that's actually probably a good lead

**Comment by stuicey** [comment]
`/proc/EquipCustomItems(mob/living/carbon/human/M)`

I recon if you just change `M` to `C` then it will fix it -

```
var/obj/item/weapon/card/id/I = Item
for(var/obj/item/weapon/card/id/C in M)
    I.name = "[M.real_name]'s ID Card ([M.mind.role_alt_title ? M.mind.role_alt_title : 
```

**Comment by stuicey** [comment]
Happening on regular ID cards too? Did someone screw the code

**Comment by Kwask** [comment]
Was this fixed?

**Comment by dontdothis** [comment]
it happened to me yesterday, but i don't know how often you update the server so.
tentatively not fixed.  really troublesome please fix thanks

**Comment by DreadedReborn** [comment]
It also happened to me one time I got mid-round antag with a character using the lifetime id. Didn't change my PDA either, though.
EDIT : The 'one time' happened in the last 2-3 days, iirc.
