### ISSUE TITLE
AI and ghosting client crashes

### ISSUE THREAD

**Issue by Metichi** [Apollo-Community/ApolloStation#983]
It was commented that the AI crashes the client for unknown reasons, its also happening to me while gosting and jumping to people, probably related.

**Comment by Kwask** [comment]
This is confirmed that its still happening today? I thought I fixed this yesterday #952

**Comment by Metichi** [comment]
My client is freezing a lot now, maybe its an issue on my end im not sure

**Comment by Kwask** [comment]
What OS and BYOND version are you using?

**Comment by Metichi** [comment]
Windows 10 and 510.1345, Im updating to 1347 now

**Comment by Kwask** [comment]
Try updating to the most recent version of BYOND and see if its still doing it http://www.byond.com/download/
