### ISSUE TITLE
Spawning with two survival kits.

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#984]
Since I got promoted to scientist I spawn with two survival kits each with supplies. Incase it's a character specific bug the character is Avery Hunter.

**Comment by CakeQ** [comment]
A screenshot would be helpful

**Comment by ghost** [comment]
![twokits](https://cloud.githubusercontent.com/assets/20270682/16571231/fda53b0e-4225-11e6-9be4-b7df90bd1bb9.png)

**Comment by CakeQ** [comment]
fixed
