### ISSUE TITLE
Nanopaste

### ISSUE THREAD

**Issue by dontdothis** [Apollo-Community/ApolloStation#997]
Nanopaste cannot be used to repair robot limbs.

Nanopaste checks if the limb you apply it to has open = 1 for when you try to fix external organs (limbs).  Open is set to 1 when you scalpel a limb-- for organic limbs.  There is no way to set a robotic limb to open, and that check was erroneously put there.  If you delete the open check, nanopaste should work as intended.

**Comment by Kwask** [comment]
Is nanopaste supposed to be used for robotics limbs? Last I knew cable coil and welders were to be used to repair robotic limbs

**Comment by CakeQ** [comment]
nanopaste is for repairing bone fractures. They aren't use for repairing mechanical limbs.

**Comment by stuicey** [comment]
As far as I know you use nanopaste for restoring machine integrity and for mechanical organs

**Comment by CakeQ** [comment]
Rjtwins has confirmed that Nanopaste is supposed to be used to repair mechanical organs, not limbs.

**Comment by bryanlavergne** [comment]
Nanopaste was able to fix robotic limbs in the paste. In fact, there seems to be a big discontinuity here as cyborgs can be repaired with nanopaste, which includes the same limbs as prosthetic limbs.

If you check the code you will see that there exists two separate lines of text that the user can receive. One says "Nothing to fix here." while the other says "Nothing to fix in here.". Notice how one of them actually specifies "in".

Even moreso, the comment in that attack proc says that it's used for repairing "robolimbs".

Allowing to repair cyborgs but not robotic limbs on humans doesn't make sense.
